import { StyleSheet } from "react-native";

import { T } from "@/lib/theme";
import { cardBase, cardElevated } from "@/lib/ui";

export const debtStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: T.bg },
  center: { flex: 1, justifyContent: "center", alignItems: "center", gap: 12 },
  scroll: { paddingBottom: 140 },
  heroRow: { flexDirection: "row", gap: 10, padding: 14, paddingBottom: 0 },
  heroCard: {
    flex: 1,
    padding: 16,
    gap: 2,
    ...cardBase,
    borderWidth: 1,
  },
  heroLabel: { color: T.textDim, fontSize: 10, fontWeight: "800", letterSpacing: 0.6 },
  heroValue: { fontSize: 22, fontWeight: "900", marginTop: 4 },
  heroSub: { color: T.textMuted, fontSize: 11, fontWeight: "600", marginTop: 2 },
  termWrap: { width: "100%", gap: 8 },
  inlineRow: { flexDirection: "row", gap: 10, alignItems: "flex-start" },
  termLabel: { color: T.textDim, fontSize: 12, fontWeight: "800" },
  termRow: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginTop: 8, marginBottom: 10 },
  termBtn: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.cardAlt,
  },
  termBtnActive: { borderColor: T.accent, backgroundColor: `${T.accent}2A` },
  termBtnTxt: { color: T.textDim, fontSize: 12, fontWeight: "700" },
  termBtnTxtActive: { color: T.accent, fontWeight: "800" },
  cardChoiceWrap: { gap: 8 },
  cardChoiceBtn: {
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: 8,
    backgroundColor: T.cardAlt,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  cardChoiceBtnActive: { borderColor: T.accent, backgroundColor: `${T.accent}2A` },
  cardChoiceTxt: { color: T.text, fontSize: 13, fontWeight: "700" },
  cardChoiceTxtActive: { color: T.accent, fontWeight: "800" },
  cardChoiceEmpty: { color: T.textDim, fontSize: 12, fontWeight: "700" },
  chartCard: { margin: 14, marginBottom: 0, padding: 14, gap: 12, ...cardBase },
  chartHeader: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between" },
  chartTitle: { color: T.text, fontSize: 14, fontWeight: "900" },
  chartSub: { color: T.textMuted, fontSize: 11, fontWeight: "600", marginTop: 2 },
  chartBadge: { backgroundColor: T.accentDim, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 4, borderWidth: 1, borderColor: T.accentFaint },
  chartBadgeTxt: { color: T.accent, fontSize: 12, fontWeight: "800" },
  analyticsBtn: { flexDirection: "row", alignItems: "center", gap: 2, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8, backgroundColor: T.accentDim, borderWidth: 1, borderColor: T.accentFaint },
  analyticsBtnTxt: { color: T.accent, fontSize: 11, fontWeight: "800" },
  milestoneRow: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 6 },
  milestoneLabel: { color: T.textMuted, fontSize: 11, fontWeight: "700", marginRight: 2 },
  milestoneChip: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: T.cardAlt,
    borderWidth: 1,
    borderColor: T.border,
  },
  milestoneChipActive: { borderColor: T.accent, backgroundColor: T.accentDim },
  milestoneChipText: { color: T.textDim, fontSize: 11, fontWeight: "700" },
  milestoneChipTextActive: { color: T.accent },
  chipRow: { flexDirection: "row", gap: 8 },
  chip: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    padding: 10,
    borderRadius: 12,
    backgroundColor: T.cardAlt,
    borderWidth: 1,
  },
  chipLabel: { color: T.textMuted, fontSize: 9, fontWeight: "800", letterSpacing: 0.4 },
  chipValue: { color: T.text, fontSize: 11, fontWeight: "800", marginTop: 1 },
  tipsCard: { margin: 14, marginTop: 6, padding: 14, ...cardBase },
  tipsHeader: { flexDirection: "row", alignItems: "center", gap: 6, marginBottom: 8 },
  tipsHeading: { color: T.text, fontSize: 13, fontWeight: "900" },
  tipRow: { flexDirection: "row", paddingVertical: 6 },
  tipBorder: { borderTopWidth: 1, borderTopColor: T.border, marginTop: 6 },
  tipTitle: { color: T.text, fontSize: 13, fontWeight: "900" },
  tipDetail: { color: T.textDim, fontSize: 12, marginTop: 2, fontWeight: "600" },
  listHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 8,
  },
  listHeaderSpacer: { width: 1, height: 1 },
  filterToggle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    padding: 4,
    borderRadius: 24,
    backgroundColor: T.card,
    borderWidth: 1,
    borderColor: T.border,
  },
  filterToggleOption: {
    minWidth: 84,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  filterToggleOptionActive: {
    backgroundColor: T.accentDim,
    borderWidth: 1,
    borderColor: T.accent,
  },
  filterToggleText: { color: T.textDim, fontSize: 13, fontWeight: "800" },
  filterToggleTextActive: { color: T.text },
  addBtn: {
    backgroundColor: T.accent,
    borderRadius: 18,
    height: 36,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  addBtnTxt: { color: T.onAccent, fontSize: 13, fontWeight: "800" },
  addForm: { margin: 0, padding: 0, gap: 10 },
  input: {
    backgroundColor: T.cardAlt,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: T.text,
    fontSize: 14,
    borderWidth: 1,
    borderColor: T.border,
  },
  dateValue: { color: T.text, fontSize: 14, fontWeight: "600" },
  dateValuePlaceholder: { color: T.textMuted, fontWeight: "500" },
  dropdownAnchor: { position: "relative", zIndex: 20 },
  saveBtn: {
    backgroundColor: T.accent,
    borderRadius: 8,
    paddingVertical: 11,
    alignItems: "center",
    marginTop: 10,
  },
  saveBtnTxt: { color: T.onAccent, fontWeight: "700", fontSize: 14 },
  disabled: { opacity: 0.5 },
  card: {
    flexDirection: "row",
    marginHorizontal: 14,
    marginBottom: 10,
    overflow: "hidden",
    ...cardElevated,
  },
  cardPressed: { opacity: 0.75 },
  cardAccent: { width: 4 },
  cardBody: { flex: 1, padding: 14, gap: 8 },
  cardTop: { flexDirection: "row", alignItems: "flex-start" },
  cardLeft: { flex: 1 },
  cardRight: { alignItems: "flex-end" },
  cardTitleRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  avatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.cardAlt,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  avatarLogo: { width: "100%", height: "100%", borderRadius: 999 },
  avatarTxt: { color: T.textDim, fontSize: 12, fontWeight: "800" },
  cardName: { color: T.text, fontSize: 15, fontWeight: "900" },
  cardType: { fontSize: 11, fontWeight: "600", marginTop: 2 },
  cardBalance: { color: T.text, fontSize: 17, fontWeight: "900" },
  cardBalancePaid: { color: T.green },
  cardMonthly: { color: T.textDim, fontSize: 12, marginTop: 2, fontWeight: "600" },
  progressWrap: { gap: 4 },
  progressBg: { height: 7, backgroundColor: T.border, borderRadius: 4, overflow: "hidden" },
  progressFill: { height: "100%", borderRadius: 3 },
  progressPct: { color: T.textDim, fontSize: 11, fontWeight: "600" },
  cardFooter: { flexDirection: "row", alignItems: "center", gap: 10 },
  cardMetaStrong: { color: T.accent, fontSize: 12, fontWeight: "800" },
  cardMeta: { color: T.textDim, fontSize: 12, fontWeight: "600" },
  paidBadge: { flexDirection: "row", alignItems: "center", gap: 4 },
  paidBadgeText: { color: T.green, fontSize: 12, fontWeight: "600" },
  cardChevron: { color: T.textMuted, fontSize: 20 },
  empty: { alignItems: "center", paddingTop: 60, gap: 10 },
  emptyTitle: { color: T.text, fontSize: 16, fontWeight: "800" },
  emptySubtitle: { color: T.textDim, fontSize: 13 },
  errorText: { color: T.red, fontSize: 14, textAlign: "center", paddingHorizontal: 32 },
  retryBtn: { backgroundColor: T.accent, borderRadius: 8, paddingHorizontal: 24, paddingVertical: 10 },
  retryTxt: { color: T.onAccent, fontWeight: "700" },
  sheetOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0, 0, 0, 0.45)",
  },
  sheet: {
    backgroundColor: T.card,
    flex: 1,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderTopWidth: 1,
    borderTopColor: T.border,
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 22,
    gap: 10,
  },
  sheetScrollContent: { paddingBottom: 6 },
  sheetFormScroll: { flex: 1, minHeight: 0 },
  sheetHandle: {
    alignSelf: "center",
    width: 44,
    height: 4,
    borderRadius: 999,
    backgroundColor: T.border,
    marginBottom: 2,
  },
  sheetHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  sheetTitle: { color: T.text, fontWeight: "900", fontSize: 15 },
  sheetCloseBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.cardAlt,
    borderWidth: 1,
    borderColor: T.border,
  },
  dateSheetOverlay: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(0,0,0,0.45)" },
  dateSheetBackdrop: { ...StyleSheet.absoluteFillObject },
  dateSheetCard: {
    backgroundColor: T.card,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderTopWidth: 1,
    borderTopColor: T.border,
    paddingBottom: 18,
  },
  dateSheetHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: T.border,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  dateSheetTitle: { color: T.text, fontSize: 14, fontWeight: "800" },
  dateSheetCancel: { color: T.textDim, fontSize: 15, fontWeight: "700" },
  dateSheetDone: { color: T.accent, fontSize: 15, fontWeight: "800" },
});