import { Dimensions, StyleSheet } from "react-native";

import { T } from "@/lib/theme";
import { cardElevated, flatInput, flatInputLabel } from "@/lib/ui";

export const { height: ADD_EXPENSE_SHEET_SCREEN_H } = Dimensions.get("window");

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: "flex-end",
    paddingTop: 18,
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.62)",
  },
  sheet: {
    backgroundColor: T.bg,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    height: ADD_EXPENSE_SHEET_SCREEN_H * 0.925,
    borderWidth: 1,
    borderBottomWidth: 0,
    borderColor: T.border,
    overflow: "hidden",
    shadowColor: "#000000",
    shadowOpacity: 0.34,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: -10 },
    elevation: 24,
  },
  handle: {
    width: 48,
    height: 5,
    borderRadius: 999,
    backgroundColor: T.border,
    alignSelf: "center",
    marginTop: 12,
    marginBottom: 6,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: T.border,
  },
  title: { color: T.text, fontSize: 21, fontWeight: "900", letterSpacing: -0.3 },
  sub: { color: T.textMuted, fontSize: 12, fontWeight: "600", marginTop: 2 },
  periodRail: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 12,
  },
  periodIconBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: T.border,
  },
  periodIconBtnDisabled: {
    opacity: 0.32,
  },
  periodPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: `${T.accent}18`,
    borderWidth: 1,
    borderColor: `${T.accent}38`,
  },
  periodPillText: {
    color: T.text,
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  closeBtn: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 22,
    borderWidth: 1,
    borderColor: T.border,
    shadowColor: "#000000",
    shadowOpacity: 0.16,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },

  planPickerWrap: {
    marginHorizontal: 20,
    marginTop: 14,
    zIndex: 20,
  },
  planPickerButton: {
    ...flatInput,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  planPickerButtonOpen: {
    borderBottomColor: `${T.accent}cc`,
    backgroundColor: "transparent",
  },
  planPickerText: {
    color: T.text,
    fontSize: 18,
    fontWeight: "500",
    flex: 1,
  },
  planPickerMenu: {
    ...cardElevated,
    position: "absolute",
    top: 62,
    left: 0,
    right: 0,
    borderRadius: 20,
    borderColor: "rgba(244,246,255,0.08)",
    backgroundColor: T.cardAlt,
    overflow: "hidden",
    zIndex: 30,
  },
  planPickerOption: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderTopWidth: 1,
    borderTopColor: T.border,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  planPickerOptionFirst: {
    borderTopWidth: 0,
  },
  planPickerOptionActive: {
    backgroundColor: `${T.accent}14`,
  },
  planPickerOptionText: {
    color: T.text,
    fontSize: 14,
    fontWeight: "600",
    flex: 1,
  },
  planPickerOptionTextActive: {
    color: T.accent,
    fontWeight: "800",
  },

  scrollContent: {
    paddingTop: 6,
    paddingBottom: 144,
    gap: 16,
  },
  formScroll: {
    marginHorizontal: 20,
    paddingHorizontal: 0,
    paddingVertical: 6,
    gap: 18,
  },

  halfRow: {
    flexDirection: "row",
    gap: 12,
    alignItems: "flex-start",
  },
  halfCol: {
    flex: 1,
    minWidth: 0,
  },

  fieldGroup: { gap: 10 },
  label: {
    ...flatInputLabel,
    color: "rgba(244,246,255,0.66)",
  },
  optional: { color: T.textDim, fontWeight: "700", letterSpacing: 0.3 },
  input: {
    ...flatInput,
  },
  selectInputOpen: {
    borderBottomColor: `${T.accent}cc`,
    backgroundColor: "transparent",
  },
  selectRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  selectValueText: {
    color: T.text,
    fontSize: 18,
    fontWeight: "500",
    flex: 1,
  },
  dropdownMenu: {
    ...cardElevated,
    position: "absolute",
    top: 64,
    left: 0,
    right: 0,
    backgroundColor: T.cardAlt,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(244,246,255,0.08)",
    overflow: "hidden",
    zIndex: 40,
  },
  dropdownOption: {
    paddingHorizontal: 16,
    paddingVertical: 13,
    borderBottomWidth: 1,
    borderBottomColor: T.border,
  },
  dropdownOptionLast: {
    borderBottomWidth: 0,
  },
  dropdownOptionActive: {
    backgroundColor: `${T.accent}14`,
  },
  dropdownOptionText: {
    color: T.text,
    fontSize: 14,
    fontWeight: "700",
  },
  dropdownOptionTextActive: {
    color: T.accent,
    fontWeight: "800",
  },
  inlineWarning: {
    backgroundColor: "#f59e0b18",
    borderRadius: 14,
    padding: 12,
    marginTop: 6,
    borderWidth: 1,
    borderColor: "#f59e0b44",
  },
  inlineWarningText: {
    color: "#f59e0b",
    fontSize: 12,
    fontWeight: "700",
  },
  togglesWrap: {
    paddingHorizontal: 20,
    gap: 0,
  },

  toggleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 0,
    paddingVertical: 16,
    gap: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(244,246,255,0.08)",
  },
  toggleInfo: { flex: 1 },
  toggleTitle: { color: T.text, fontSize: 15, fontWeight: "800" },
  toggleSub: { color: T.textMuted, fontSize: 12, fontWeight: "600", marginTop: 4, lineHeight: 16 },
  toggle: {
    width: 52,
    height: 30,
    borderRadius: 15,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(244,246,255,0.10)",
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  toggleOn: {
    backgroundColor: `${T.accent}24`,
    borderColor: `${T.accent}88`,
  },
  toggleThumb: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "rgba(244,246,255,0.46)",
    alignSelf: "flex-start",
  },
  toggleThumbOn: {
    backgroundColor: T.accent,
    alignSelf: "flex-end",
    shadowColor: T.accent,
    shadowOpacity: 0.35,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },

  errorRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: `${T.red}15`,
    borderRadius: 14,
    padding: 13,
    borderWidth: 1,
    borderColor: `${T.red}55`,
  },
  errorTxt: { color: T.red, fontSize: 13, fontWeight: "700", flex: 1 },

  footerWrap: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 20,
    paddingTop: 8,
    backgroundColor: "transparent",
    alignItems: "stretch",
  },
  footerActionRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
  },

  submitBtn: {
    borderRadius: 999,
    alignSelf: "flex-end",
    overflow: "hidden",
    marginTop: 2,
    shadowColor: "#000000",
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: -2 },
    elevation: 8,
  },
  submitBtnGlass: {
    minHeight: 56,
    minWidth: 184,
    paddingHorizontal: 24,
    paddingVertical: 15,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.62)",
    backgroundColor: "rgba(255,255,255,0.78)",
    overflow: "hidden",
  },
  submitBtnTint: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  submitBtnGlow: {
    position: "absolute",
    width: 148,
    height: 148,
    borderRadius: 999,
    right: -20,
    top: -56,
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  submitBtnInnerBorder: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.38)",
  },
  submitBtnPressed: {
    transform: [{ scale: 0.985 }],
  },
  submitDisabled: { shadowOpacity: 0.08, elevation: 2 },
  submitTxt: { color: "#111827", fontSize: 16, fontWeight: "800", letterSpacing: -0.1 },

  dateModalSheet: {
    backgroundColor: T.card,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingBottom: 24,
  },
  dateModalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: T.border,
  },
  dateModalActionMuted: {
    color: T.textMuted,
    fontSize: 16,
    fontWeight: "600",
  },
  dateModalActionPrimary: {
    color: T.accent,
    fontSize: 16,
    fontWeight: "700",
  },
});

export const pr = StyleSheet.create({
  row: { gap: 10, paddingVertical: 4, paddingRight: 4 },
  pill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    minHeight: 44,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.045)",
    borderWidth: 1,
    borderColor: "rgba(244,246,255,0.10)",
  },
  pillSelected: {
    backgroundColor: T.accentDim,
    borderColor: T.accent,
  },
  dot: { width: 10, height: 10, borderRadius: 5 },
  pillTxt: { color: T.textDim, fontSize: 14, fontWeight: "700" },
  pillTxtSelected: { color: T.text, fontWeight: "900" },
});
