import { StyleSheet } from "react-native";

import { T } from "@/lib/theme";
import { cardElevated } from "@/lib/ui";

export const loggedExpensesStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: T.bg },
  content: { paddingBottom: 24 },
  purpleHero: {
    backgroundColor: "rgba(20,24,38,0.56)",
    paddingHorizontal: 20,
    paddingBottom: 30,
    alignItems: "center",
    overflow: "hidden",
    borderBottomLeftRadius: 34,
    borderBottomRightRadius: 34,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(244,246,255,0.16)",
  },
  purpleHeroLabel: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 15,
    fontWeight: "700",
    letterSpacing: 0.4,
  },
  purpleHeroAmount: {
    color: "#ffffff",
    fontSize: 52,
    fontWeight: "900",
    letterSpacing: -1,
    marginTop: 2,
  },
  purpleHeroMeta: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 16,
    fontWeight: "700",
    marginTop: 8,
  },
  sectionHeadingWrap: {
    paddingHorizontal: 14,
    paddingTop: 16,
    paddingBottom: 8,
  },
  sectionHeading: {
    color: T.textDim,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  swipeOuter: {
    marginHorizontal: 14,
    marginBottom: 8,
    borderRadius: 24,
    overflow: "hidden",
  },
  deleteActionWrap: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 56,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
  },
  deleteActionBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 82, 82, 0.55)",
    borderWidth: 1,
    borderColor: "rgba(255, 187, 187, 0.55)",
  },
  deleteActionBtnPressed: {
    opacity: 0.8,
  },
  card: {
    ...cardElevated,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 12,
    gap: 8,
    backgroundColor: "rgba(20,24,38,0.56)",
    borderColor: "rgba(244,246,255,0.16)",
    borderRadius: 24,
  },
  cardPressed: { opacity: 0.75 },
  cardDeleteReady: {
    borderColor: "rgba(255, 124, 124, 0.55)",
  },
  topRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  left: { flexDirection: "row", alignItems: "center", gap: 10, flex: 1, minWidth: 0 },
  right: { flexDirection: "row", alignItems: "center", gap: 6, flexShrink: 0 },
  iconWrap: {
    width: 36,
    height: 36,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
  },
  iconDot: { width: 10, height: 10, borderRadius: 5 },
  rowName: {
    color: T.text,
    fontSize: 16,
    fontWeight: "800",
    flex: 1,
  },
  rowMeta: {
    color: T.textDim,
    fontSize: 13,
    fontWeight: "600",
    textTransform: "capitalize",
    flex: 1,
  },
  rowMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingLeft: 46,
    gap: 10,
  },
  rowDate: {
    color: T.textMuted,
    fontSize: 12,
    fontWeight: "700",
    flexShrink: 0,
  },
  rowAmount: {
    color: T.text,
    fontSize: 17,
    fontWeight: "900",
  },
  track: {
    height: 6,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderRadius: 999,
    overflow: "hidden",
    marginTop: 6,
  },
  fill: { height: "100%", borderRadius: 999 },
  center: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 40,
    gap: 10,
  },
  empty: {
    color: T.textDim,
    fontSize: 14,
    fontWeight: "600",
  },
  error: {
    color: T.red,
    fontSize: 13,
    textAlign: "center",
  },
  retryBtn: {
    backgroundColor: T.accent,
    borderRadius: 10,
    paddingHorizontal: 18,
    paddingVertical: 10,
  },
  retryText: {
    color: T.onAccent,
    fontSize: 13,
    fontWeight: "800",
  },
});
