import { StyleSheet } from "react-native";
import { T } from "@/lib/theme";

export const styles = StyleSheet.create({
	wrap: {
		marginBottom: 16,
		gap: 14,
		alignItems: "stretch",
	},
	heroCard: {
		position: "relative",
		overflow: "hidden",
		alignItems: "center",
		borderRadius: 28,
		paddingHorizontal: 18,
		paddingTop: 30,
		paddingBottom: 20,
	},
	heroGlow: {
		position: "absolute",
		borderRadius: 999,
	},
	heroGlowPrimary: {
		width: 220,
		height: 220,
		top: -110,
		right: -46,
		backgroundColor: "rgba(124,92,255,0.22)",
	},
	heroGlowSecondary: {
		width: 180,
		height: 180,
		bottom: -90,
		left: -22,
		backgroundColor: "rgba(255,181,37,0.16)",
	},
	heroTitle: {
		color: T.text,
		fontSize: 16,
		fontWeight: "900",
		textAlign: "center",
		marginTop: 20,
	},
	chartShell: {
		width: "100%",
		alignItems: "center",
		justifyContent: "center",
		marginTop: 24,
		paddingVertical: 8,
	},
	chartHalo: {
		position: "absolute",
		width: 272,
		height: 272,
		borderRadius: 136,
		backgroundColor: "rgba(255,255,255,0.03)",
	},
	chartWrap: {
		width: 228,
		height: 228,
		alignItems: "center",
		justifyContent: "center",
	},
	centerLabel: {
		position: "absolute",
		alignItems: "center",
		justifyContent: "center",
		paddingHorizontal: 18,
		gap: 6,
	},
	centerTitle: {
		color: T.textDim,
		fontSize: 14,
		fontWeight: "800",
		textAlign: "center",
	},
	centerValue: {
		color: T.text,
		fontSize: 21,
		fontWeight: "900",
	},
	centerValuePositive: {
		color: T.green,
	},
	centerValueOver: {
		color: T.red,
	},
	centerSub: {
		color: T.textDim,
		fontSize: 12,
		fontWeight: "700",
		textAlign: "center",
		lineHeight: 18,
	},
	heroStatsRow: {
		width: "100%",
		flexDirection: "row",
		gap: 10,
		marginTop: 18,
	},
	heroStatCard: {
		flex: 1,
		borderRadius: 18,
		backgroundColor: "rgba(255,255,255,0.05)",
		borderWidth: 1,
		borderColor: "rgba(255,255,255,0.08)",
		paddingHorizontal: 12,
		paddingVertical: 12,
		gap: 4,
	},
	heroStatLabel: {
		color: T.textMuted,
		fontSize: 11,
		fontWeight: "700",
	},
	heroStatValue: {
		color: T.text,
		fontSize: 15,
		fontWeight: "900",
	},
	legendRow: {
		marginTop: 24,
		flexDirection: "row",
		gap: 8,
		justifyContent: "center",
		flexWrap: "wrap",
		paddingHorizontal: 12,
	},
	legendChip: {
		flexDirection: "row",
		alignItems: "center",
		gap: 6,
		paddingHorizontal: 10,
		paddingVertical: 6,
		borderRadius: 999,
		backgroundColor: "rgba(255,255,255,0.04)",
		borderWidth: 1,
		borderColor: "rgba(255,255,255,0.06)",
	},
	legendDot: {
		width: 8,
		height: 8,
		borderRadius: 4,
	},
	legendLabel: {
		color: T.textDim,
		fontSize: 11,
		fontWeight: "700",
	},
	legendValue: {
		color: T.text,
		fontSize: 11,
		fontWeight: "800",
	},
});
