import { StyleSheet } from "react-native";

import { T } from "@/lib/theme";

export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: T.bg },
  center: { flex: 1, justifyContent: "center", alignItems: "center", gap: 12 },
  scroll: { paddingHorizontal: 14, paddingTop: 0, gap: 14 },
  sectionCard: {
    position: "relative",
    overflow: "hidden",
    borderRadius: 24,
    padding: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    backgroundColor: "#141826",
    shadowColor: "#000000",
    shadowOpacity: 0.2,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  sectionGlow: {
    position: "absolute",
    borderRadius: 999,
  },
  sectionGlowPrimary: {
    width: 180,
    height: 180,
    top: -92,
    right: -56,
    backgroundColor: "rgba(124,92,255,0.16)",
  },
  sectionGlowSecondary: {
    width: 140,
    height: 140,
    bottom: -78,
    left: -44,
    backgroundColor: "rgba(68,126,255,0.08)",
  },
  sectionInnerBorder: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.03)",
  },
  sectionTitle: { color: T.text, fontSize: 16, fontWeight: "900", letterSpacing: -0.3, marginTop: 2 },
  errorText: { color: T.red, fontSize: 14, textAlign: "center", paddingHorizontal: 32 },
  retryBtn: { backgroundColor: T.accent, borderRadius: 8, paddingHorizontal: 24, paddingVertical: 10 },
  retryTxt: { color: T.onAccent, fontWeight: "700" },
  bottomActionsWrap: {
    position: "absolute",
    left: 14,
    right: 14,
    bottom: 12,
    paddingHorizontal: 14,
  },
  bottomActionsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  bottomActionBtn: {
    width: 108,
    minHeight: 46,
    borderRadius: 999,
    overflow: "hidden",
    shadowColor: "#000000",
    shadowOpacity: 0.16,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: -2 },
    elevation: 8,
  },
  bottomActionGlass: {
    minHeight: 46,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.72)",
    backgroundColor: "rgba(255,255,255,0.78)",
    overflow: "hidden",
  },
  bottomActionTint: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(255,255,255,0.34)",
  },
  bottomActionTintEdit: {
    backgroundColor: "rgba(255,255,255,0.18)",
  },
  bottomActionTintDelete: {
    backgroundColor: "rgba(245,247,250,0.22)",
  },
  bottomActionGlow: {
    position: "absolute",
    width: 110,
    height: 110,
    borderRadius: 999,
  },
  bottomActionGlowEdit: {
    right: -20,
    top: -34,
    backgroundColor: "rgba(255,255,255,0.34)",
  },
  bottomActionGlowDelete: {
    left: -18,
    bottom: -42,
    backgroundColor: "rgba(255,255,255,0.28)",
  },
  bottomActionInnerBorder: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.38)",
  },
  bottomActionTxt: {
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: -0.2,
    color: "#162033",
  },
});