import { StyleSheet } from "react-native";

import { T } from "@/lib/theme";

export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: T.bg },
  center: { flex: 1, justifyContent: "center", alignItems: "center", gap: 12 },
  scroll: { paddingHorizontal: 14, paddingTop: 0, gap: 14 },
  detailModeSwitch: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    padding: 5,
    borderRadius: 999,
    backgroundColor: "#141826",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    marginHorizontal: 4,
    marginBottom: 2,
  },
  detailModeOption: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 11,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
  },
  detailModeOptionActive: {
    backgroundColor: "rgba(124,92,255,0.18)",
    borderWidth: 1,
    borderColor: "rgba(124,92,255,0.34)",
  },
  detailModeText: {
    color: T.textDim,
    fontSize: 14,
    fontWeight: "800",
  },
  detailModeTextActive: {
    color: T.text,
  },
  projectionSection: {
    gap: 12,
    paddingHorizontal: 4,
    paddingBottom: 4,
  },
  sectionCard: {
    position: "relative",
    overflow: "hidden",
    borderRadius: 24,
    padding: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    backgroundColor: "#141826",
    shadowColor: "#000000",
    shadowOpacity: 0.2,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  sectionGlow: {
    position: "absolute",
    borderRadius: 999,
  },
  sectionGlowPrimary: {
    width: 180,
    height: 180,
    top: -92,
    right: -56,
    backgroundColor: "rgba(124,92,255,0.16)",
  },
  sectionGlowSecondary: {
    width: 140,
    height: 140,
    bottom: -78,
    left: -44,
    backgroundColor: "rgba(68,126,255,0.08)",
  },
  sectionInnerBorder: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.03)",
  },
  sectionTitle: { color: T.text, fontSize: 16, fontWeight: "900", letterSpacing: -0.3, marginTop: 2 },
  projectionTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  projectionHeader: {
    flex: 1,
    alignItems: "flex-start",
    gap: 4,
    marginBottom: 2,
  },
  projectionBalanceLabel: {
    color: T.text,
    fontSize: 15,
    fontWeight: "800",
  },
  projectionBalanceValue: {
    color: T.text,
    fontSize: 28,
    fontWeight: "900",
    letterSpacing: -0.7,
  },
  projectionBalanceSub: {
    fontSize: 13,
    fontWeight: "800",
  },
  projectionBalanceSubNeutral: {
    color: T.textDim,
  },
  projectionBalanceSubPositive: {
    color: T.green,
  },
  projectionBalanceSubNegative: {
    color: T.red,
  },
  projectionLogoCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    overflow: "hidden",
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
  },
  projectionLogoImage: {
    width: "86%",
    height: "86%",
    borderRadius: 999,
  },
  projectionLogoFallback: {
    color: T.text,
    fontSize: 20,
    fontWeight: "900",
  },
  projectionMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    gap: 14,
    marginTop: 2,
  },
  projectionMetaItem: {
    alignItems: "center",
    minWidth: 104,
    gap: 2,
  },
  projectionMetaLabel: {
    color: T.textDim,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.3,
  },
  projectionMetaValue: {
    color: T.text,
    fontSize: 16,
    fontWeight: "900",
    letterSpacing: -0.2,
  },
  projectionMetaValuePositive: {
    color: T.green,
  },
  projectionMetaValueWarning: {
    color: T.orange,
  },
  projectionMetaDivider: {
    width: 1,
    height: 28,
    backgroundColor: "rgba(255,255,255,0.10)",
  },
  errorText: { color: T.red, fontSize: 14, textAlign: "center", paddingHorizontal: 32 },
  retryBtn: { backgroundColor: T.accent, borderRadius: 8, paddingHorizontal: 24, paddingVertical: 10 },
  retryTxt: { color: T.onAccent, fontWeight: "700" },
  bottomActionsWrap: {
    position: "absolute",
    left: 14,
    right: 14,
    bottom: 12,
    paddingHorizontal: 14,
  },
  bottomActionsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  bottomActionBtn: {
    flex: 1,
    minHeight: 46,
    borderRadius: 999,
    overflow: "hidden",
    shadowColor: "#000000",
    shadowOpacity: 0.16,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: -2 },
    elevation: 8,
  },
  bottomPrimaryActionBtn: {
    flex: 1.6,
  },
  bottomIconActionBtn: {
    width: 74,
    flex: 0.62,
  },
  bottomActionGlass: {
    minHeight: 46,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.72)",
    backgroundColor: "rgba(255,255,255,0.78)",
    overflow: "hidden",
  },
  bottomActionGlassPayment: {
    backgroundColor: "rgba(255,255,255,0.10)",
    borderColor: "rgba(255,255,255,0.18)",
  },
  bottomActionTint: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(255,255,255,0.34)",
  },
  bottomActionTintEdit: {
    backgroundColor: "rgba(255,255,255,0.18)",
  },
  bottomActionTintDelete: {
    backgroundColor: "rgba(245,247,250,0.22)",
  },
  bottomActionTintPayment: {
    backgroundColor: "rgba(124,92,255,0.10)",
  },
  bottomActionGlow: {
    position: "absolute",
    width: 110,
    height: 110,
    borderRadius: 999,
  },
  bottomActionGlowEdit: {
    right: -20,
    top: -34,
    backgroundColor: "rgba(255,255,255,0.34)",
  },
  bottomActionGlowDelete: {
    left: -18,
    bottom: -42,
    backgroundColor: "rgba(255,255,255,0.28)",
  },
  bottomActionGlowPayment: {
    right: -14,
    top: -38,
    backgroundColor: "rgba(124,92,255,0.22)",
  },
  bottomActionInnerBorder: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.38)",
  },
  bottomActionInnerBorderPayment: {
    borderColor: "rgba(255,255,255,0.14)",
  },
  bottomActionContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  bottomActionTxt: {
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: -0.2,
    color: "#162033",
  },
  bottomActionTxtPrimary: {
    color: T.text,
  },
});