import { Dimensions, StyleSheet } from "react-native";

import { BRAND_BLUE, BRAND_GREEN } from "@/lib/constants";
import { T } from "@/lib/theme";
import { cardBase, cardElevated } from "@/lib/ui";

const MONEY_TOGGLE_WIDTH = Math.max(220, Dimensions.get("window").width - 32);
const MONEY_TOGGLE_TRACK_PADDING = 4;
const MONEY_TOGGLE_SEGMENT_WIDTH = (MONEY_TOGGLE_WIDTH - MONEY_TOGGLE_TRACK_PADDING * 2) / 2;

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: T.bg },
  content: { flex: 1 },
  center: { flex: 1, justifyContent: "center", alignItems: "center", gap: 12, paddingHorizontal: 24 },
  scroll: { paddingHorizontal: 16, paddingTop: 10, paddingBottom: 86 },
  scrollNoTop: { paddingTop: 0 },

  section: {
    ...cardBase,
    padding: 16,
    marginBottom: 14,
  },
  sectionHead: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  sectionTitle: { color: T.textDim, fontSize: 13, fontWeight: "800" },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: T.border,
    gap: 10,
  },
  rowLabel: { color: T.textDim, fontSize: 14, fontWeight: "700" },
  rowValue: { color: T.text, fontSize: 14, fontWeight: "800", maxWidth: "58%", textAlign: "right" },
  muted: { color: T.textDim, fontSize: 13, marginTop: 8 },

  profileCard: {
    ...cardElevated,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 12,
  },
  avatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: T.accent,
    justifyContent: "center",
    alignItems: "center",
  },
  avatarText: { color: T.onAccent, fontSize: 22, fontWeight: "700" },
  profileName: { color: T.text, fontSize: 18, fontWeight: "900" },
  profileSub: { color: T.textDim, fontSize: 13, marginTop: 2, fontWeight: "600" },

  outlineBtn: {
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.cardAlt,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  outlineBtnText: { color: T.textDim, fontSize: 12, fontWeight: "800" },

  primaryBtn: {
    backgroundColor: T.accent,
    borderRadius: 10,
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  primaryBtnText: { color: T.onAccent, fontWeight: "800", fontSize: 13 },
  inlineAction: { marginTop: 10, alignSelf: "flex-start" },
  inlineActionText: { color: T.accent, fontSize: 12, fontWeight: "800" },

  twoColRow: {
    flexDirection: "row",
    gap: 14,
    marginBottom: 16,
  },
  halfCol: {
    flex: 1,
  },
  plainBudgetBlock: {
    marginBottom: 16,
  },
  plainSavingsBlock: {
    marginBottom: 16,
  },
  moneyToggleWrap: {
    flexDirection: "row",
    width: MONEY_TOGGLE_WIDTH,
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: 999,
    backgroundColor: T.cardAlt,
    padding: MONEY_TOGGLE_TRACK_PADDING,
    marginBottom: 20,
    position: "relative",
  },
  moneyToggleThumb: {
    position: "absolute",
    left: MONEY_TOGGLE_TRACK_PADDING,
    top: MONEY_TOGGLE_TRACK_PADDING,
    width: MONEY_TOGGLE_SEGMENT_WIDTH,
    height: 33,
    borderRadius: 999,
    backgroundColor: `${T.accent}30`,
    borderWidth: 1,
    borderColor: `${T.accent}73`,
  },
  moneyTogglePill: {
    width: MONEY_TOGGLE_SEGMENT_WIDTH,
    borderRadius: 999,
    paddingVertical: 7,
    alignItems: "center",
    justifyContent: "center",
  },
  moneyToggleTxt: {
    color: T.textDim,
    fontSize: 12,
    fontWeight: "800",
  },
  moneyToggleTxtActive: {
    color: T.text,
  },
  moneySectionCard: {
    ...cardBase,
    padding: 12,
    marginBottom: 12,
  },
  moneyTabSurface: {
    backgroundColor: "transparent",
    borderWidth: 0,
    borderColor: "transparent",
    borderRadius: 0,
    marginHorizontal: -16,
    paddingHorizontal: 16,
    paddingTop: 0,
    paddingBottom: 12,
    marginBottom: 8,
  },
  savingsTilesRow: {
    gap: 12,
    paddingRight: 2,
  },
  savingsSectionStack: {
    marginBottom: 0,
  },
  savingsSectionTitle: {
    color: T.text,
    fontSize: 13,
    fontWeight: "800",
    marginBottom: 8,
    paddingHorizontal: 2,
  },
  savingsTileCard: {
    ...cardBase,
    backgroundColor: BRAND_GREEN,
    borderColor: "rgba(11,46,62,0.16)",
    borderRadius: 16,
    padding: 12,
    justifyContent: "space-between",
  },
  savingsTileTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
  },
  savingsTileIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(8,44,66,0.16)",
  },
  savingsTileAddCard: {
    ...cardBase,
    backgroundColor: BRAND_GREEN,
    borderColor: "rgba(11,46,62,0.16)",
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  savingsTileAddText: {
    fontSize: 11,
    fontWeight: "800",
    textAlign: "center",
  },
  savingsTileTitle: {
    color: "#0b2e3e",
    fontSize: 13,
    fontWeight: "800",
  },
  savingsTileValue: {
    color: "#071f34",
    fontSize: 24,
    fontWeight: "900",
  },
  savingsTileHint: {
    color: "#123e56",
    fontSize: 10,
    fontWeight: "600",
    lineHeight: 13,
  },
  plainSectionHeadRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  cardMiniActionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  cardMiniIconBtn: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: `${T.border}55`,
  },
  plainBudgetTitle: {
    color: T.textDim,
    fontSize: 13,
    fontWeight: "800",
    marginBottom: 10,
    paddingHorizontal: 2,
  },
  infoCard: {
    ...cardBase,
    borderRadius: 14,
    padding: 14,
    marginBottom: 16,
  },
  halfCard: {
    flex: 1,
    marginBottom: 0,
  },
  infoCardLabel: { color: T.textDim, fontSize: 12, fontWeight: "700", marginBottom: 4 },
  infoCardValue: { color: T.text, fontSize: 16, fontWeight: "900" },
  infoCardHint: { color: T.textDim, fontSize: 12, fontWeight: "600", marginTop: 6 },
  savingsCardHead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 2,
  },
  savingsIconWrap: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: `${T.border}55`,
  },
  cardRowCenter: { flexDirection: "row", alignItems: "center", gap: 8 },

  circleAddBtn: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.accent,
  },

  debtCard: {
    ...cardBase,
    paddingHorizontal: 14,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 10,
  },
  debtCardBody: {
    flex: 1,
    paddingRight: 4,
  },
  debtTypeBlock: {
    marginBottom: 12,
  },
  debtTypeHead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  debtTypeIconWrap: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: `${T.border}55`,
  },
  debtTypeTitle: {
    color: T.textDim,
    fontSize: 12,
    fontWeight: "800",
    flex: 1,
  },
  debtTypeCount: {
    color: T.textMuted,
    fontSize: 12,
    fontWeight: "700",
  },
  debtRow: {
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: 10,
    padding: 10,
    marginBottom: 8,
  },
  debtName: { color: T.text, fontSize: 14, fontWeight: "800" },
  debtSub: { color: T.textDim, fontSize: 12, marginTop: 3, fontWeight: "600" },
  limitWrap: { marginTop: 8, flexDirection: "row", gap: 8 },
  limitInput: {
    flex: 1,
    backgroundColor: T.card,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: T.border,
    color: T.text,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  saveMiniBtn: {
    borderRadius: 8,
    backgroundColor: T.accent,
    paddingHorizontal: 10,
    justifyContent: "center",
  },
  saveMiniText: { color: T.onAccent, fontWeight: "800", fontSize: 12 },

  planRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: 10,
    padding: 10,
    marginBottom: 8,
  },
  planName: { color: T.text, fontSize: 14, fontWeight: "800" },
  planSub: { color: T.textDim, fontSize: 12, marginTop: 2, fontWeight: "600" },
  trashBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: `${T.red}66`,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: `${T.red}22`,
  },

  primaryGhostBtn: {
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: 12,
    paddingVertical: 11,
    alignItems: "center",
    marginBottom: 8,
  },
  primaryGhostText: { color: T.text, fontSize: 16, fontWeight: "800" },

  signOutBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "rgba(226,92,92,0.1)",
    borderRadius: 14,
    paddingVertical: 14,
    marginTop: 8,
    borderWidth: 1,
    borderColor: "rgba(226,92,92,0.2)",
  },
  signOutText: { color: T.red, fontSize: 15, fontWeight: "700" },
  notificationList: {
    gap: 8,
    marginTop: 0,
    marginBottom: 8,
  },
  notificationHeading: {
    marginBottom: 6,
  },
  notificationItem: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.cardAlt,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 4,
  },
  notificationItemPressed: {
    opacity: 0.9,
  },
  notificationItemUnread: {
    borderColor: `${T.accent}80`,
  },
  notificationTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  notificationTitle: {
    color: T.text,
    fontSize: 13,
    fontWeight: "700",
    flex: 1,
  },
  notificationUnreadDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: T.red,
  },
  notificationBody: {
    color: T.textDim,
    fontSize: 12,
    lineHeight: 16,
  },
  notificationMeta: {
    color: T.textMuted,
    fontSize: 11,
    fontWeight: "600",
  },
  notificationFooterRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  notificationActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  notificationActionBtn: {
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.card,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  notificationActionText: {
    color: T.textDim,
    fontSize: 12,
    fontWeight: "800",
  },
  notificationDeleteBtn: {
    width: 28,
    height: 28,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: `${T.red}66`,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: `${T.red}14`,
  },
  notificationEmpty: {
    color: T.textMuted,
    fontSize: 12,
  },

  bottomTabsGlass: {
    overflow: "hidden",
    borderTopWidth: 1,
    borderTopColor: `${T.accent}29`,
    backgroundColor: `${T.card}A8`,
  },
  bottomTabsTint: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: `${T.accent}12`,
  },
  bottomTabs: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  bottomTabBtn: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 2,
  },
  bottomIconWrap: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  bottomIconWrapActive: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: `${T.accent}30`,
    borderWidth: 1,
    borderColor: `${T.accent}73`,
  },
  bottomTabTxt: { color: T.textDim, fontSize: 11, fontWeight: "700", marginTop: 2 },

  moreBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "flex-end",
    padding: 12,
  },
  moreMenu: {
    borderRadius: 14,
    backgroundColor: T.card,
    borderWidth: 1,
    borderColor: T.border,
    overflow: "hidden",
  },
  moreMenuItem: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: T.border,
  },
  moreMenuItemActive: { backgroundColor: T.accentFaint },
  moreMenuTxt: { color: T.text, fontSize: 14, fontWeight: "700" },
  moreMenuTxtActive: { color: T.accent },

  sheetOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  sheetKeyboardWrap: {
    flex: 1,
    justifyContent: "flex-end",
  },
  sheet: {
    backgroundColor: T.card,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderTopWidth: 1,
    borderTopColor: T.border,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 20,
    gap: 8,
  },
  sheetTall: {
    height: "88%",
    maxHeight: "90%",
  },
  sheetBody: {
    flex: 1,
    minHeight: 0,
  },
  sheetScroll: {
    flex: 1,
  },
  sheetScrollContent: {
    gap: 8,
    paddingBottom: 10,
  },
  sheetHandle: {
    alignSelf: "center",
    width: 46,
    height: 5,
    borderRadius: 999,
    backgroundColor: T.border,
    marginBottom: 4,
  },
  moneyEditorHero: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: `${T.accent}66`,
    backgroundColor: T.accentFaint,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 4,
    alignItems: "center",
    gap: 4,
  },
  moneyEditorHeader: {
    borderRadius: 18,
    backgroundColor: BRAND_BLUE,
    borderWidth: 1,
    borderColor: `${T.onAccent}22`,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 16,
    marginBottom: 10,
    alignItems: "center",
    gap: 6,
  },
  moneyEditorSheet: {
    backgroundColor: BRAND_BLUE,
    borderTopColor: "rgba(255,255,255,0.14)",
  },
  moneyEditorIconCircle: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: `${T.onAccent}22`,
    borderWidth: 1,
    borderColor: `${T.onAccent}33`,
  },
  moneyEditorHeroTitle: {
    color: T.onAccent,
    fontSize: 15,
    fontWeight: "800",
  },
  moneyEditorHeroValue: {
    color: T.onAccent,
    fontSize: 46,
    fontWeight: "900",
    letterSpacing: -0.6,
    lineHeight: 52,
  },
  moneyEditorHeroSub: {
    color: `${T.onAccent}CC`,
    fontSize: 12,
    fontWeight: "600",
  },
  moneyEditorStatsRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 8,
  },
  moneyEditorStatCard: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.22)",
    backgroundColor: "rgba(88,64,190,0.58)",
    paddingVertical: 10,
    paddingHorizontal: 12,
    alignItems: "center",
    gap: 2,
  },
  moneyEditorStatLabel: {
    color: "rgba(255,255,255,0.75)",
    fontSize: 12,
    fontWeight: "700",
  },
  moneyEditorStatValue: {
    color: T.onAccent,
    fontSize: 22,
    fontWeight: "900",
  },
  moneyDeleteBtn: {
    flex: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.85)",
    backgroundColor: "#ffffff",
    paddingVertical: 12,
    alignItems: "center",
  },
  moneyDeleteBtnText: {
    color: BRAND_BLUE,
    fontSize: 16,
    fontWeight: "800",
  },
  moneyEditorDockedActions: {
    backgroundColor: BRAND_BLUE,
    borderTopColor: "rgba(255,255,255,0.2)",
  },
  sheetTitle: { color: T.text, fontSize: 18, fontWeight: "900", marginBottom: 6 },
  label: { color: T.textDim, fontSize: 12, fontWeight: "800" },
  input: {
    backgroundColor: T.cardAlt,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: T.border,
    color: T.text,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  inputDisabled: {
    backgroundColor: T.cardAlt,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: T.border,
    color: T.textDim,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  dateInput: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  dateValue: { color: T.text, fontWeight: "700" },
  dateValuePlaceholder: { color: T.textDim, fontWeight: "700" },

  dateModalOverlay: { flex: 1, justifyContent: "flex-end" },
  dateModalBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(0,0,0,0.55)" },
  dateModalSheet: {
    backgroundColor: T.card,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderTopWidth: 1,
    borderTopColor: T.border,
    paddingBottom: 18,
  },
  dateModalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: T.border,
  },
  dateModalCancelTxt: { color: T.textDim, fontSize: 16, fontWeight: "700" },
  dateModalDoneTxt: { color: T.accent, fontSize: 16, fontWeight: "800" },
  choiceRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 4 },
  choiceBtn: {
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: 10,
    backgroundColor: T.cardAlt,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  choiceBtnActive: {
    borderColor: T.accent,
    backgroundColor: T.accentFaint,
  },
  choiceTxt: { color: T.textDim, fontSize: 12, fontWeight: "700" },
  choiceTxtActive: { color: T.accent },
  sheetActions: { flexDirection: "row", gap: 10, marginTop: 8 },
  sheetActionsDocked: {
    flexDirection: "row",
    gap: 10,
    marginTop: 8,
    paddingTop: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: T.border,
    backgroundColor: T.card,
  },
  outlineBtnWide: {
    flex: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.cardAlt,
    paddingVertical: 12,
    alignItems: "center",
  },
  primaryBtnWide: {
    flex: 1,
    borderRadius: 10,
    backgroundColor: T.accent,
    paddingVertical: 12,
    alignItems: "center",
  },
  tipCard: {
    borderRadius: 14,
    backgroundColor: T.card,
    borderWidth: 1,
    borderColor: T.border,
    padding: 14,
  },

  errorText: { color: T.red, fontSize: 14, textAlign: "center" },
  noPlanTitle: { color: T.text, fontSize: 20, fontWeight: "900", textAlign: "center" },
  noPlanText: { color: T.textDim, fontSize: 14, textAlign: "center" },
  disabled: { opacity: 0.6 },
});
