import { StyleSheet } from "react-native";
import { T } from "@/lib/theme";
import { cardBase } from "@/lib/ui";

export const styles = StyleSheet.create({
  row: { flexDirection: "row", gap: 12, paddingHorizontal: 14, marginTop: 12 },
  card: {
    flex: 1,
    ...cardBase,
    minHeight: 112,
    paddingHorizontal: 14,
    paddingVertical: 14,
    overflow: "hidden",
    backgroundColor: "rgba(20,24,38,0.56)",
    borderColor: "rgba(244,246,255,0.16)",
    shadowColor: "#000000",
    shadowOpacity: 0.24,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 12 },
    elevation: 10,
  },
  cardPressed: { opacity: 0.88 },
  cardGlow: {
    position: "absolute",
    width: 120,
    height: 120,
    borderRadius: 999,
    top: -36,
    right: -28,
  },
  cardInnerBorder: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.03)",
  },
  cardHeaderStack: { alignItems: "flex-start", marginBottom: 10, gap: 8 },
  cardTitleWrap: { flexDirection: "row", alignItems: "center", gap: 8, minWidth: 0, width: "100%" },
  iconPill: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  cardLabel: { color: T.textDim, fontSize: 11, fontWeight: "800", letterSpacing: 0.6, textTransform: "uppercase", flex: 1, flexShrink: 1 },
  valueInline: { flexDirection: "row", alignItems: "flex-end", gap: 8, flexWrap: "wrap" },
  cardValue: { color: T.text, fontSize: 19, fontWeight: "900", letterSpacing: -0.3 },
  cardPctInline: { color: T.textDim, fontSize: 11, fontWeight: "800", marginBottom: 2 },
  cardSubline: { fontSize: 12, fontWeight: "800", marginTop: 8 },
  positive: { color: T.green },
  negative: { color: T.red },
  badge: { borderRadius: 999, paddingHorizontal: 9, paddingVertical: 4, alignSelf: "flex-start" },
  badgeOn: { backgroundColor: "rgba(46,229,143,0.12)", borderWidth: 1, borderColor: "rgba(46,229,143,0.28)" },
  badgeOver: { backgroundColor: "rgba(255,92,122,0.12)", borderWidth: 1, borderColor: "rgba(255,92,122,0.25)" },
  badgeText: { fontSize: 10, fontWeight: "800", textTransform: "uppercase" },
  badgeTextOn: { color: T.green },
  badgeTextOver: { color: T.red },
});
