import { StyleSheet } from "react-native";

import { EXPENSES_TOTAL_BLUE } from "@/lib/constants";

export const onboardingStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: EXPENSES_TOTAL_BLUE },
  gestureWrap: { flex: 1 },
  wrap: { flexGrow: 1, paddingHorizontal: 20, paddingVertical: 24, justifyContent: "center" },
  floatingBackBtn: {
    position: "absolute",
    left: 20,
    zIndex: 10,
    elevation: 10,
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "rgba(255,255,255,0.14)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.25)",
    alignItems: "center",
    justifyContent: "center",
  },
  floatingLogoutBtn: {
    position: "absolute",
    right: 20,
    zIndex: 10,
    elevation: 10,
    paddingHorizontal: 4,
    paddingVertical: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  floatingLogoutText: { color: "#ffffff", fontSize: 12, fontWeight: "900" },
  header: { minHeight: 220, alignItems: "center", justifyContent: "center", paddingVertical: 10 },
  welcome: {
    color: "#ffffff",
    fontSize: 46,
    fontWeight: "800",
    letterSpacing: 0.2,
    textAlign: "center",
    lineHeight: 52,
  },
  welcomeScript: {
    fontFamily: "Sacramento_400Regular",
    fontWeight: "400",
    lineHeight: 64,
    paddingTop: 8,
  },
  welcomeName: {
    color: "#ffffff",
    marginTop: 2,
    fontSize: 32,
    fontWeight: "900",
    letterSpacing: -0.3,
    textAlign: "center",
  },
  sub: { color: "rgba(255,255,255,0.78)", marginTop: 10, fontSize: 13, fontWeight: "800", textAlign: "center", maxWidth: 360 },
  form: { gap: 10 },
  questionRow: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 6 },
  question: { color: "#ffffff", fontSize: 16, fontWeight: "900", flexShrink: 1 },
  option: {
    paddingHorizontal: 10,
    paddingVertical: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.35)",
    borderRadius: 10,
    backgroundColor: "transparent",
  },
  optionRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 },
  optionLeft: { flexDirection: "row", alignItems: "center", gap: 10, flex: 1 },
  optionActive: { borderColor: "rgba(255,255,255,0.8)" },
  optionText: { color: "#ffffff", fontSize: 14, fontWeight: "800" },
  optionTextActive: { color: "#ffffff" },
  helper: { color: "rgba(255,255,255,0.72)", fontSize: 12, fontWeight: "700", marginTop: 2 },
  chipsWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  chip: {
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.30)",
    backgroundColor: "rgba(255,255,255,0.12)",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    position: "relative",
    overflow: "hidden",
  },
  chipActive: { borderColor: "#ffffff", backgroundColor: "#ffffff" },
  chipText: { color: "#ffffff", fontSize: 12, fontWeight: "800" },
  chipTextActive: { color: EXPENSES_TOTAL_BLUE },
  input: {
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.30)",
    backgroundColor: "rgba(255,255,255,0.12)",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: "#ffffff",
  },
  row: { flexDirection: "row", gap: 10 },
  rowInput: { flex: 1 },
  toggleRow: { flexDirection: "row", gap: 10 },
  toggle: {
    flex: 1,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.30)",
    backgroundColor: "rgba(255,255,255,0.12)",
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: "center",
  },
  toggleActive: {
    borderColor: "rgba(255,255,255,0.78)",
    backgroundColor: "rgba(255,255,255,0.18)",
  },
  toggleText: { color: "#ffffff", fontWeight: "800" },
  toggleTextActive: { color: "#ffffff" },
  footerRow: { marginTop: 16, flexDirection: "row", justifyContent: "center", alignItems: "center" },
  primaryBtn: {
    width: "100%",
    height: 52,
    borderRadius: 999,
    paddingHorizontal: 26,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
  },
  primaryBtnText: {
    color: EXPENSES_TOTAL_BLUE,
    fontSize: 16,
    fontWeight: "900",
    letterSpacing: 0.2,
  },
  primaryBtnCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
  },
  disabled: { opacity: 0.55 },
});