import { StyleSheet } from "react-native";

import { EXPENSES_TOTAL_BLUE } from "@/lib/constants";

export const onboardingStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: EXPENSES_TOTAL_BLUE },
  bgGlow: {
    position: "absolute",
    borderRadius: 999,
    zIndex: 0,
  },
  bgGlowTop: {
    width: 360,
    height: 360,
    right: -110,
    top: -70,
    backgroundColor: "rgba(145, 178, 255, 0.18)",
  },
  bgGlowBottom: {
    width: 290,
    height: 290,
    left: -130,
    bottom: 70,
    backgroundColor: "rgba(76, 120, 255, 0.16)",
  },
  gestureWrap: { flex: 1 },
  wrap: { flexGrow: 1, paddingHorizontal: 20, paddingVertical: 24, justifyContent: "center" },
  wrapWithProgress: {
    justifyContent: "flex-start",
    paddingTop: 96,
  },
  topBar: {
    position: "absolute",
    left: 20,
    right: 20,
    zIndex: 12,
    elevation: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  topBarSide: {
    width: 68,
    minHeight: 40,
    justifyContent: "center",
  },
  topBarSideRight: {
    alignItems: "flex-end",
  },
  topBarCenter: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  floatingBackBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.16)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.34)",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#7ba6ff",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.24,
    shadowRadius: 14,
    elevation: 5,
  },
  floatingLogoutBtn: {
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.3)",
    backgroundColor: "rgba(255,255,255,0.1)",
    alignItems: "center",
    justifyContent: "center",
  },
  progressWrap: {
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    maxWidth: 180,
  },
  progressTrack: {
    width: "100%",
    height: 7,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.2)",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: "#ffffff",
  },
  floatingLogoutText: { color: "#ffffff", fontSize: 12, fontWeight: "900", letterSpacing: 0.2 },
  header: { minHeight: 220, alignItems: "center", justifyContent: "center", paddingVertical: 10 },
  welcome: {
    color: "#ffffff",
    fontSize: 46,
    fontWeight: "800",
    letterSpacing: 0.2,
    textAlign: "center",
    lineHeight: 52,
  },
  welcomeScript: {
    fontFamily: "Sacramento_400Regular",
    fontWeight: "400",
    lineHeight: 64,
    paddingTop: 8,
  },
  welcomeName: {
    color: "#ffffff",
    marginTop: 2,
    fontSize: 32,
    fontWeight: "900",
    letterSpacing: -0.3,
    textAlign: "center",
  },
  sub: { color: "rgba(255,255,255,0.82)", marginTop: 10, fontSize: 13, fontWeight: "800", textAlign: "center", maxWidth: 360, letterSpacing: 0.1 },
  form: { gap: 10, paddingTop: 14, paddingBottom: 16 },
  sectionCard: {
    borderWidth: 1,
    borderColor: "rgba(197,218,255,0.30)",
    borderRadius: 14,
    backgroundColor: "rgba(9, 16, 70, 0.3)",
    padding: 10,
    gap: 8,
  },
  questionRow: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 8 },
  question: { color: "#ffffff", fontSize: 17, fontWeight: "900", flexShrink: 1, letterSpacing: 0.1 },
  questionSubtitle: {
    color: "rgba(223,233,255,0.82)",
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 18,
    marginTop: -2,
    marginBottom: 8,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 8,
    marginBottom: 6,
  },
  sectionHeader: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: 0.3,
    textTransform: "uppercase",
  },
  sectionDivider: {
    height: 1,
    backgroundColor: "rgba(199,220,255,0.24)",
    marginVertical: 12,
  },
  sectionHelper: {
    marginTop: 0,
    marginBottom: 8,
  },
  fieldLabel: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "800",
    marginBottom: 6,
  },
  option: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "rgba(197,218,255,0.45)",
    borderRadius: 16,
    backgroundColor: "rgba(7, 16, 72, 0.45)",
  },
  optionRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 },
  optionLeft: { flexDirection: "row", alignItems: "center", gap: 10, flex: 1 },
  optionActive: {
    borderColor: "rgba(255,255,255,0.92)",
    backgroundColor: "rgba(154, 197, 255, 0.2)",
    shadowColor: "#9fc1ff",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.28,
    shadowRadius: 18,
    elevation: 7,
  },
  optionText: { color: "#ffffff", fontSize: 14, fontWeight: "800", letterSpacing: 0.1 },
  optionTextActive: { color: "#ffffff" },
  helper: { color: "rgba(223,233,255,0.82)", fontSize: 12, fontWeight: "700", marginTop: 2 },
  helperRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  chipsWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  dropdownTrigger: {
    minHeight: 48,
    borderWidth: 1,
    borderColor: "rgba(202,224,255,0.42)",
    backgroundColor: "rgba(255,255,255,0.12)",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  dropdownTriggerOpen: {
    borderColor: "rgba(255,255,255,0.92)",
    backgroundColor: "rgba(154, 197, 255, 0.2)",
  },
  dropdownTriggerText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "800",
    flex: 1,
  },
  dropdownTriggerPlaceholder: {
    color: "rgba(223,233,255,0.76)",
  },
  dropdownList: {
    marginTop: 8,
    maxHeight: 236,
    borderWidth: 1,
    borderColor: "rgba(202,224,255,0.42)",
    borderRadius: 12,
    backgroundColor: "rgba(10, 17, 72, 0.72)",
    overflow: "hidden",
  },
  dropdownListScroll: {
    maxHeight: 236,
  },
  dropdownListContent: {
    paddingVertical: 4,
  },
  dropdownItem: {
    minHeight: 44,
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  dropdownItemActive: {
    backgroundColor: "rgba(154, 197, 255, 0.22)",
  },
  dropdownItemText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "700",
    flex: 1,
  },
  dropdownItemTextActive: {
    fontWeight: "900",
  },
  chip: {
    borderWidth: 1,
    borderColor: "rgba(202,224,255,0.38)",
    backgroundColor: "rgba(255,255,255,0.11)",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
    position: "relative",
    overflow: "hidden",
  },
  chipActive: { borderColor: "#ffffff", backgroundColor: "#ffffff" },
  chipText: { color: "#ffffff", fontSize: 12, fontWeight: "800" },
  chipTextActive: { color: EXPENSES_TOTAL_BLUE },
  input: {
    borderWidth: 1,
    borderColor: "rgba(199,220,255,0.4)",
    backgroundColor: "rgba(255,255,255,0.14)",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: "#ffffff",
  },
  billList: { gap: 10 },
  billCard: {
    borderWidth: 1,
    borderColor: "rgba(211,227,255,0.34)",
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 10,
    paddingVertical: 10,
    gap: 8,
  },
  billCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  billIndexBadge: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.56)",
    backgroundColor: "rgba(6, 14, 66, 0.5)",
    alignItems: "center",
    justifyContent: "center",
  },
  billIndexText: {
    color: "#ffffff",
    fontSize: 11,
    fontWeight: "900",
  },
  billMeta: {
    flex: 1,
  },
  billCardTitle: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: 0.2,
  },
  billCardHint: {
    color: "rgba(223,233,255,0.7)",
    fontSize: 11,
    fontWeight: "700",
    marginTop: 1,
  },
  billInputRow: {
    flexDirection: "row",
    gap: 12,
  },
  billNameInput: {
    flex: 1,
    minHeight: 42,
    backgroundColor: "rgba(255,255,255,0.14)",
  },
  billAmountInput: {
    flex: 1,
    minWidth: 138,
  },
  stepNoteBadge: {
    marginTop: 6,
    backgroundColor: "rgba(255,255,255,0.1)",
    borderWidth: 1,
    borderColor: "rgba(216,231,255,0.28)",
  },
  stepNoteAccent: {
    width: 8,
    backgroundColor: "#f3c674",
  },
  stepNoteText: {
    color: "rgba(245,248,255,0.95)",
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 19,
  },
  row: { flexDirection: "row", gap: 10 },
  rowInput: { flex: 1 },
  toggleRow: { flexDirection: "row", gap: 10 },
  toggle: {
    flex: 1,
    borderWidth: 1,
    borderColor: "rgba(199,220,255,0.38)",
    backgroundColor: "rgba(255,255,255,0.12)",
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: "center",
  },
  toggleActive: {
    borderColor: "rgba(255,255,255,0.92)",
    backgroundColor: "rgba(154, 197, 255, 0.24)",
  },
  toggleText: { color: "#ffffff", fontWeight: "800" },
  toggleTextActive: { color: "#ffffff" },
  footerRow: { marginTop: 16, flexDirection: "row", justifyContent: "center", alignItems: "center" },
  primaryBtn: {
    width: "100%",
    height: 52,
    borderRadius: 999,
    paddingHorizontal: 26,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
    shadowColor: "#b5ceff",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 18,
    elevation: 7,
  },
  primaryBtnText: {
    color: EXPENSES_TOTAL_BLUE,
    fontSize: 16,
    fontWeight: "900",
    letterSpacing: 0.2,
  },
  primaryBtnCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
  },
  disabled: { opacity: 0.55 },
});