import { StyleSheet } from "react-native";

import { T } from "@/lib/theme";
import { cardBase } from "@/lib/ui";

export const debtAnalyticsStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: T.bg },
  loadingWrap: { flex: 1, alignItems: "center", justifyContent: "center", gap: 10, paddingHorizontal: 24 },
  loadingText: { color: T.textDim, fontSize: 14, fontWeight: "700" },
  errorText: { color: T.red, textAlign: "center", fontSize: 14, fontWeight: "700" },
  retryBtn: { marginTop: 8, backgroundColor: T.accent, borderRadius: 10, paddingHorizontal: 20, paddingVertical: 10 },
  retryTxt: { color: T.onAccent, fontWeight: "800" },
  scroll: { padding: 14, gap: 12, paddingBottom: 48 },
  summaryRow: { flexDirection: "row", gap: 8 },
  summaryCard: { flex: 1, ...cardBase, padding: 12, alignItems: "center", gap: 4 },
  summaryLbl: { color: T.textMuted, fontSize: 9, fontWeight: "800", letterSpacing: 0.5 },
  summaryVal: { fontSize: 14, fontWeight: "900" },
  card: { ...cardBase, padding: 16, gap: 2 },
  sectionTitle: { color: T.text, fontSize: 14, fontWeight: "900" },
  sectionSub: { color: T.textMuted, fontSize: 11, fontWeight: "600" },
  chipRow: { flexDirection: "row", gap: 10 },
  chip: {
    flex: 1,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    padding: 12,
    borderRadius: 14,
    backgroundColor: T.cardAlt,
    borderWidth: 1,
  },
  chipLbl: { color: T.textMuted, fontSize: 9, fontWeight: "800", letterSpacing: 0.5, marginBottom: 2 },
  chipVal: { color: T.text, fontSize: 13, fontWeight: "900" },
  chipSub: { fontSize: 11, fontWeight: "700", marginTop: 1 },
  debtRow: { flexDirection: "row", gap: 10, paddingVertical: 12 },
  debtRowBorder: { borderTopWidth: 1, borderTopColor: T.border },
  debtColorBar: { width: 3, borderRadius: 2, alignSelf: "stretch" },
  debtRowTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  debtName: { color: T.text, fontSize: 13, fontWeight: "800", flex: 1 },
  debtBalance: { fontSize: 14, fontWeight: "900" },
  debtRowMeta: { flexDirection: "row", gap: 12 },
  debtMeta: { color: T.textDim, fontSize: 11, fontWeight: "600" },
  progressBg: { height: 7, backgroundColor: T.border, borderRadius: 4, overflow: "hidden" },
  progressFill: { height: "100%", borderRadius: 3 },
  legendGrid: { width: "100%", flexDirection: "row", flexWrap: "wrap", gap: 10, paddingHorizontal: 8, marginTop: 4 },
  legendItem: { flexDirection: "row", alignItems: "center", gap: 8, width: "46%" },
  legendItemPressed: { opacity: 0.9 },
  legendItemDimmed: { opacity: 0.5 },
  legendDot: { width: 10, height: 10, borderRadius: 5 },
  legendName: { color: T.text, fontSize: 12, fontWeight: "800" },
  legendSub: { color: T.textMuted, fontSize: 10, fontWeight: "600" },
});
