import { StyleSheet } from "react-native";

import { T } from "@/lib/theme";
import { cardBase } from "@/lib/ui";

export const debtAnalyticsStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: T.bg },
  loadingWrap: { flex: 1, alignItems: "center", justifyContent: "center", gap: 10, paddingHorizontal: 24 },
  loadingText: { color: T.textDim, fontSize: 14, fontWeight: "700" },
  errorText: { color: T.red, textAlign: "center", fontSize: 14, fontWeight: "700" },
  retryBtn: { marginTop: 8, backgroundColor: T.accent, borderRadius: 10, paddingHorizontal: 20, paddingVertical: 10 },
  retryTxt: { color: T.onAccent, fontWeight: "800" },
  scroll: { padding: 14, gap: 12, paddingBottom: 48 },
  heroSection: { alignItems: "center", paddingTop: 4, paddingBottom: 2 },
  heroTitle: { color: T.text, fontSize: 16, fontWeight: "900", textAlign: "center" },
  heroSub: { color: T.textMuted, fontSize: 12, fontWeight: "700", textAlign: "center", marginTop: 6 },
  summaryRow: { flexDirection: "row", gap: 12, marginTop: 12 },
  summaryCard: { flex: 1, ...cardBase, padding: 12, alignItems: "center", gap: 4 },
  summaryLbl: { color: T.textMuted, fontSize: 9, fontWeight: "800", letterSpacing: 0.5 },
  summaryVal: { fontSize: 14, fontWeight: "900" },
  card: { ...cardBase, padding: 16, gap: 2 },
  sectionTitle: { color: T.text, fontSize: 14, fontWeight: "900" },
  sectionSub: { color: T.textMuted, fontSize: 11, fontWeight: "600" },
  donutShell: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 22,
    paddingVertical: 8,
  },
  donutHalo: {
    position: "absolute",
    width: 272,
    height: 272,
    borderRadius: 136,
    backgroundColor: "rgba(255,255,255,0.03)",
  },
  donutWrap: {
    width: 228,
    height: 228,
    alignItems: "center",
    justifyContent: "center",
  },
  donutCenterLabel: {
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
    gap: 6,
  },
  donutCenterTitle: {
    color: T.textDim,
    fontSize: 14,
    fontWeight: "800",
    textAlign: "center",
  },
  donutCenterValue: {
    color: T.text,
    fontSize: 22,
    fontWeight: "900",
    textAlign: "center",
  },
  donutCenterSub: {
    color: T.textDim,
    fontSize: 12,
    fontWeight: "700",
    textAlign: "center",
    lineHeight: 18,
  },
  chipRow: { flexDirection: "row", gap: 10 },
  chip: {
    flex: 1,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    padding: 12,
    borderRadius: 14,
    backgroundColor: T.cardAlt,
    borderWidth: 1,
  },
  chipLbl: { color: T.textMuted, fontSize: 9, fontWeight: "800", letterSpacing: 0.5, marginBottom: 2 },
  chipVal: { color: T.text, fontSize: 13, fontWeight: "900" },
  chipSub: { fontSize: 11, fontWeight: "700", marginTop: 1 },
  debtRow: { flexDirection: "row", gap: 10, paddingVertical: 12 },
  debtRowBorder: { borderTopWidth: 1, borderTopColor: T.border },
  debtColorBar: { width: 3, borderRadius: 2, alignSelf: "stretch" },
  debtRowTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  debtName: { color: T.text, fontSize: 13, fontWeight: "800", flex: 1 },
  debtBalance: { fontSize: 14, fontWeight: "900" },
  debtRowMeta: { flexDirection: "row", gap: 12 },
  debtMeta: { color: T.textDim, fontSize: 11, fontWeight: "600" },
  progressBg: { height: 7, backgroundColor: T.border, borderRadius: 4, overflow: "hidden" },
  progressFill: { height: "100%", borderRadius: 3 },
  legendGrid: {
    width: "100%",
    gap: 10,
    paddingHorizontal: 4,
    marginTop: 22,
  },
  legendItem: {
    width: "100%",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    backgroundColor: "#171b2d",
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 10,
  },
  legendItemPressed: { opacity: 0.9 },
  legendItemDimmed: { opacity: 0.5 },
  legendDot: { width: 10, height: 10, borderRadius: 5 },
  legendTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  legendLabelWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
    minWidth: 0,
  },
  legendName: { color: T.text, fontSize: 14, fontWeight: "800", flexShrink: 1 },
  legendValueWrap: { alignItems: "flex-end", gap: 2 },
  legendPct: { color: T.textMuted, fontSize: 11, fontWeight: "700" },
  legendAmount: { color: T.text, fontSize: 16, fontWeight: "900" },
  legendBarBg: {
    height: 7,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.08)",
    overflow: "hidden",
  },
  legendBarFill: {
    height: 7,
    borderRadius: 999,
  },
});
