import { StyleSheet } from "react-native";

import { T } from "@/lib/theme";

export const styles = StyleSheet.create({
  cardGlow: {
    position: "absolute",
    borderRadius: 999,
  },
  cardGlowPrimary: {
    width: 170,
    height: 170,
    top: -76,
    right: -68,
    backgroundColor: `${T.accent}1C`,
  },
  cardGlowSecondary: {
    width: 120,
    height: 120,
    bottom: -50,
    left: -36,
    backgroundColor: `${T.onAccent}08`,
  },
  footerHint: {
    color: T.textDim,
    fontSize: 13,
    lineHeight: 19,
    marginTop: 8,
    fontWeight: "600",
  },
  mailboxHint: {
    color: T.textMuted,
    fontSize: 13,
    lineHeight: 19,
    marginBottom: 2,
  },
  notificationActionBtn: {
    borderWidth: 1,
    borderColor: `${T.accent}45`,
    backgroundColor: `${T.accent}18`,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  notificationActionText: {
    color: T.text,
    fontSize: 13,
    fontWeight: "800",
  },
  notificationActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  notificationBody: {
    color: T.textDim,
    fontSize: 14,
    lineHeight: 22,
  },
  notificationDeleteBtn: {
    width: 34,
    height: 34,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: `${T.red}7A`,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: `${T.red}1C`,
  },
  notificationEmpty: {
    color: T.textMuted,
    fontSize: 13,
    marginBottom: 8,
  },
  notificationFooterRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    marginTop: 2,
  },
  notificationHeading: {
    marginBottom: 8,
    color: T.textDim,
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  notificationItem: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: `${T.accent}28`,
    backgroundColor: `${T.cardAlt}D8`,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 6,
  },
  notificationItemPressed: {
    opacity: 0.94,
  },
  notificationItemUnread: {
    borderColor: `${T.accent}8F`,
    backgroundColor: `${T.accent}12`,
  },
  notificationList: {
    gap: 10,
    marginTop: 0,
    marginBottom: 2,
  },
  notificationMeta: {
    color: T.textMuted,
    fontSize: 12,
    fontWeight: "600",
  },
  notificationTitle: {
    color: T.text,
    fontSize: 15,
    fontWeight: "900",
    flex: 1,
  },
  notificationTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  notificationUnreadDot: {
    width: 9,
    height: 9,
    borderRadius: 4.5,
    backgroundColor: T.red,
  },
  preferencesCard: {
    borderWidth: 1,
    borderColor: `${T.accent}26`,
    borderRadius: 18,
    backgroundColor: `${T.cardAlt}D5`,
    paddingHorizontal: 12,
    marginBottom: 14,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: T.border,
    gap: 10,
  },
  rowLabel: { color: T.textDim, fontSize: 14, fontWeight: "800" },
  rowLast: {
    borderBottomWidth: 0,
  },
  sheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(6,8,15,0.56)",
  },
  sheetCard: {
    marginHorizontal: 14,
    marginBottom: 18,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: `${T.accent}2E`,
    backgroundColor: `${T.card}FB`,
    maxHeight: "72%",
    overflow: "hidden",
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 12,
  },
  sheetCloseBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: T.border,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: `${T.cardAlt}B2`,
  },
  sheetHandle: {
    alignSelf: "center",
    width: 42,
    height: 4,
    borderRadius: 999,
    backgroundColor: T.border,
    marginBottom: 10,
  },
  sheetHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  sheetList: {
    flexGrow: 0,
  },
  sheetListContent: {
    paddingBottom: 8,
  },
  sheetOverlay: {
    flex: 1,
    justifyContent: "flex-end",
  },
  sheetTitle: {
    color: T.text,
    fontSize: 16,
    fontWeight: "900",
    letterSpacing: -0.2,
  },
});
