import { StyleSheet } from "react-native";

import { T } from "@/lib/theme";
import { cardElevated } from "@/lib/ui";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: T.bg },
  content: { flex: 1, paddingHorizontal: 16, paddingTop: 10 },
  cardGlow: {
    position: "absolute",
    borderRadius: 999,
  },
  card: {
    ...cardElevated,
    padding: 18,
    borderColor: `${T.accent}30`,
    backgroundColor: `${T.card}F7`,
    overflow: "hidden",
  },
  cardGlowPrimary: {
    width: 220,
    height: 220,
    top: -112,
    right: -96,
    backgroundColor: `${T.accent}1E`,
  },
  cardGlowSecondary: {
    width: 140,
    height: 140,
    bottom: -62,
    left: -52,
    backgroundColor: `${T.onAccent}08`,
  },
  label: {
    color: T.textDim,
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    marginBottom: 8,
  },
  input: {
    backgroundColor: `${T.cardAlt}ED`,
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: 18,
    color: T.text,
    fontSize: 15,
    fontWeight: "600",
    paddingHorizontal: 16,
    paddingVertical: 16,
    marginBottom: 18,
  },
  inputDisabled: {
    backgroundColor: `${T.cardAlt}ED`,
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: 18,
    color: T.textMuted,
    fontSize: 15,
    fontWeight: "600",
    paddingHorizontal: 16,
    paddingVertical: 16,
    marginBottom: 18,
  },
  verificationCard: {
    backgroundColor: `${T.cardAlt}F0`,
    borderWidth: 1,
    borderColor: `${T.accent}36`,
    borderRadius: 18,
    padding: 15,
    marginBottom: 18,
    gap: 8,
    overflow: "hidden",
  },
  verificationGlow: {
    width: 150,
    height: 150,
    top: -74,
    right: -68,
    backgroundColor: `${T.accent}18`,
  },
  verificationTitle: {
    color: T.text,
    fontSize: 16,
    fontWeight: "800",
    letterSpacing: -0.2,
  },
  verificationBody: {
    color: T.textDim,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "600",
  },
  verificationBadge: {
    alignSelf: "flex-start",
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 6,
  },
  verificationBadgeText: {
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  verificationButton: {
    marginTop: 10,
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: `${T.accent}20`,
    borderWidth: 1,
    borderColor: `${T.accent}54`,
  },
  verificationButtonText: {
    color: T.accent,
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  footer: {
    flexDirection: "row",
    gap: 14,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 24,
    borderTopWidth: 1,
    borderTopColor: T.border,
    backgroundColor: `${T.bg}E8`,
  },
  cancelBtn: {
    flex: 1,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: T.border,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 16,
    backgroundColor: `${T.card}F0`,
  },
  cancelBtnText: { color: T.textMuted, fontSize: 14, fontWeight: "800" },
  saveBtn: {
    flex: 1,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 16,
    backgroundColor: T.accent,
    shadowColor: T.accent,
    shadowOpacity: 0.26,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 7,
  },
  saveBtnText: { color: T.onAccent, fontSize: 15, fontWeight: "800", letterSpacing: 0.2 },
  disabled: { opacity: 0.6 },
});