import { StyleSheet } from "react-native";

import { T } from "@/lib/theme";
import { cardElevated } from "@/lib/ui";

export const styles = StyleSheet.create({
  cardGlow: {
    position: "absolute",
    borderRadius: 999,
  },
  cardGlowPrimary: {
    width: 104,
    height: 104,
    top: -52,
    right: -48,
    backgroundColor: `${T.accent}1A`,
  },
  cardGlowSecondary: {
    width: 74,
    height: 74,
    bottom: -36,
    left: -28,
    backgroundColor: `${T.onAccent}08`,
  },
  featureGlowPrimary: {
    width: 150,
    height: 150,
    top: -70,
    right: -64,
    backgroundColor: `${T.accent}1F`,
  },
  featureGlowSecondary: {
    width: 110,
    height: 110,
    bottom: -48,
    left: -40,
    backgroundColor: `${T.onAccent}09`,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  sectionBadge: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: `${T.accent}18`,
    borderWidth: 1,
    borderColor: `${T.accent}4A`,
  },
  sectionBadgeText: {
    color: T.accent,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.2,
    textTransform: "uppercase",
  },
  cardMiniActionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  cardMiniIconBtn: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: `${T.accent}18`,
    borderWidth: 1,
    borderColor: `${T.accent}3A`,
  },
  cardRowCenter: { flexDirection: "row", alignItems: "center", gap: 8 },
  halfCard: {
    flex: 1,
    marginBottom: 0,
  },
  infoLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 2,
  },
  infoCard: {
    ...cardElevated,
    borderRadius: 20,
    padding: 16,
    marginBottom: 16,
    borderColor: `${T.accent}26`,
    backgroundColor: `${T.card}F7`,
    overflow: "hidden",
  },
  featureCard: {
    paddingVertical: 18,
  },
  infoCardHint: { color: T.textDim, fontSize: 13, fontWeight: "600", marginTop: 6, lineHeight: 19 },
  infoCardLabel: {
    color: T.textDim,
    fontSize: 12,
    fontWeight: "800",
    marginBottom: 4,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  infoCardValue: {
    color: T.text,
    fontSize: 18,
    fontWeight: "900",
    letterSpacing: -0.3,
  },
  featureRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  featureTextWrap: {
    flex: 1,
  },
  featureIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: `${T.accent}1E`,
    borderWidth: 1,
    borderColor: `${T.accent}44`,
  },
  forwardBadge: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: `${T.onAccent}0F`,
    borderWidth: 1,
    borderColor: T.border,
  },
  plainBudgetBlock: {
    marginBottom: 16,
  },
  plainBudgetTitle: {
    color: T.textDim,
    fontSize: 13,
    fontWeight: "800",
    marginBottom: 10,
    paddingHorizontal: 2,
  },
  twoColRow: {
    flexDirection: "row",
    gap: 14,
    marginBottom: 16,
  },
});
