import { StyleSheet } from "react-native";

import { T } from "@/lib/theme";
import { cardElevated } from "@/lib/ui";

export const styles = StyleSheet.create({
  body: {
    gap: 14,
  },
  cardGlow: {
    position: "absolute",
    borderRadius: 999,
  },
  currentCard: {
    ...cardElevated,
    padding: 18,
    gap: 7,
    borderColor: `${T.accent}30`,
    backgroundColor: `${T.card}F7`,
  },
  currentCardGlowPrimary: {
    width: 180,
    height: 180,
    top: -84,
    right: -76,
    backgroundColor: `${T.accent}24`,
  },
  currentCardGlowSecondary: {
    width: 120,
    height: 120,
    bottom: -50,
    left: -32,
    backgroundColor: `${T.onAccent}08`,
  },
  currentBadge: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: `${T.accent}18`,
    borderWidth: 1,
    borderColor: `${T.accent}50`,
  },
  currentBadgeText: {
    color: T.accent,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  eyebrow: {
    color: T.textMuted,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  currentTitle: {
    color: T.text,
    fontSize: 28,
    fontWeight: "900",
    letterSpacing: -0.5,
  },
  currentText: {
    color: T.textDim,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "600",
  },
  currentHint: {
    color: T.textMuted,
    fontSize: 13,
    lineHeight: 18,
  },
  offerCard: {
    ...cardElevated,
    padding: 18,
    gap: 11,
    borderColor: T.border,
    backgroundColor: `${T.card}F5`,
  },
  offerCardGlowPrimary: {
    width: 160,
    height: 160,
    top: -76,
    right: -74,
    backgroundColor: `${T.onAccent}06`,
  },
  offerCardGlowSecondary: {
    width: 110,
    height: 110,
    bottom: -46,
    left: -40,
    backgroundColor: `${T.accent}10`,
  },
  offerCardGlowHighlight: {
    backgroundColor: `${T.accent}20`,
  },
  offerCardGlowHighlightSecondary: {
    backgroundColor: `${T.accent}14`,
  },
  offerCardHighlight: {
    borderColor: `${T.accent}A6`,
    borderWidth: 1.5,
  },
  offerTitleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  offerTitle: {
    color: T.text,
    fontSize: 19,
    fontWeight: "900",
  },
  badge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: `${T.accent}20`,
    borderWidth: 1,
    borderColor: `${T.accent}45`,
  },
  badgeText: {
    color: T.accent,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  price: {
    color: T.text,
    fontSize: 24,
    fontWeight: "900",
    letterSpacing: -0.4,
  },
  billing: {
    color: T.textDim,
    fontSize: 14,
    fontWeight: "600",
  },
  bulletList: {
    gap: 8,
    marginTop: 2,
  },
  bulletRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  bulletIconWrap: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: `${T.accent}20`,
    borderWidth: 1,
    borderColor: `${T.accent}44`,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 1,
  },
  bullet: {
    color: T.textDim,
    fontSize: 14,
    lineHeight: 19,
    flex: 1,
  },
  disabledBtn: {
    marginTop: 4,
    borderRadius: 14,
    paddingVertical: 13,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: `${T.cardAlt}F0`,
    borderWidth: 1,
    borderColor: T.border,
  },
  disabledBtnHighlight: {
    backgroundColor: `${T.accent}20`,
    borderColor: `${T.accent}66`,
    shadowColor: T.accent,
    shadowOpacity: 0.22,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
  },
  disabledBtnText: {
    color: T.text,
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  errorText: {
    color: T.red,
    fontSize: 14,
    lineHeight: 20,
  },
  retryBtn: {
    alignSelf: "flex-start",
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 9,
    backgroundColor: T.accent,
  },
  retryText: {
    color: T.onAccent,
    fontSize: 13,
    fontWeight: "800",
  },
});