import { StyleSheet } from "react-native";

import { T } from "@/lib/theme";

export const styles = StyleSheet.create({
  bgGlow: {
    position: "absolute",
    borderRadius: 999,
  },
  bgGlowBottom: {
    width: 320,
    height: 320,
    left: -160,
    bottom: 120,
    backgroundColor: `${T.onAccent}07`,
  },
  bgGlowTop: {
    width: 380,
    height: 380,
    right: -165,
    top: -115,
    backgroundColor: `${T.accent}14`,
  },
  cardGlow: {
    position: "absolute",
    borderRadius: 999,
  },
  cardGlowPrimary: {
    width: 180,
    height: 180,
    top: -82,
    right: -74,
    backgroundColor: `${T.accent}1C`,
  },
  cardGlowSecondary: {
    width: 120,
    height: 120,
    bottom: -48,
    left: -40,
    backgroundColor: `${T.onAccent}09`,
  },
  safe: { flex: 1, backgroundColor: T.bg },
  kav: { flex: 1 },
  scroll: { flexGrow: 1, justifyContent: "center", paddingHorizontal: 24, paddingVertical: 40 },
  logoArea: { alignItems: "center", marginBottom: 32 },
  appName: { color: T.text, fontSize: 50, fontWeight: "900", letterSpacing: -1.1 },
  tagline: { color: T.textDim, fontSize: 14, marginTop: 6, fontWeight: "600", letterSpacing: 0.4 },
  card: {
    backgroundColor: `${T.card}F6`,
    borderRadius: 32,
    padding: 24,
    borderWidth: 1,
    borderColor: `${T.accent}36`,
    overflow: "hidden",
    shadowColor: T.accent,
    shadowOpacity: 0.14,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  modeRow: {
    flexDirection: "row",
    marginBottom: 22,
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: `${T.cardAlt}CC`,
    borderWidth: 1,
    borderColor: `${T.accent}22`,
    padding: 5,
    gap: 4,
  },
  modeBtn: {
    flex: 1,
    paddingVertical: 12,
    alignItems: "center",
    borderRadius: 12,
  },
  modeBtnActive: {
    backgroundColor: T.accent,
    shadowColor: T.accent,
    shadowOpacity: 0.22,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  modeBtnText: { color: T.textDim, fontWeight: "800", fontSize: 14 },
  modeBtnTextActive: { color: T.onAccent },
  input: {
    backgroundColor: `${T.cardAlt}D8`,
    color: T.text,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: `${T.accent}28`,
    paddingHorizontal: 16,
    paddingVertical: 16,
    fontSize: 16,
    marginBottom: 16,
  },
  submitBtn: {
    backgroundColor: T.accent,
    borderRadius: 18,
    paddingVertical: 18,
    alignItems: "center",
    shadowColor: T.accent,
    shadowOpacity: 0.26,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 5,
  },
  submitBtnDisabled: { opacity: 0.6 },
  submitBtnText: { color: T.onAccent, fontWeight: "800", fontSize: 16, letterSpacing: 0.2 },
});