import { StyleSheet } from "react-native";
import { T } from "@/lib/theme";
import { cardBase, flatInput } from "@/lib/ui";

export const styles = StyleSheet.create({
  card: {
    ...cardBase,
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 14,
    marginVertical: 6,
    paddingVertical: 16,
    paddingHorizontal: 14,
    gap: 12,
    backgroundColor: "#141826",
    borderColor: "rgba(255,255,255,0.07)",
    shadowColor: "#000000",
    shadowOpacity: 0.16,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 7,
  },
  pressed: { opacity: 0.75 },
  left: { flex: 1, minWidth: 0, flexDirection: "row", alignItems: "center", gap: 12 },
  iconWrap: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  copy: { flex: 1, minWidth: 0 },
  name: { color: T.text, fontSize: 17, fontWeight: "800" },
  hint: { color: T.textDim, fontSize: 12, marginTop: 3, fontWeight: "700" },
  right: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },

  editWrap: {
    ...cardBase,
    padding: 12,
    marginVertical: 6,
    marginHorizontal: 14,
    gap: 10,
    borderColor: T.accentFaint,
  },
  editInputs: { flexDirection: "row", gap: 10 },
  editActions: { flexDirection: "row", justifyContent: "flex-end", gap: 10 },
  input: {
    ...flatInput,
  },
  cancelBtn: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: T.cardAlt,
  },
  cancelText: { color: T.textDim, fontWeight: "700", fontSize: 13 },
  saveBtn: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 8, backgroundColor: T.accent },
  saveText: { color: T.onAccent, fontWeight: "700", fontSize: 13 },
  disabled: { opacity: 0.5 },
});
