import { StyleSheet } from "react-native";
import { T } from "@/lib/theme";

export const styles = StyleSheet.create({
  mainScreen: { flex: 1, backgroundColor: T.bg },
  mainList: { flex: 1, backgroundColor: T.bg },
  loadingState: { flex: 1, backgroundColor: T.bg },
  loadingInner: { flex: 1, justifyContent: "center", alignItems: "center" },
  wrap: { gap: 12, paddingHorizontal: 14, paddingTop: 22 },
  buttonSpacer: { height: 4 },
  noticeCard: {
    backgroundColor: `${T.accent}15`,
    borderWidth: 1,
    borderColor: `${T.accent}66`,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  noticeTitle: { color: T.text, fontSize: 12, fontWeight: "900" },
  noticeText: { color: T.textDim, fontSize: 12, fontWeight: "700" },
  noticeCloseBtn: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.cardAlt,
  },
  card: {
    backgroundColor: T.card,
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: 14,
    padding: 12,
    gap: 10,
  },
  cardTitle: { color: T.text, fontSize: 14, fontWeight: "900" },
  cardSub: { color: T.textDim, fontSize: 12, fontWeight: "600" },
  emptyText: { color: T.textDim, fontSize: 12, fontWeight: "600" },
  confirmRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: 10,
    padding: 10,
    backgroundColor: T.cardAlt,
  },
  confirmTarget: { color: T.text, fontSize: 13, fontWeight: "800" },
  confirmMeta: { color: T.textDim, fontSize: 11, fontWeight: "700" },
  confirmStatus: { color: T.orange, fontSize: 11, fontWeight: "800" },
  confirmStatusOk: { color: T.green },
  confirmBtn: {
    backgroundColor: T.accent,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  confirmBtnText: { color: T.onAccent, fontSize: 12, fontWeight: "800" },
  linkedTotalsText: { color: T.textDim, fontSize: 12, fontWeight: "700" },
  actionRow: { gap: 8 },
  footerButtonStack: { gap: 8 },
  manageFooterRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  manageFooterLeftGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  inlineInfoCard: {
    backgroundColor: T.card,
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  inlineInfoText: { color: T.textDim, fontSize: 13, fontWeight: "700", lineHeight: 19 },
  primaryBtn: {
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "rgba(15,40,47,0.10)",
    borderRadius: 10,
    paddingVertical: 11,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 6,
  },
  primaryBtnText: { color: "#0f282f", fontSize: 13, fontWeight: "800" },
  secondaryBtn: {
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "rgba(15,40,47,0.10)",
    borderRadius: 10,
    paddingVertical: 11,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 6,
  },
  secondaryBtnText: { color: "#0f282f", fontSize: 13, fontWeight: "800" },
  disabled: { opacity: 0.55 },
  aiTipCard: {
    backgroundColor: T.card,
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 13,
    gap: 8,
  },
  aiTipHeader: { flexDirection: "row", alignItems: "center", gap: 8 },
  aiTipTitle: { color: T.text, fontSize: 13, fontWeight: "900" },
  aiTipHeadline: { color: T.text, fontSize: 15, fontWeight: "900" },
  aiTipText: { color: T.textDim, fontSize: 13, fontWeight: "600", lineHeight: 19 },
  aiTipDots: { flexDirection: "row", gap: 6, marginTop: 2 },
  aiTipDot: { width: 6, height: 6, borderRadius: 999, backgroundColor: "rgba(255,255,255,0.18)" },
  aiTipDotActive: { backgroundColor: T.accent },
  manageScreen: { flex: 1, backgroundColor: T.bg },
  manageScreenDetail: { backgroundColor: T.bg },
  manageHeaderShell: {
    backgroundColor: `${T.card}66`,
    borderBottomWidth: 1,
    borderBottomColor: `${T.accent}29`,
    borderBottomLeftRadius: 26,
    borderBottomRightRadius: 26,
    overflow: "hidden",
  },
  manageHeaderShellDetail: {
    backgroundColor: "#080080",
    borderBottomColor: "rgba(255,255,255,0.12)",
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  manageHeaderTint: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: `${T.accent}12`,
  },
  manageHeaderTintDetail: {
    backgroundColor: "rgba(255,255,255,0.04)",
  },
  manageHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    paddingBottom: 12,
    paddingTop: 12,
    position: "relative",
  },
  manageHeaderDetail: {
    paddingBottom: 8,
  },
  manageBackBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: `${T.cardAlt}66`,
  },
  manageBackBtnDetail: {
    borderWidth: 0,
    backgroundColor: "transparent",
  },
  manageHeaderCenterWrap: {
    position: "absolute",
    left: 62,
    right: 62,
    top: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  manageHeaderSpacer: {
    width: 34,
    height: 34,
  },
  manageTitle: { color: T.text, fontSize: 15, fontWeight: "700", textAlign: "center", letterSpacing: 0.1 },
  manageScroll: { flex: 1, backgroundColor: T.bg },
  manageScrollDetail: { backgroundColor: T.bg },
  manageScrollContent: {
    paddingHorizontal: 14,
    paddingTop: 24,
    gap: 12,
  },
  manageScrollContentDetail: {
    paddingTop: 0,
  },
  fixedFooter: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: "stretch",
    paddingHorizontal: 14,
    paddingTop: 12,
    backgroundColor: "transparent",
  },
  mainFooterRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  mainFooterRightGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  mainFooterBtn: {
    minHeight: 46,
    minWidth: 88,
    borderRadius: 999,
    backgroundColor: "#f8f8fb",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.65)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    paddingVertical: 10,
    shadowColor: "#000000",
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: -2 },
    elevation: 8,
  },
  mainFooterBtnAccent: {
    backgroundColor: T.accent,
    borderColor: T.accent,
    shadowColor: T.accent,
    shadowOpacity: 0.3,
    shadowRadius: 20,
  },
  mainFooterBtnText: {
    color: "#162932",
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: -0.2,
  },
  mainFooterBtnTextAccent: {
    color: T.onAccent,
  },
  fieldLabel: { color: T.textDim, fontSize: 12, fontWeight: "700" },
  fieldHelpText: { color: T.textDim, fontSize: 11, fontWeight: "600", marginTop: -4 },
  inlineMetaText: { color: T.textMuted, fontSize: 11, fontWeight: "700" },
  periodInfoBanner: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    borderWidth: 1,
    borderColor: `${T.accent}33`,
    backgroundColor: `${T.accent}12`,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  periodInfoCopy: { flex: 1, gap: 2 },
  periodInfoTitle: { color: T.text, fontSize: 12, fontWeight: "800" },
  periodInfoMeta: { color: T.textDim, fontSize: 11, fontWeight: "600" },
  sectionCard: {
    backgroundColor: T.card,
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: 14,
    padding: 12,
    gap: 10,
  },
  sectionSubHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  input: {
    backgroundColor: T.cardAlt,
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: 9,
    color: T.text,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
  },
  currentAmountText: { color: T.textDim, fontSize: 12, fontWeight: "700" },
  amountSummaryRow: {
    flexDirection: "row",
    gap: 8,
  },
  chooserStack: {
    gap: 12,
  },
  chooserSummary: {
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 10,
    paddingBottom: 12,
    paddingHorizontal: 20,
    gap: 2,
  },
  chooserSummaryEyebrow: {
    color: T.textMuted,
    fontSize: 12,
    fontWeight: "700",
    textAlign: "center",
  },
  chooserSummaryPrimary: {
    color: T.text,
    fontSize: 32,
    fontWeight: "900",
    letterSpacing: -0.8,
    textAlign: "center",
  },
  chooserSummaryMeta: {
    color: T.textDim,
    fontSize: 12,
    fontWeight: "700",
    textAlign: "center",
    marginTop: 4,
  },
  chooserSummarySecondary: {
    color: T.text,
    fontSize: 18,
    fontWeight: "800",
    textAlign: "center",
  },
  amountSummaryCard: {
    flex: 1,
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: 12,
    backgroundColor: T.card,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 4,
  },
  amountSummaryLabel: { color: T.textMuted, fontSize: 11, fontWeight: "700" },
  amountSummaryValue: { color: T.text, fontSize: 15, fontWeight: "900" },
  amountSummaryHint: { color: T.textDim, fontSize: 11, fontWeight: "600", lineHeight: 16 },
  detailHero: {
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 24,
    paddingBottom: 26,
    paddingHorizontal: 20,
    marginHorizontal: -14,
    marginBottom: 8,
    backgroundColor: "#080080",
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    gap: 6,
  },
  detailHeroIcon: {
    width: 58,
    height: 58,
    borderRadius: 29,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    marginBottom: 6,
  },
  detailHeroTitle: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "900",
    textAlign: "center",
    paddingHorizontal: 16,
  },
  detailHeroAmount: {
    color: "#ffffff",
    fontSize: 44,
    fontWeight: "900",
    letterSpacing: -1,
    textAlign: "center",
  },
  detailHeroMeta: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 12,
    fontWeight: "600",
    textAlign: "center",
  },
  detailHeroDueLabel: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 12,
    fontWeight: "700",
    textAlign: "center",
    marginTop: 4,
  },
  detailHeroDueValue: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "800",
    textAlign: "center",
  },
  detailHeroInlineEditWrap: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 2,
  },
  detailHeroInlineCurrency: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "800",
  },
  detailHeroInlineInput: {
    minWidth: 124,
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "800",
    textAlign: "center",
    paddingVertical: 0,
  },
  detailHeroRemoveBtn: {
    marginTop: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  detailHeroRemoveText: {
    color: "rgba(255,255,255,0.82)",
    fontSize: 12,
    fontWeight: "700",
  },
  amountHeroBlock: {
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
    paddingVertical: 4,
    gap: 2,
  },
  amountHeroValue: {
    color: T.text,
    fontSize: 24,
    fontWeight: "900",
    letterSpacing: -0.6,
    textAlign: "center",
  },
  amountHeroMeta: {
    color: T.textMuted,
    fontSize: 11,
    fontWeight: "700",
    textAlign: "center",
    marginBottom: 6,
  },
  amountHeroDueLabel: {
    color: T.textDim,
    fontSize: 11,
    fontWeight: "700",
    textAlign: "center",
    marginTop: 2,
  },
  amountHeroDueValue: {
    color: T.text,
    fontSize: 14,
    fontWeight: "800",
    textAlign: "center",
  },
  targetCardList: { gap: 10 },
  targetSectionDivider: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    marginTop: 4,
  },
  targetCard: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: T.border,
    borderRadius: 12,
    backgroundColor: T.cardAlt,
    padding: 14,
  },
  targetCardIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: T.border,
  },
  targetCardMainRow: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 10 },
  targetCardLead: { flexDirection: "row", alignItems: "flex-start", gap: 8, flex: 1, minWidth: 0 },
  targetCardCopy: { flex: 1, minWidth: 0 },
  targetCardAmountWrap: { alignItems: "flex-end", justifyContent: "center", paddingLeft: 8 },
  targetCardTitle: { color: T.text, fontSize: 14, fontWeight: "800", marginBottom: 4 },
  targetCardAmount: { color: T.text, fontSize: 15, fontWeight: "900" },
  targetCardMeta: { color: T.textDim, fontSize: 12, fontWeight: "700" },
  targetCardMetaRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12, marginTop: 10, marginBottom: 6 },
  targetCardDueText: { color: T.textDim, fontSize: 12, fontWeight: "700", flex: 1 },
  targetCardGoalText: { color: T.textMuted, fontSize: 11, fontWeight: "700", flexShrink: 1, textAlign: "right" },
  targetCardProgressMeta: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10, marginBottom: 6 },
  targetCardProgressLabel: { color: T.textDim, fontSize: 11, fontWeight: "700" },
  targetCardProgressValue: { color: T.text, fontSize: 11, fontWeight: "800" },
  targetCardProgressBg: { height: 7, borderRadius: 4, backgroundColor: T.border, overflow: "hidden" },
  targetCardProgressFill: { height: 7, borderRadius: 4 },
  targetCardChevronWrap: { position: "absolute", right: 12, top: 14, height: 24, justifyContent: "center" },
  optionGrid: {
    flexDirection: "row",
    gap: 8,
  },
  optionCard: {
    flex: 1,
    minHeight: 56,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.card,
    paddingHorizontal: 10,
    paddingVertical: 10,
    justifyContent: "center",
  },
  optionCardActive: {
    borderColor: T.accent,
    backgroundColor: `${T.accent}18`,
  },
  optionCardTitle: {
    color: T.text,
    fontSize: 12,
    fontWeight: "800",
    textAlign: "center",
  },
  optionCardTitleActive: {
    color: T.accent,
  },
  pillWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  pill: {
    backgroundColor: T.cardAlt,
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  pillActive: { backgroundColor: `${T.accent}22`, borderColor: T.accent },
  pillText: { color: T.textDim, fontSize: 12, fontWeight: "700" },
  pillTextActive: { color: T.accent, fontWeight: "800" },
  monthGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  monthChip: {
    width: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.cardAlt,
    paddingVertical: 7,
  },
  monthChipActive: { borderColor: T.accent, backgroundColor: `${T.accent}22` },
  monthChipText: { color: T.textDim, fontSize: 12, fontWeight: "700" },
  monthChipTextActive: { color: T.accent, fontWeight: "800" },
  yearRow: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 10 },
  yearBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.cardAlt,
  },
  yearValue: { color: T.text, fontSize: 16, fontWeight: "900", minWidth: 74, textAlign: "center" },
  removeAmountBtn: {
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.cardAlt,
  },
  removeAmountText: { color: T.textDim, fontSize: 12, fontWeight: "700" },
});
