import { StyleSheet } from "react-native";
import { T } from "@/lib/theme";

export const styles = StyleSheet.create({
  mainScreen: { flex: 1, backgroundColor: T.bg },
  mainList: { flex: 1, backgroundColor: T.bg },
  loadingState: { flex: 1, backgroundColor: T.bg },
  loadingInner: { flex: 1, justifyContent: "center", alignItems: "center" },
  wrap: { gap: 14, paddingHorizontal: 14, paddingTop: 18 },
  buttonSpacer: { height: 8 },
  noticeCard: {
    backgroundColor: `${T.accent}15`,
    borderWidth: 1,
    borderColor: `${T.accent}66`,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  noticeTitle: { color: T.text, fontSize: 12, fontWeight: "900" },
  noticeText: { color: T.textDim, fontSize: 12, fontWeight: "700" },
  noticeCloseBtn: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.cardAlt,
  },
  card: {
    backgroundColor: T.card,
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: 14,
    padding: 12,
    gap: 10,
  },
  cardTitle: { color: T.text, fontSize: 14, fontWeight: "900" },
  cardSub: { color: T.textDim, fontSize: 12, fontWeight: "600" },
  emptyText: { color: T.textDim, fontSize: 12, fontWeight: "600" },
  confirmRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: 10,
    padding: 10,
    backgroundColor: T.cardAlt,
  },
  confirmTarget: { color: T.text, fontSize: 13, fontWeight: "800" },
  confirmMeta: { color: T.textDim, fontSize: 11, fontWeight: "700" },
  confirmStatus: { color: T.orange, fontSize: 11, fontWeight: "800" },
  confirmStatusOk: { color: T.green },
  confirmBtn: {
    backgroundColor: T.accent,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  confirmBtnText: { color: T.onAccent, fontSize: 12, fontWeight: "800" },
  linkedTotalsText: { color: T.textDim, fontSize: 12, fontWeight: "700" },
  actionRow: { gap: 8 },
  footerButtonStack: { gap: 8 },
  manageFooterRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  manageFooterLeftGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  inlineInfoCard: {
    backgroundColor: T.card,
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  inlineInfoText: { color: T.textDim, fontSize: 13, fontWeight: "700", lineHeight: 19 },
  primaryBtn: {
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "rgba(15,40,47,0.10)",
    borderRadius: 10,
    paddingVertical: 11,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 6,
  },
  primaryBtnText: { color: "#0f282f", fontSize: 13, fontWeight: "800" },
  secondaryBtn: {
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "rgba(15,40,47,0.10)",
    borderRadius: 10,
    paddingVertical: 11,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 6,
  },
  secondaryBtnText: { color: "#0f282f", fontSize: 13, fontWeight: "800" },
  addPillButton: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "rgba(15,40,47,0.10)",
  },
  addPillButtonText: { color: "#0f282f", fontSize: 13, fontWeight: "800" },
  disabled: { opacity: 0.55 },
  aiTipCard: {
    backgroundColor: "#171b2d",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 15,
    gap: 10,
    shadowColor: "#000000",
    shadowOpacity: 0.16,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 6,
  },
  aiTipHeader: { flexDirection: "row", alignItems: "center", gap: 8 },
  aiTipTitle: { color: T.accent, fontSize: 12, fontWeight: "900", letterSpacing: 0.2 },
  aiTipHeadline: { color: T.text, fontSize: 16, fontWeight: "900", lineHeight: 22 },
  aiTipText: { color: T.textDim, fontSize: 13, fontWeight: "700", lineHeight: 21 },
  aiTipDots: { flexDirection: "row", gap: 6, marginTop: 2 },
  aiTipDot: { width: 6, height: 6, borderRadius: 999, backgroundColor: "rgba(255,255,255,0.18)" },
  aiTipDotActive: { backgroundColor: T.accent },
  manageScreen: { flex: 1, backgroundColor: T.bg },
  manageScreenDetail: { backgroundColor: T.bg },
  manageHeaderShell: {
    backgroundColor: `${T.card}66`,
    borderBottomWidth: 1,
    borderBottomColor: `${T.accent}29`,
    borderBottomLeftRadius: 26,
    borderBottomRightRadius: 26,
    overflow: "hidden",
  },
  manageHeaderShellDetail: {
    backgroundColor: "#171b2d",
    borderBottomColor: "rgba(255,255,255,0.06)",
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  manageHeaderTint: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: `${T.accent}12`,
  },
  manageHeaderTintDetail: {
    backgroundColor: "rgba(124,92,255,0.10)",
  },
  manageHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    paddingBottom: 12,
    paddingTop: 12,
    position: "relative",
  },
  manageHeaderDetail: {
    paddingBottom: 8,
  },
  manageBackBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: `${T.cardAlt}66`,
  },
  manageBackBtnDetail: {
    borderWidth: 0,
    backgroundColor: "transparent",
  },
  manageHeaderCenterWrap: {
    position: "absolute",
    left: 62,
    right: 62,
    top: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  manageHeaderSpacer: {
    width: 34,
    height: 34,
  },
  manageTitle: { color: T.text, fontSize: 15, fontWeight: "700", textAlign: "center", letterSpacing: 0.1 },
  manageScroll: { flex: 1, backgroundColor: T.bg },
  manageScrollDetail: { backgroundColor: T.bg },
  manageScrollContent: {
    paddingHorizontal: 14,
    paddingTop: 24,
    gap: 12,
  },
  manageScrollContentDetail: {
    paddingTop: 0,
  },
  fixedFooter: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: "stretch",
    paddingHorizontal: 14,
    paddingTop: 12,
    backgroundColor: "transparent",
    overflow: "hidden",
  },
  fixedFooterBackdrop: {
    ...StyleSheet.absoluteFillObject,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "rgba(255,255,255,0.10)",
  },
  fixedFooterBackdropBlur: {
    ...StyleSheet.absoluteFillObject,
  },
  fixedFooterBackdropTint: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(11,15,28,0.34)",
  },
  mainFooterRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  mainFooterLeftGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  mainFooterRightGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  mainFooterBtn: {
    overflow: "hidden",
    minHeight: 46,
    minWidth: 88,
    borderRadius: 999,
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 0,
    paddingVertical: 0,
    shadowColor: "#000000",
    shadowOpacity: 0.16,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: -2 },
    elevation: 8,
  },
  mainFooterBtnIconOnly: {
    minWidth: 46,
    width: 46,
    borderRadius: 23,
  },
  mainFooterBtnAccent: {
    borderColor: "rgba(124,92,255,0.44)",
    shadowColor: T.accent,
    shadowOpacity: 0.28,
    shadowRadius: 20,
  },
  mainFooterBtnPressed: {
    transform: [{ scale: 0.985 }],
  },
  mainFooterBtnBlur: {
    minHeight: 46,
    minWidth: 88,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    paddingVertical: 10,
    overflow: "hidden",
  },
  mainFooterBtnBlurIconOnly: {
    minWidth: 46,
    width: 46,
    paddingHorizontal: 0,
    borderRadius: 23,
  },
  mainFooterBtnBlurAccent: {
    backgroundColor: "rgba(124,92,255,0.16)",
  },
  mainFooterBtnGlass: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 999,
  },
  mainFooterBtnInner: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
    backgroundColor: "rgba(255,255,255,0.14)",
  },
  mainFooterBtnInnerAccent: {
    borderColor: "rgba(255,255,255,0.12)",
    backgroundColor: "rgba(124,92,255,0.24)",
  },
  mainFooterBtnText: {
    color: "#f4f5fb",
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: -0.2,
  },
  mainFooterBtnTextAccent: {
    color: T.text,
  },
  fieldLabel: { color: T.textDim, fontSize: 12, fontWeight: "700" },
  fieldHelpText: { color: T.textDim, fontSize: 11, fontWeight: "600", marginTop: -4 },
  inlineMetaText: { color: T.textMuted, fontSize: 11, fontWeight: "700" },
  periodInfoBanner: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    borderWidth: 1,
    borderColor: `${T.accent}33`,
    backgroundColor: `${T.accent}12`,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  periodInfoCopy: { flex: 1, gap: 2 },
  periodInfoTitle: { color: T.text, fontSize: 12, fontWeight: "800" },
  periodInfoMeta: { color: T.textDim, fontSize: 11, fontWeight: "600" },
  sectionCard: {
    backgroundColor: T.card,
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: 14,
    padding: 12,
    gap: 10,
  },
  sectionSubHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  input: {
    backgroundColor: T.cardAlt,
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: 9,
    color: T.text,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
  },
  currentAmountText: { color: T.textDim, fontSize: 12, fontWeight: "700" },
  amountSummaryRow: {
    flexDirection: "row",
    gap: 8,
  },
  chooserStack: {
    gap: 12,
  },
  chooserHero: {
    position: "relative",
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 18,
    paddingBottom: 18,
    paddingHorizontal: 18,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "rgba(124,92,255,0.18)",
    backgroundColor: "#171b2d",
    shadowColor: "#000000",
    shadowOpacity: 0.28,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
    elevation: 10,
  },
  chooserHeroGlow: {
    position: "absolute",
    borderRadius: 999,
  },
  chooserHeroGlowPrimary: {
    width: 220,
    height: 220,
    top: -96,
    right: -40,
    backgroundColor: "rgba(124,92,255,0.22)",
  },
  chooserHeroGlowSecondary: {
    width: 180,
    height: 180,
    bottom: -88,
    left: -28,
    backgroundColor: "rgba(46,229,143,0.10)",
  },
  chooserHeroBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    marginBottom: 12,
  },
  chooserHeroBadgeText: {
    color: T.text,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  chooserHeroAmount: {
    color: T.text,
    fontSize: 38,
    fontWeight: "900",
    letterSpacing: -1,
    textAlign: "center",
  },
  chooserHeroCaption: {
    color: T.textDim,
    fontSize: 12,
    fontWeight: "700",
    textAlign: "center",
    marginTop: 4,
  },
  chooserHeroStatsRow: {
    width: "100%",
    flexDirection: "row",
    gap: 10,
    marginTop: 16,
  },
  chooserHeroStatCard: {
    flex: 1,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 4,
  },
  chooserHeroStatLabel: {
    color: T.textMuted,
    fontSize: 11,
    fontWeight: "700",
  },
  chooserHeroStatValue: {
    color: T.text,
    fontSize: 16,
    fontWeight: "900",
  },
  chooserSummary: {
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 10,
    paddingBottom: 12,
    paddingHorizontal: 20,
    gap: 2,
  },
  chooserSummaryEyebrow: {
    color: T.textMuted,
    fontSize: 12,
    fontWeight: "700",
    textAlign: "center",
  },
  chooserSummaryPrimary: {
    color: T.text,
    fontSize: 32,
    fontWeight: "900",
    letterSpacing: -0.8,
    textAlign: "center",
  },
  chooserSummaryMeta: {
    color: T.textDim,
    fontSize: 12,
    fontWeight: "700",
    textAlign: "center",
    marginTop: 4,
  },
  chooserSummarySecondary: {
    color: T.text,
    fontSize: 18,
    fontWeight: "800",
    textAlign: "center",
  },
  amountSummaryCard: {
    flex: 1,
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: 12,
    backgroundColor: T.card,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 4,
  },
  amountSummaryLabel: { color: T.textMuted, fontSize: 11, fontWeight: "700" },
  amountSummaryValue: { color: T.text, fontSize: 15, fontWeight: "900" },
  amountSummaryHint: { color: T.textDim, fontSize: 11, fontWeight: "600", lineHeight: 16 },
  detailHero: {
    position: "relative",
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 30,
    paddingBottom: 28,
    paddingHorizontal: 22,
    marginBottom: 18,
    backgroundColor: "#171b2d",
    borderRadius: 30,
    borderWidth: 1,
    borderColor: "rgba(143,126,255,0.18)",
    gap: 8,
    shadowColor: "#000000",
    shadowOpacity: 0.28,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 14 },
    elevation: 12,
  },
  detailHeroGlow: {
    position: "absolute",
    borderRadius: 999,
  },
  detailHeroGlowPrimary: {
    width: 220,
    height: 220,
    top: -110,
    right: -52,
    backgroundColor: "rgba(124,92,255,0.24)",
  },
  detailHeroGlowSecondary: {
    width: 180,
    height: 180,
    bottom: -92,
    left: -28,
    backgroundColor: "rgba(46,229,143,0.10)",
  },
  detailHeroBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: "rgba(9,12,20,0.22)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.10)",
    marginBottom: 14,
  },
  detailHeroBadgeText: {
    color: T.text,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  detailHeroIcon: {
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    marginBottom: 6,
  },
  detailHeroTitle: {
    color: "#ffffff",
    fontSize: 17,
    fontWeight: "900",
    textAlign: "center",
    paddingHorizontal: 16,
  },
  detailHeroAmount: {
    color: "#ffffff",
    fontSize: 44,
    fontWeight: "900",
    letterSpacing: -1,
    textAlign: "center",
  },
  detailHeroMeta: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 12,
    fontWeight: "700",
    textAlign: "center",
    marginTop: 2,
  },
  detailHeroStatsRow: {
    width: "100%",
    flexDirection: "row",
    gap: 12,
    marginTop: 16,
  },
  detailHeroStatCard: {
    flex: 1,
    borderRadius: 20,
    backgroundColor: "rgba(12,16,28,0.28)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.09)",
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 6,
  },
  detailHeroStatLabel: {
    color: "rgba(255,255,255,0.58)",
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  detailHeroStatValue: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "900",
  },
  detailHeroStatValueSmall: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "800",
  },
  detailHeroDueLabel: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 12,
    fontWeight: "700",
    textAlign: "center",
    marginTop: 4,
  },
  detailHeroDueValue: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "800",
    textAlign: "center",
  },
  detailHeroInlineEditWrap: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    minHeight: 32,
  },
  detailHeroInlineCurrency: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "800",
  },
  detailHeroInlineInput: {
    minWidth: 124,
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "800",
    textAlign: "center",
    paddingVertical: 0,
  },
  detailEditorCard: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
    paddingVertical: 18,
    borderRadius: 24,
    backgroundColor: "rgba(10,14,24,0.30)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.09)",
    gap: 8,
    marginTop: 18,
  },
  detailEditorLabel: {
    color: "rgba(255,255,255,0.56)",
    fontSize: 11,
    fontWeight: "700",
    textAlign: "center",
  },
  detailEditorValue: {
    color: "#ffffff",
    fontSize: 22,
    fontWeight: "900",
    textAlign: "center",
    letterSpacing: -0.5,
  },
  detailHeroRemoveBtn: {
    marginTop: 12,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
    backgroundColor: "rgba(14,18,28,0.42)",
  },
  detailHeroRemoveText: {
    color: "rgba(255,255,255,0.82)",
    fontSize: 12,
    fontWeight: "700",
  },
  detailSectionStack: {
    gap: 16,
    paddingTop: 4,
  },
  detailSectionCard: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
    backgroundColor: "#14192b",
    padding: 18,
    gap: 14,
    shadowColor: "#000000",
    shadowOpacity: 0.16,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  detailSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  detailSectionTitle: {
    color: T.text,
    fontSize: 15,
    fontWeight: "900",
  },
  detailSectionPill: {
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  detailSectionPillText: {
    color: T.textMuted,
    fontSize: 11,
    fontWeight: "700",
  },
  detailSectionHelp: {
    color: "rgba(220,224,240,0.70)",
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 20,
  },
  detailOptionGrid: {
    flexDirection: "row",
    gap: 10,
  },
  detailOptionCard: {
    flex: 1,
    minHeight: 64,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "rgba(20,24,38,0.92)",
    paddingHorizontal: 12,
    paddingVertical: 14,
    justifyContent: "center",
  },
  detailOptionCardActive: {
    borderColor: "rgba(151,123,255,0.56)",
    backgroundColor: "rgba(124,92,255,0.24)",
  },
  detailOptionCardTitle: {
    color: T.text,
    fontSize: 13,
    fontWeight: "800",
    textAlign: "center",
    lineHeight: 18,
  },
  detailOptionCardTitleActive: {
    color: "#ffffff",
  },
  detailPillWrap: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginTop: 2 },
  detailPill: {
    minWidth: 108,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(20,24,38,0.92)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 11,
  },
  detailPillActive: {
    backgroundColor: "rgba(124,92,255,0.24)",
    borderColor: "rgba(151,123,255,0.56)",
  },
  detailPillText: { color: T.textDim, fontSize: 13, fontWeight: "700" },
  detailPillTextActive: { color: "#ffffff", fontWeight: "800" },
  amountHeroBlock: {
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
    paddingVertical: 4,
    gap: 2,
  },
  amountHeroValue: {
    color: T.text,
    fontSize: 24,
    fontWeight: "900",
    letterSpacing: -0.6,
    textAlign: "center",
  },
  amountHeroMeta: {
    color: T.textMuted,
    fontSize: 11,
    fontWeight: "700",
    textAlign: "center",
    marginBottom: 6,
  },
  amountHeroDueLabel: {
    color: T.textDim,
    fontSize: 11,
    fontWeight: "700",
    textAlign: "center",
    marginTop: 2,
  },
  amountHeroDueValue: {
    color: T.text,
    fontSize: 14,
    fontWeight: "800",
    textAlign: "center",
  },
  targetCardList: { gap: 10 },
  targetSectionDivider: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    marginTop: 4,
  },
  targetCard: {
    position: "relative",
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    borderRadius: 20,
    backgroundColor: "#1b2033",
    padding: 16,
    shadowColor: "#000000",
    shadowOpacity: 0.14,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 6,
  },
  targetCardPressed: {
    transform: [{ scale: 0.985 }],
    borderColor: "rgba(124,92,255,0.22)",
  },
  targetCardGlow: {
    ...StyleSheet.absoluteFillObject,
    opacity: 1,
  },
  targetCardIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  targetCardMainRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  targetCardLead: { flexDirection: "row", alignItems: "center", gap: 12, flex: 1, minWidth: 0 },
  targetCardCopy: { flex: 1, minWidth: 0 },
  targetCardAmountBadge: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 32,
  },
  targetCardTitle: { color: T.text, fontSize: 15, fontWeight: "900", marginBottom: 3 },
  targetCardAmount: { color: T.text, fontSize: 15, fontWeight: "900" },
  targetCardMeta: { color: T.textDim, fontSize: 12, fontWeight: "700" },
  targetCardMetaRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10, marginTop: 14, marginBottom: 8 },
  targetCardDuePill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    paddingHorizontal: 10,
    paddingVertical: 7,
    flexShrink: 1,
  },
  targetCardDueLabel: { color: T.textMuted, fontSize: 11, fontWeight: "700" },
  targetCardDueText: { color: T.text, fontSize: 12, fontWeight: "800" },
  targetCardGoalPill: {
    maxWidth: 140,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  targetCardGoalText: { color: T.textMuted, fontSize: 11, fontWeight: "700", flexShrink: 1 },
  targetCardProgressMeta: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10, marginBottom: 6 },
  targetCardProgressLabel: { color: T.textDim, fontSize: 11, fontWeight: "700" },
  targetCardProgressValue: { color: T.text, fontSize: 11, fontWeight: "800" },
  targetCardProgressBg: { height: 7, borderRadius: 999, backgroundColor: "rgba(255,255,255,0.08)", overflow: "hidden" },
  targetCardProgressFill: { height: 7, borderRadius: 4 },
  targetCardChevronWrap: {
    position: "absolute",
    right: 14,
    top: 14,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.05)",
    alignItems: "center",
    justifyContent: "center",
  },
  targetCardAccentTrack: {
    marginTop: 12,
    height: 5,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.08)",
    overflow: "hidden",
  },
  targetCardAccentFill: {
    height: "100%",
    borderRadius: 999,
  },
  targetSectionTitle: {
    color: T.textDim,
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  targetSectionCountPill: {
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  targetSectionCountText: {
    color: T.textMuted,
    fontSize: 11,
    fontWeight: "700",
  },
  emptyStateCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    backgroundColor: "#171b2d",
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  emptyStateText: {
    color: T.textDim,
    fontSize: 13,
    fontWeight: "700",
  },
  optionGrid: {
    flexDirection: "row",
    gap: 8,
  },
  optionCard: {
    flex: 1,
    minHeight: 56,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.card,
    paddingHorizontal: 10,
    paddingVertical: 10,
    justifyContent: "center",
  },
  optionCardActive: {
    borderColor: T.accent,
    backgroundColor: `${T.accent}18`,
  },
  optionCardTitle: {
    color: T.text,
    fontSize: 12,
    fontWeight: "800",
    textAlign: "center",
  },
  optionCardTitleActive: {
    color: T.accent,
  },
  pillWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  pill: {
    backgroundColor: T.cardAlt,
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  pillActive: { backgroundColor: `${T.accent}22`, borderColor: T.accent },
  pillText: { color: T.textDim, fontSize: 12, fontWeight: "700" },
  pillTextActive: { color: T.accent, fontWeight: "800" },
  monthGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  monthChip: {
    width: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.cardAlt,
    paddingVertical: 7,
  },
  monthChipActive: { borderColor: T.accent, backgroundColor: `${T.accent}22` },
  monthChipText: { color: T.textDim, fontSize: 12, fontWeight: "700" },
  monthChipTextActive: { color: T.accent, fontWeight: "800" },
  yearRow: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 10 },
  yearBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.cardAlt,
  },
  yearValue: { color: T.text, fontSize: 16, fontWeight: "900", minWidth: 74, textAlign: "center" },
  removeAmountBtn: {
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.cardAlt,
  },
  removeAmountText: { color: T.textDim, fontSize: 12, fontWeight: "700" },
});
