import { StyleSheet } from "react-native";

import { T } from "@/lib/theme";

export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: T.bg },
  flex: { flex: 1 },
  scrollContent: { paddingHorizontal: 18, paddingBottom: 40, gap: 12 },
  pickWrap: {
    flex: 1,
    paddingHorizontal: 24,
    gap: 14,
    paddingTop: 8,
  },
  heroIconWrap: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: `${T.accent}18`,
    borderWidth: 1,
    borderColor: T.accentBorder,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    marginBottom: 8,
  },
  heroTitle: { color: T.text, fontSize: 22, fontWeight: "800", textAlign: "center" },
  heroSub: { color: T.textDim, fontSize: 14, textAlign: "center", lineHeight: 20 },
  pickOptionCamera: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: T.accent,
    borderRadius: 18,
    padding: 18,
    gap: 14,
  },
  pickOptionGallery: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: T.card,
    borderRadius: 18,
    padding: 18,
    gap: 14,
    borderWidth: 1,
    borderColor: T.border,
  },
  pickOptionIcon: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: `${T.onAccent}22`,
    alignItems: "center",
    justifyContent: "center",
  },
  pickOptionIconSecondary: {
    backgroundColor: `${T.accent}15`,
  },
  pickOptionText: { flex: 1 },
  pickOptionTitle: { color: T.onAccent, fontSize: 16, fontWeight: "700" },
  pickOptionSub: { color: `${T.onAccent}bb`, fontSize: 12, marginTop: 2 },
  scanningWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  previewImg: {
    position: "absolute",
    width: "100%",
    height: "100%",
    opacity: 0.3,
  },
  scanningOverlay: {
    alignItems: "center",
    gap: 8,
    padding: 32,
    backgroundColor: `${T.bg}cc`,
    borderRadius: 24,
    margin: 24,
  },
  scanningIcon: {},
  scanningTitle: { color: T.text, fontSize: 20, fontWeight: "700" },
  scanningSubtitle: { color: T.textDim, fontSize: 14 },
  thumbWrap: {
    borderRadius: 16,
    overflow: "hidden",
    height: 140,
    backgroundColor: T.card,
    borderWidth: 1,
    borderColor: T.border,
    alignItems: "center",
    justifyContent: "center",
  },
  thumb: { width: "100%", height: "100%" },
  thumbBadge: {
    position: "absolute",
    bottom: 8,
    right: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: `${T.bg}dd`,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  thumbBadgeTxt: { color: T.green, fontSize: 12, fontWeight: "600" },
  amountCard: {
    backgroundColor: T.card,
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: T.accentBorder,
  },
  amountLabelRow: { flexDirection: "row", alignItems: "center", gap: 5, marginBottom: 10 },
  amountLabel: { color: T.textDim, fontSize: 13, fontWeight: "500" },
  amountInputRow: { flexDirection: "row", alignItems: "baseline", gap: 4 },
  currencySymbol: { color: T.text, fontSize: 28, fontWeight: "700" },
  amountInput: {
    flex: 1,
    color: T.text,
    fontSize: 42,
    fontWeight: "800",
    padding: 0,
    letterSpacing: -1,
  },
  fieldCard: {
    backgroundColor: T.card,
    borderRadius: 16,
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: T.border,
  },
  fieldLabel: { color: T.textDim, fontSize: 11, fontWeight: "600", textTransform: "uppercase", letterSpacing: 0.6, marginBottom: 6 },
  fieldInput: { color: T.text, fontSize: 16, padding: 0 },
  fieldRow: { flexDirection: "row", alignItems: "center" },
  fieldValue: { flex: 1, color: T.text, fontSize: 15, fontWeight: "500" },
  fieldPlaceholder: { flex: 1, color: T.textMuted, fontSize: 15 },
  fieldChevron: { marginLeft: 6 },
  catDot: { width: 10, height: 10, borderRadius: 5, marginRight: 10 },
  errorWrap: { flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 4 },
  errorText: { color: T.red, fontSize: 13, flex: 1 },
  submitBtn: {
    backgroundColor: T.accent,
    borderRadius: 16,
    paddingVertical: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 8,
  },
  submitBtnDisabled: { opacity: 0.45 },
  submitTxt: { color: T.onAccent, fontSize: 16, fontWeight: "700" },
  modalOverlay: { flex: 1 },
  modalBackdrop: { flex: 1, backgroundColor: "rgba(0,0,0,0.5)" },
  modalSheet: {
    backgroundColor: T.card,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 12,
    paddingHorizontal: 18,
    paddingBottom: 40,
    maxHeight: "75%",
  },
  sheetHandle: {
    width: 40,
    height: 4,
    backgroundColor: T.border,
    borderRadius: 2,
    alignSelf: "center",
    marginBottom: 16,
  },
  sheetTitle: { color: T.text, fontSize: 16, fontWeight: "700", marginBottom: 12 },
  catList: { paddingBottom: 8 },
  catRow: { flexDirection: "row", alignItems: "center", paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: T.border },
  catRowSelected: { backgroundColor: `${T.accent}0d`, marginHorizontal: -18, paddingHorizontal: 18 },
  catName: { flex: 1, color: T.text, fontSize: 15 },
  catCheck: { marginLeft: 8 },
  pickerYearRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    marginBottom: 16,
  },
  pickerYearBtn: { width: 32, height: 32, alignItems: "center", justifyContent: "center" },
  pickerYearText: { color: T.text, fontSize: 22, fontWeight: "700", minWidth: 60, textAlign: "center" },
  pickerGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    justifyContent: "space-between",
  },
  pickerCell: {
    width: "23%",
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.cardAlt,
    alignItems: "center",
  },
  pickerCellSelected: { backgroundColor: T.accent, borderColor: T.accent },
  pickerCellText: { color: T.textDim, fontSize: 14, fontWeight: "500" },
  pickerCellSelectedText: { color: T.onAccent, fontWeight: "700" },
});