import { StyleSheet } from "react-native";

import { T } from "@/lib/theme";
import { cardBase, cardElevated } from "@/lib/ui";

export const analyticsStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: T.bg },
  center: { flex: 1, alignItems: "center", justifyContent: "center", gap: 10, paddingHorizontal: 24 },
  loading: { color: T.textDim, fontSize: 14, fontWeight: "700" },
  error: { color: T.red, textAlign: "center", fontSize: 14, fontWeight: "700" },
  retryBtn: { marginTop: 8, backgroundColor: T.accent, borderRadius: 10, paddingHorizontal: 20, paddingVertical: 10 },
  retryTxt: { color: T.onAccent, fontWeight: "800" },
  scroll: { padding: 16, paddingBottom: 36, gap: 12 },
  grid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  card: {
    ...cardElevated,
    width: "48%",
    padding: 12,
    minHeight: 92,
    justifyContent: "space-between",
  },
  cardLabel: { color: T.textDim, fontSize: 12, fontWeight: "800" },
  cardValue: { color: T.text, fontSize: 18, fontWeight: "900" },
  cardSub: { color: T.textMuted, fontSize: 11, fontWeight: "700" },
  tipCard: { ...cardBase, padding: 14 },
  tipTitle: { color: T.text, fontSize: 15, fontWeight: "900", marginBottom: 6 },
  tipRow: { flexDirection: "row", gap: 8, alignItems: "flex-start", paddingVertical: 8 },
  tipRowBorder: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: T.border },
  tipTitleRow: { flexDirection: "row", alignItems: "center", gap: 6, flexWrap: "wrap" },
  tipRowTitle: { color: T.text, fontSize: 13, fontWeight: "800", marginBottom: 2 },
  tipText: { color: T.textDim, fontSize: 12, fontWeight: "600" },
  priorityBadge: {
    color: T.red,
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
    borderWidth: 1,
    borderColor: `${T.red}66`,
    backgroundColor: `${T.red}24`,
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 999,
    overflow: "hidden",
  },
  overviewHead: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  overviewModeBadge: {
    color: T.textMuted,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  overviewChartWrap: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.card,
    paddingTop: 10,
    paddingBottom: 8,
    paddingHorizontal: 4,
    alignItems: "center",
    position: "relative",
    overflow: "hidden",
  },
  overviewYAxisOverlay: {
    position: "absolute",
    left: 6,
    top: 16,
    bottom: 44,
    width: 34,
    paddingRight: 6,
    borderRightWidth: 1,
    borderRightColor: T.border,
    justifyContent: "space-between",
    alignItems: "flex-end",
    zIndex: 2,
  },
  overviewYAxisLabel: {
    color: T.textMuted,
    fontSize: 10,
    fontWeight: "700",
  },
  chartAxisText: {
    color: T.textMuted,
    fontSize: 10,
    fontWeight: "700",
  },
  chartAxisXText: {
    color: T.textMuted,
    fontSize: 8,
    fontWeight: "600",
    letterSpacing: 0,
  },
  pointerTooltip: {
    backgroundColor: "#0a0a0a",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    justifyContent: "center",
  },
  pointerTooltipValue: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "900",
  },
  pointerTooltipMonth: {
    marginTop: 2,
    color: "#d2d2d2",
    fontSize: 11,
    fontWeight: "700",
  },
  legendRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    marginTop: 10,
  },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  legendDot: {
    width: 10,
    height: 10,
    borderRadius: 2,
  },
  legendText: {
    color: T.text,
    fontSize: 12,
    fontWeight: "700",
  },
  barRow: {
    paddingVertical: 7,
  },
  barRowHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 5,
    gap: 8,
  },
  barName: {
    flex: 1,
    color: T.text,
    fontSize: 12,
    fontWeight: "800",
  },
  barValue: {
    color: T.textDim,
    fontSize: 12,
    fontWeight: "700",
  },
  barTrack: {
    height: 8,
  },
});