import { StyleSheet } from "react-native";

import { T } from "@/lib/theme";
import { cardBase, cardElevated } from "@/lib/ui";

export const analyticsStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: T.bg },
  screenShell: { flex: 1, position: "relative" },
  screenGlowPrimary: {
    position: "absolute",
    top: -110,
    right: -70,
    width: 260,
    height: 260,
    borderRadius: 999,
    backgroundColor: "rgba(124,92,255,0.14)",
  },
  screenGlowSecondary: {
    position: "absolute",
    top: 210,
    left: -120,
    width: 250,
    height: 250,
    borderRadius: 999,
    backgroundColor: "rgba(46,229,143,0.08)",
  },
  center: { flex: 1, alignItems: "center", justifyContent: "center", gap: 10, paddingHorizontal: 24 },
  loading: { color: T.textDim, fontSize: 14, fontWeight: "700" },
  error: { color: T.red, textAlign: "center", fontSize: 14, fontWeight: "700" },
  retryBtn: { marginTop: 8, backgroundColor: T.accent, borderRadius: 10, paddingHorizontal: 20, paddingVertical: 10 },
  retryTxt: { color: T.onAccent, fontWeight: "800" },
  scroll: { paddingHorizontal: 16, paddingBottom: 40, gap: 18 },
  grid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  overviewHero: {
    position: "relative",
    marginHorizontal: -20,
    paddingHorizontal: 12,
    paddingBottom: 18,
    paddingTop: 4,
    overflow: "hidden",
  },
  card: {
    ...cardElevated,
    width: "48%",
    padding: 14,
    minHeight: 132,
    justifyContent: "space-between",
    borderRadius: 26,
    backgroundColor: "#141a2d",
    borderWidth: 1,
    borderColor: "rgba(244,246,255,0.06)",
    overflow: "hidden",
  },
  cardGlow: {
    position: "absolute",
    top: -34,
    right: -22,
    width: 120,
    height: 120,
    borderRadius: 999,
  },
  cardGlowSecondary: {
    position: "absolute",
    bottom: -46,
    left: -18,
    width: 92,
    height: 92,
    borderRadius: 999,
  },
  cardTopRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 16 },
  cardIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  cardChip: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  cardChipText: { fontSize: 10, fontWeight: "800", letterSpacing: 0.2, textTransform: "uppercase" },
  cardLabel: { color: T.textDim, fontSize: 13, fontWeight: "800", marginBottom: 8 },
  cardValue: { color: T.text, fontSize: 22, fontWeight: "900", letterSpacing: -0.6, marginBottom: 6 },
  cardSub: { color: T.textMuted, fontSize: 12, fontWeight: "700", lineHeight: 18, paddingRight: 10 },
  cardAccentLine: {
    marginTop: 14,
    height: 4,
    borderRadius: 999,
    opacity: 0.9,
  },
  tipCard: {
    ...cardBase,
    padding: 18,
    borderRadius: 28,
    backgroundColor: "#14192b",
    borderColor: "rgba(244,246,255,0.06)",
    shadowColor: "#000000",
    shadowOpacity: 0.22,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 14 },
    elevation: 10,
    overflow: "hidden",
  },
  sectionGlow: {
    position: "absolute",
    borderRadius: 999,
  },
  overviewGlowPrimary: {
    width: 180,
    height: 180,
    top: -70,
    right: -20,
    backgroundColor: "rgba(124,92,255,0.16)",
  },
  overviewGlowSecondary: {
    width: 150,
    height: 150,
    bottom: -68,
    left: -24,
    backgroundColor: "rgba(59,153,255,0.08)",
  },
  tipsGlowPrimary: {
    width: 170,
    height: 170,
    top: -84,
    right: -26,
    backgroundColor: "rgba(124,92,255,0.12)",
  },
  debtGlowPrimary: {
    width: 170,
    height: 170,
    top: -84,
    right: -26,
    backgroundColor: "rgba(255,176,32,0.10)",
  },
  sectionHead: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 10,
  },
  sectionEyebrow: {
    color: T.textMuted,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.5,
    textTransform: "uppercase",
    marginBottom: 5,
  },
  sectionBadge: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(244,246,255,0.10)",
    backgroundColor: "rgba(255,255,255,0.05)",
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  sectionBadgeText: { color: T.textDim, fontSize: 11, fontWeight: "800" },
  tipTitle: { color: T.text, fontSize: 15, fontWeight: "900", marginBottom: 2 },
  tipRow: { flexDirection: "row", gap: 10, alignItems: "flex-start", paddingVertical: 12 },
  tipRowBorder: { borderTopWidth: 1, borderTopColor: "rgba(244,246,255,0.08)" },
  tipIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: `${T.accent}35`,
    backgroundColor: `${T.accent}14`,
  },
  tipTitleRow: { flexDirection: "row", alignItems: "center", gap: 6, flexWrap: "wrap" },
  tipRowTitle: { color: T.text, fontSize: 14, fontWeight: "800", marginBottom: 3 },
  tipText: { color: T.textDim, fontSize: 13, fontWeight: "600", lineHeight: 20 },
  priorityBadge: {
    color: T.red,
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
    borderWidth: 1,
    borderColor: `${T.red}66`,
    backgroundColor: `${T.red}24`,
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 999,
    overflow: "hidden",
  },
  overviewHead: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
    gap: 12,
  },
  overviewHeroHead: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 12,
  },
  overviewHeroTitle: {
    color: T.text,
    fontSize: 22,
    fontWeight: "900",
    letterSpacing: -0.5,
  },
  overviewModeBadge: {
    color: T.text,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    borderWidth: 1,
    borderColor: "rgba(244,246,255,0.10)",
    backgroundColor: "rgba(255,255,255,0.05)",
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: 999,
  },
  overviewFlatChartWrap: {
    minHeight: 228,
    paddingTop: 4,
    paddingBottom: 8,
    paddingLeft: 0,
    paddingRight: 0,
    alignItems: "stretch",
    position: "relative",
    overflow: "hidden",
  },
  overviewPinnedSummary: {
    alignSelf: "flex-start",
    minWidth: 176,
    marginBottom: 10,
    paddingHorizontal: 2,
    gap: 6,
  },
  overviewPinnedSummaryLabel: {
    color: T.textMuted,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  overviewPinnedSummaryMetricRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  overviewPinnedSummaryDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
  },
  overviewPinnedSummaryMetricName: {
    color: T.textMuted,
    fontSize: 12,
    fontWeight: "700",
    minWidth: 56,
  },
  overviewPinnedSummaryMetricValue: {
    color: T.text,
    fontSize: 15,
    fontWeight: "900",
    letterSpacing: -0.2,
  },
  overviewPlotWrap: {
    position: "relative",
    minHeight: 174,
    overflow: "hidden",
  },
  overviewChartWrap: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "rgba(244,246,255,0.08)",
    backgroundColor: "#161b2f",
    paddingTop: 12,
    paddingBottom: 10,
    paddingLeft: 6,
    paddingRight: 6,
    alignItems: "center",
    position: "relative",
    overflow: "hidden",
  },
  overviewYAxisOverlay: {
    position: "absolute",
    right: 0,
    top: 14,
    bottom: 40,
    width: 60,
    paddingLeft: 8,
    justifyContent: "space-between",
    alignItems: "flex-end",
    zIndex: 2,
  },
  overviewYAxisLabel: {
    color: T.textMuted,
    fontSize: 11,
    fontWeight: "800",
  },
  chartAxisText: {
    color: T.textMuted,
    fontSize: 10,
    fontWeight: "700",
  },
  chartAxisXText: {
    color: T.textMuted,
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 0.25,
  },
  pointerTooltip: {
    backgroundColor: "#0f1422",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(244,246,255,0.10)",
    paddingHorizontal: 10,
    paddingVertical: 8,
    justifyContent: "center",
  },
  pointerTooltipValue: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "900",
  },
  pointerTooltipMonth: {
    marginTop: 2,
    color: "#d2d2d2",
    fontSize: 11,
    fontWeight: "700",
  },
  legendRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    marginTop: 12,
    flexWrap: "wrap",
  },
  overviewLegendRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    marginTop: 8,
    flexWrap: "wrap",
  },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(244,246,255,0.10)",
    backgroundColor: "rgba(255,255,255,0.05)",
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  legendDot: {
    width: 10,
    height: 10,
    borderRadius: 4,
  },
  legendText: {
    color: T.text,
    fontSize: 12,
    fontWeight: "700",
  },
  barRow: {
    paddingVertical: 10,
  },
  barRowHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 7,
    gap: 8,
  },
  barName: {
    flex: 1,
    color: T.text,
    fontSize: 13,
    fontWeight: "800",
  },
  barValuePill: {
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(244,246,255,0.08)",
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  barValue: {
    color: T.text,
    fontSize: 11,
    fontWeight: "800",
  },
  barTrack: {
    height: 10,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.06)",
    overflow: "hidden",
  },
  barFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: T.accent,
  },
});