import { StyleSheet } from "react-native";

import { BRAND_BLUE } from "@/lib/constants";
import { T } from "@/lib/theme";

export const styles = StyleSheet.create({
	sheetOverlay: {
		flex: 1,
		justifyContent: "flex-end",
		backgroundColor: "rgba(0,0,0,0.5)",
	},
	sheet: {
		backgroundColor: T.card,
		borderTopLeftRadius: 18,
		borderTopRightRadius: 18,
		borderTopWidth: 1,
		borderTopColor: T.border,
		paddingHorizontal: 16,
		paddingTop: 14,
		paddingBottom: 20,
		gap: 8,
	},
	sheetTall: {
		height: "88%",
		maxHeight: "90%",
	},
	moneyEditorSheet: {
		backgroundColor: BRAND_BLUE,
		borderTopColor: "rgba(255,255,255,0.14)",
	},
	sheetHandle: {
		alignSelf: "center",
		width: 46,
		height: 5,
		borderRadius: 999,
		backgroundColor: T.border,
		marginBottom: 4,
	},
	sheetTitle: { color: T.text, fontSize: 18, fontWeight: "900", marginBottom: 6 },
	sheetBody: {
		flex: 1,
		minHeight: 0,
	},
	sheetScroll: {
		flex: 1,
	},
	sheetScrollContent: {
		gap: 8,
		paddingBottom: 10,
	},
	moneyEditorHeader: {
		borderRadius: 18,
		backgroundColor: BRAND_BLUE,
		borderWidth: 1,
		borderColor: `${T.onAccent}22`,
		paddingHorizontal: 16,
		paddingTop: 14,
		paddingBottom: 16,
		marginBottom: 10,
		alignItems: "center",
		gap: 6,
	},
	moneyEditorIconCircle: {
		width: 42,
		height: 42,
		borderRadius: 21,
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: `${T.onAccent}22`,
		borderWidth: 1,
		borderColor: `${T.onAccent}33`,
	},
	moneyEditorHeroTitle: {
		color: T.onAccent,
		fontSize: 15,
		fontWeight: "800",
	},
	moneyEditorHeroValue: {
		color: T.onAccent,
		fontSize: 46,
		fontWeight: "900",
		letterSpacing: -0.6,
		lineHeight: 52,
	},
	moneyEditorStatsRow: {
		flexDirection: "row",
		gap: 10,
		marginBottom: 8,
	},
	moneyEditorStatCard: {
		flex: 1,
		borderRadius: 12,
		borderWidth: 1,
		borderColor: "rgba(255,255,255,0.22)",
		backgroundColor: "rgba(88,64,190,0.58)",
		paddingVertical: 10,
		paddingHorizontal: 12,
		alignItems: "center",
		gap: 2,
	},
	moneyEditorStatLabel: {
		color: "rgba(255,255,255,0.75)",
		fontSize: 12,
		fontWeight: "700",
	},
	moneyEditorStatValue: {
		color: T.onAccent,
		fontSize: 22,
		fontWeight: "900",
	},
	label: { color: T.textDim, fontSize: 12, fontWeight: "800" },
	input: {
		backgroundColor: T.cardAlt,
		borderRadius: 10,
		borderWidth: 1,
		borderColor: T.border,
		color: T.text,
		paddingHorizontal: 12,
		paddingVertical: 10,
	},
	sheetActionsDocked: {
		flexDirection: "row",
		gap: 10,
		marginTop: 8,
		paddingTop: 10,
		borderTopWidth: StyleSheet.hairlineWidth,
		borderTopColor: T.border,
		backgroundColor: T.card,
	},
	moneyEditorDockedActions: {
		backgroundColor: BRAND_BLUE,
		borderTopColor: "rgba(255,255,255,0.2)",
	},
	moneyDeleteBtn: {
		flex: 1,
		borderRadius: 10,
		borderWidth: 1,
		borderColor: "rgba(255,255,255,0.85)",
		backgroundColor: "#ffffff",
		paddingVertical: 12,
		alignItems: "center",
	},
	moneyDeleteBtnText: {
		color: BRAND_BLUE,
		fontSize: 16,
		fontWeight: "800",
	},
	outlineBtnWide: {
		flex: 1,
		borderRadius: 10,
		borderWidth: 1,
		borderColor: T.border,
		backgroundColor: T.cardAlt,
		paddingVertical: 12,
		alignItems: "center",
	},
	outlineBtnText: { color: T.textDim, fontSize: 12, fontWeight: "800" },
	primaryBtnWide: {
		flex: 1,
		borderRadius: 10,
		backgroundColor: T.accent,
		paddingVertical: 12,
		alignItems: "center",
	},
	primaryBtnText: { color: T.onAccent, fontWeight: "800", fontSize: 13 },
	disabled: { opacity: 0.6 },
});
