import { StyleSheet } from "react-native";

import { T } from "@/lib/theme";

export const debtStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: T.bg },
  center: { flex: 1, justifyContent: "center", alignItems: "center", gap: 12 },
  scroll: { paddingBottom: 140 },
  heroRow: { flexDirection: "row", gap: 12, padding: 14, paddingBottom: 0 },
  heroCard: {
    flex: 1,
    minHeight: 132,
    paddingHorizontal: 18,
    paddingVertical: 18,
    gap: 4,
    position: "relative",
    overflow: "hidden",
    borderRadius: 24,
    borderWidth: 1,
    backgroundColor: "#141826",
    shadowColor: "#000000",
    shadowOpacity: 0.2,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  heroCardGlow: {
    position: "absolute",
    borderRadius: 999,
  },
  heroCardGlowStart: {
    width: 138,
    height: 138,
    top: -56,
    left: -34,
  },
  heroCardGlowEnd: {
    width: 112,
    height: 112,
    right: -22,
    bottom: -44,
  },
  heroCardInnerBorder: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.03)",
  },
  heroLabel: { color: T.textDim, fontSize: 11, fontWeight: "900", letterSpacing: 1.1 },
  heroValue: { fontSize: 24, fontWeight: "900", marginTop: 8, letterSpacing: -0.6 },
  heroSub: { color: T.textMuted, fontSize: 12, fontWeight: "700", marginTop: 4 },
  termWrap: { width: "100%", gap: 8 },
  inlineRow: { flexDirection: "row", gap: 10, alignItems: "flex-start" },
  termLabel: { color: T.textDim, fontSize: 12, fontWeight: "800" },
  termRow: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginTop: 8, marginBottom: 10 },
  termBtn: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.cardAlt,
  },
  termBtnActive: { borderColor: T.accent, backgroundColor: `${T.accent}2A` },
  termBtnTxt: { color: T.textDim, fontSize: 12, fontWeight: "700" },
  termBtnTxtActive: { color: T.accent, fontWeight: "800" },
  cardChoiceWrap: { gap: 8 },
  cardChoiceBtn: {
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: 8,
    backgroundColor: T.cardAlt,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  cardChoiceBtnActive: { borderColor: T.accent, backgroundColor: `${T.accent}2A` },
  cardChoiceTxt: { color: T.text, fontSize: 13, fontWeight: "700" },
  cardChoiceTxtActive: { color: T.accent, fontWeight: "800" },
  cardChoiceEmpty: { color: T.textDim, fontSize: 12, fontWeight: "700" },
  chartCard: {
    margin: 14,
    marginBottom: 0,
    paddingHorizontal: 16,
    paddingTop: 4,
    paddingBottom: 0,
    gap: 14,
    position: "relative",
    overflow: "visible",
  },
  chartGlow: {
    position: "absolute",
    borderRadius: 999,
  },
  chartGlowPrimary: {
    width: 220,
    height: 220,
    top: -120,
    right: -72,
    backgroundColor: "rgba(124,92,255,0.18)",
  },
  chartGlowSecondary: {
    width: 170,
    height: 170,
    bottom: -90,
    left: -58,
    backgroundColor: "rgba(68,126,255,0.10)",
  },
  chartInnerBorder: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 26,
    borderWidth: 0,
    borderColor: "transparent",
  },
  chartHeader: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 10, marginBottom: 4 },
  chartTitle: { color: T.text, fontSize: 16, fontWeight: "900", letterSpacing: -0.3 },
  chartSub: { color: T.textMuted, fontSize: 12, fontWeight: "700", marginTop: 4 },
  chartBadge: {
    backgroundColor: "rgba(124,92,255,0.14)",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: "rgba(124,92,255,0.28)",
  },
  chartBadgeTxt: { color: T.accent, fontSize: 13, fontWeight: "900" },
  analyticsBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 14,
    backgroundColor: "rgba(124,92,255,0.14)",
    borderWidth: 1,
    borderColor: "rgba(124,92,255,0.28)",
  },
  analyticsBtnTxt: { color: T.accent, fontSize: 13, fontWeight: "800" },
  milestoneRow: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 8 },
  milestoneLabel: { color: T.textMuted, fontSize: 12, fontWeight: "700", marginRight: 4 },
  milestoneChip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.03)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  milestoneChipActive: { borderColor: "rgba(124,92,255,0.32)", backgroundColor: "rgba(124,92,255,0.16)" },
  milestoneChipText: { color: T.textDim, fontSize: 12, fontWeight: "800" },
  milestoneChipTextActive: { color: T.accent },
  chipRow: { flexDirection: "row", gap: 10 },
  chip: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.03)",
    borderWidth: 1,
  },
  chipLabel: { color: T.textMuted, fontSize: 10, fontWeight: "900", letterSpacing: 0.8 },
  chipValue: { color: T.text, fontSize: 12, fontWeight: "800", marginTop: 3 },
  tipsCard: {
    margin: 14,
    marginTop: 6,
    padding: 16,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    backgroundColor: "#141826",
    shadowColor: "#000000",
    shadowOpacity: 0.18,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  tipsHeader: { flexDirection: "row", alignItems: "center", gap: 6, marginBottom: 8 },
  tipsHeading: { color: T.text, fontSize: 13, fontWeight: "900" },
  tipRow: { flexDirection: "row", paddingVertical: 6 },
  tipBorder: { borderTopWidth: 1, borderTopColor: T.border, marginTop: 6 },
  tipTitle: { color: T.text, fontSize: 13, fontWeight: "900" },
  tipDetail: { color: T.textDim, fontSize: 12, marginTop: 2, fontWeight: "600" },
  listHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 8,
  },
  listHeaderSpacer: { width: 1, height: 1 },
  filterToggle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    padding: 5,
    borderRadius: 999,
    backgroundColor: "#141826",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  filterToggleOption: {
    minWidth: 96,
    paddingHorizontal: 16,
    paddingVertical: 11,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
  },
  filterToggleOptionActive: {
    backgroundColor: "rgba(124,92,255,0.16)",
    borderWidth: 1,
    borderColor: "rgba(124,92,255,0.34)",
  },
  filterToggleText: { color: T.textDim, fontSize: 14, fontWeight: "800" },
  filterToggleTextActive: { color: T.text },
  addBtn: {
    backgroundColor: T.accent,
    borderRadius: 999,
    minHeight: 44,
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    shadowColor: T.accent,
    shadowOpacity: 0.28,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  addBtnTxt: { color: T.onAccent, fontSize: 14, fontWeight: "900" },
  addForm: { margin: 0, padding: 0, gap: 10 },
  input: {
    backgroundColor: T.cardAlt,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: T.text,
    fontSize: 14,
    borderWidth: 1,
    borderColor: T.border,
  },
  dateValue: { color: T.text, fontSize: 14, fontWeight: "600" },
  dateValuePlaceholder: { color: T.textMuted, fontWeight: "500" },
  dropdownAnchor: { position: "relative", zIndex: 20 },
  saveBtn: {
    backgroundColor: T.accent,
    borderRadius: 8,
    paddingVertical: 11,
    alignItems: "center",
    marginTop: 10,
  },
  saveBtnTxt: { color: T.onAccent, fontWeight: "700", fontSize: 14 },
  disabled: { opacity: 0.5 },
  card: {
    flexDirection: "row",
    marginHorizontal: 14,
    marginBottom: 10,
    position: "relative",
    overflow: "hidden",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    backgroundColor: "#141826",
    shadowColor: "#000000",
    shadowOpacity: 0.18,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  cardPressed: { opacity: 0.75 },
  cardGlow: {
    position: "absolute",
    width: 160,
    height: 160,
    top: -82,
    left: -40,
    borderRadius: 999,
  },
  cardInnerBorder: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.03)",
  },
  cardAccent: { width: 5 },
  cardBody: { flex: 1, paddingHorizontal: 16, paddingVertical: 15, gap: 10 },
  cardTop: { flexDirection: "row", alignItems: "flex-start" },
  cardLeft: { flex: 1 },
  cardRight: { alignItems: "flex-end" },
  cardTitleRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "rgba(124,92,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  avatarLogo: { width: "100%", height: "100%", borderRadius: 999 },
  avatarTxt: { color: T.textDim, fontSize: 16, fontWeight: "900" },
  cardName: { color: T.text, fontSize: 16, fontWeight: "900", flexShrink: 1 },
  cardType: { fontSize: 12, fontWeight: "700", marginTop: 4 },
  cardBalance: { color: T.text, fontSize: 18, fontWeight: "900", letterSpacing: -0.4 },
  cardBalancePaid: { color: T.green },
  cardMonthly: { color: T.textDim, fontSize: 12, marginTop: 4, fontWeight: "700" },
  progressWrap: { gap: 5 },
  progressBg: { height: 8, backgroundColor: "rgba(255,255,255,0.08)", borderRadius: 999, overflow: "hidden" },
  progressFill: { height: "100%", borderRadius: 3 },
  progressPct: { color: T.textDim, fontSize: 12, fontWeight: "700" },
  cardFooter: { flexDirection: "row", alignItems: "center", gap: 10 },
  cardMetaStrong: { color: T.accent, fontSize: 12, fontWeight: "900" },
  cardMeta: { color: T.textDim, fontSize: 12, fontWeight: "700" },
  paidBadge: { flexDirection: "row", alignItems: "center", gap: 4 },
  paidBadgeText: { color: T.green, fontSize: 12, fontWeight: "700" },
  cardChevron: { color: T.textMuted, fontSize: 22 },
  empty: { alignItems: "center", paddingTop: 60, gap: 10 },
  emptyTitle: { color: T.text, fontSize: 16, fontWeight: "800" },
  emptySubtitle: { color: T.textDim, fontSize: 13 },
  errorText: { color: T.red, fontSize: 14, textAlign: "center", paddingHorizontal: 32 },
  retryBtn: { backgroundColor: T.accent, borderRadius: 8, paddingHorizontal: 24, paddingVertical: 10 },
  retryTxt: { color: T.onAccent, fontWeight: "700" },
  sheetOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0, 0, 0, 0.45)",
  },
  sheet: {
    backgroundColor: T.card,
    flex: 1,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderTopWidth: 1,
    borderTopColor: T.border,
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 22,
    gap: 10,
  },
  sheetScrollContent: { paddingBottom: 6 },
  sheetFormScroll: { flex: 1, minHeight: 0 },
  sheetHandle: {
    alignSelf: "center",
    width: 44,
    height: 4,
    borderRadius: 999,
    backgroundColor: T.border,
    marginBottom: 2,
  },
  sheetHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  sheetTitle: { color: T.text, fontWeight: "900", fontSize: 15 },
  sheetCloseBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.cardAlt,
    borderWidth: 1,
    borderColor: T.border,
  },
  dateSheetOverlay: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(0,0,0,0.45)" },
  dateSheetBackdrop: { ...StyleSheet.absoluteFillObject },
  dateSheetCard: {
    backgroundColor: T.card,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderTopWidth: 1,
    borderTopColor: T.border,
    paddingBottom: 18,
  },
  dateSheetHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: T.border,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  dateSheetTitle: { color: T.text, fontSize: 14, fontWeight: "800" },
  dateSheetCancel: { color: T.textDim, fontSize: 15, fontWeight: "700" },
  dateSheetDone: { color: T.accent, fontSize: 15, fontWeight: "800" },
});