import { StyleSheet } from "react-native";
import { T } from "@/lib/theme";
import { CARD_RADIUS, cardBase } from "@/lib/ui";

export const styles = StyleSheet.create({
  sheetOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0,0,0,0.25)",
  },
  sheet: {
    backgroundColor: T.card,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    paddingHorizontal: 16,
    paddingTop: 10,
    maxHeight: "92%",
  },
  sheetHandle: {
    alignSelf: "center",
    width: 46,
    height: 5,
    borderRadius: 3,
    backgroundColor: T.border,
    marginBottom: 10,
  },
  sheetTopBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    paddingBottom: 6,
  },
  sheetClosePlain: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.cardAlt,
    borderWidth: 1,
    borderColor: T.border,
  },
  sheetHero: {
    paddingTop: 6,
    paddingBottom: 8,
    alignItems: "center",
  },
  sheetAvatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.cardAlt,
    borderWidth: 1,
    borderColor: T.border,
    marginBottom: 10,
  },
  sheetAvatarLogo: {
    width: "100%",
    height: "100%",
  },
  sheetAvatarText: {
    color: T.text,
    fontSize: 20,
    fontWeight: "900",
    letterSpacing: -0.2,
  },
  sheetHeroName: {
    color: T.text,
    fontSize: 16,
    fontWeight: "800",
    textAlign: "center",
    letterSpacing: -0.2,
  },
  sheetHeroAmt: {
    marginTop: 6,
    color: T.text,
    fontSize: 38,
    fontWeight: "900",
    textAlign: "center",
    letterSpacing: -0.6,
  },
  sheetHeroSub: {
    marginTop: 6,
    color: T.textDim,
    fontSize: 13,
    fontWeight: "700",
    textAlign: "center",
  },
  sheetCard: {
    marginTop: 12,
    ...cardBase,
    backgroundColor: T.cardAlt,
    borderRadius: CARD_RADIUS,
    padding: 12,
  },
  sheetCardTitle: {
    marginBottom: 10,
    color: T.text,
    fontSize: 14,
    fontWeight: "900",
  },
  sheetCardRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 8,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: T.border,
  },
  sheetCardRowFirst: {
    borderTopWidth: 0,
    paddingTop: 0,
  },
  sheetCardLabel: { color: T.textDim, fontSize: 13, fontWeight: "800" },
  sheetCardValue: { color: T.text, fontSize: 13, fontWeight: "900" },
  sheetCardValueGood: { color: T.green },
  sheetCardValueWarn: { color: T.orange },
  sheetCardValueBad: { color: T.red },
  sheetCardHint: {
    marginTop: 8,
    color: T.textDim,
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 16,
  },
  sheetError: { color: T.red, fontSize: 13, fontWeight: "700" },
  sheetRetryBtn: {
    marginTop: 10,
    backgroundColor: T.accent,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 10,
    alignSelf: "flex-start",
  },
  sheetRetryText: { color: T.onAccent, fontWeight: "800" },
  sheetList: { paddingBottom: 18 },
  sheetEmpty: { color: T.textDim, fontSize: 13, fontStyle: "italic", paddingVertical: 12 },
  sheetPayRow: { flexDirection: "row", alignItems: "center", paddingVertical: 10 },
  sheetPayDate: { color: T.text, fontSize: 14, fontWeight: "800" },
  sheetPaySource: { color: T.textDim, fontSize: 12, fontWeight: "700", marginTop: 2 },
  sheetPayAmt: { color: T.text, fontSize: 14, fontWeight: "900" },
  sheetSep: { height: StyleSheet.hairlineWidth, backgroundColor: T.border },
});
