import { StyleSheet } from "react-native";

import { T } from "@/lib/theme";

export const styles = StyleSheet.create({
  balanceHero: {
    position: "relative",
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 28,
    paddingHorizontal: 20,
    paddingBottom: 34,
    marginTop: 0,
    marginHorizontal: -14,
    marginBottom: 2,
    gap: 8,
    backgroundColor: "rgba(20,24,38,0.56)",
    borderBottomLeftRadius: 34,
    borderBottomRightRadius: 34,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(124,92,255,0.16)",
    shadowColor: "#000000",
    shadowOpacity: 0.22,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 12 },
    elevation: 12,
  },
  heroGlow: {
    position: "absolute",
    borderRadius: 999,
  },
  heroGlowPrimary: {
    width: 260,
    height: 260,
    top: -126,
    right: -78,
    backgroundColor: "rgba(124,92,255,0.22)",
  },
  heroGlowSecondary: {
    width: 220,
    height: 220,
    bottom: -120,
    left: -84,
    backgroundColor: "rgba(68,126,255,0.16)",
  },
  heroInnerBorder: {
    ...StyleSheet.absoluteFillObject,
    borderBottomLeftRadius: 34,
    borderBottomRightRadius: 34,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.03)",
  },
  brandCircle: {
    width: 74,
    height: 74,
    borderRadius: 37,
    overflow: "hidden",
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  brandLogo: {
    width: "88%",
    height: "88%",
    borderRadius: 999,
  },
  brandLetter: {
    color: T.text,
    fontSize: 24,
    fontWeight: "900",
  },
  balanceHeroLabel: { color: "rgba(255,255,255,0.68)", fontSize: 13, fontWeight: "800", letterSpacing: 0.4 },
  balanceHeroValue: { color: "#ffffff", fontSize: 50, fontWeight: "900", letterSpacing: -1.1 },
  balanceHeroPctTxt: { fontSize: 15, fontWeight: "900" },
  balanceHeroPctTxtZero: { color: "rgba(255,255,255,0.62)" },
  balanceHeroPctTxtPositive: { color: T.green },
});
