import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  balanceHero: {
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 28,
    paddingHorizontal: 20,
    paddingBottom: 28,
    marginTop: 0,
    marginHorizontal: -14,
    marginBottom: 0,
    gap: 6,
    backgroundColor: "#080080",
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  brandCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    overflow: "hidden",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 6,
  },
  brandLogo: {
    width: "100%",
    height: "100%",
    borderRadius: 999,
  },
  brandLetter: {
    color: "#080080",
    fontSize: 18,
    fontWeight: "900",
  },
  balanceHeroLabel: { color: "rgba(255,255,255,0.72)", fontSize: 12, fontWeight: "800", letterSpacing: 0.4 },
  balanceHeroValue: { color: "#ffffff", fontSize: 40, fontWeight: "900", letterSpacing: -0.5 },
  balanceHeroPctTxt: { fontSize: 13, fontWeight: "800" },
  balanceHeroPctTxtZero: { color: "rgba(255,255,255,0.65)" },
  balanceHeroPctTxtPositive: { color: "#7fffc0" },
  heroPayBtn: {
    marginTop: 28,
    width: "100%",
    backgroundColor: "#ffffff",
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
  },
  heroPayBtnSmall: { marginTop: 18 },
  heroPayBtnTxt: { color: "#080080", fontSize: 15, fontWeight: "900" },
});
