import { StyleSheet } from "react-native";
import { T } from "@/lib/theme";

export const styles = StyleSheet.create({
  container: {
    backgroundColor: `${T.card}66`,
    borderBottomWidth: 1,
    borderBottomColor: `${T.accent}29`,
    borderBottomLeftRadius: 26,
    borderBottomRightRadius: 26,
    overflow: "hidden",
  },
  glassTint: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: `${T.accent}12`,
  },
  inner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    paddingVertical: 12,
    position: "relative",
  },
  centerWrap: {
    position: "absolute",
    left: 62,
    right: 70,
    alignItems: "center",
  },
  centerWrapWithThreeActions: {
    right: 138,
  },
  centerWrapWithTwoActions: {
    right: 96,
  },
  centerWrapWithOneAction: {
    right: 70,
  },
  centerWrapWithIncomeAction: {
    right: 122,
  },
  centerLabel: {
    color: T.text,
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 16,
    textAlign: "center",
  },

  avatarBtn: { position: "relative" },
  avatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: T.accent,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: T.border,
  },
  avatarInitial: { color: T.onAccent, fontSize: 14, fontWeight: "700" },
  rightActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  iconBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: `${T.cardAlt}66`,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: T.border,
    position: "relative",
  },
  addIncomeBtn: {
    minWidth: 90,
    height: 34,
    borderRadius: 17,
    backgroundColor: T.accent,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 4,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: T.accent,
    position: "relative",
  },
  addIncomeBtnText: {
    color: T.onAccent,
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  menuTriggerBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: `${T.cardAlt}4D`,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: `${T.border}B3`,
    position: "relative",
  },
  badge: {
    position: "absolute",
    top: -4,
    right: -4,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    paddingHorizontal: 4,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.red,
    borderWidth: 1,
    borderColor: T.card,
  },
  badgeText: {
    color: T.onAccent,
    fontSize: 9,
    fontWeight: "900",
  },
  notificationDot: {
    position: "absolute",
    top: 5,
    right: 7,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: T.red,
    borderWidth: 1,
    borderColor: T.card,
  },
  menuBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.25)",
  },
  menuCard: {
    position: "absolute",
    right: 18,
    width: 184,
    borderRadius: 14,
    backgroundColor: T.card,
    borderWidth: 1,
    borderColor: T.border,
    overflow: "hidden",
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: T.border,
  },
  menuItemLast: {
    borderBottomWidth: 0,
  },
  menuItemText: {
    color: T.text,
    fontSize: 14,
    fontWeight: "700",
  },
});
