import { StyleSheet } from "react-native";

import { T } from "@/lib/theme";

export const styles = StyleSheet.create({
  list: { paddingTop: 0, paddingBottom: 32 },
  card: {
    backgroundColor: "#141826",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.07)",
    padding: 16,
    marginBottom: 12,
    marginHorizontal: 14,
    shadowColor: "#000000",
    shadowOpacity: 0.16,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  row1: { flexDirection: "row", alignItems: "flex-start", gap: 10 },
  logoWrap: {
    width: 42,
    height: 42,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.07)",
    backgroundColor: "#1b2033",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 1,
    overflow: "hidden",
  },
  logoImg: { width: "100%", height: "100%", borderRadius: 999 },
  logoFallback: { color: T.textDim, fontSize: 13, fontWeight: "800" },
  nameCol: { flex: 1, minWidth: 0 },
  name: { color: T.text, fontSize: 16, fontWeight: "800", marginBottom: 6 },
  badgeRow: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  badge: { paddingHorizontal: 9, paddingVertical: 4, borderRadius: 999, borderWidth: 1 },
  badgeTxt: { fontSize: 11, fontWeight: "700" },
  rightCol: { alignItems: "flex-end", gap: 8, paddingLeft: 10 },
  row2: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 14,
    marginBottom: 8,
  },
  amount: { color: T.text, fontSize: 18, fontWeight: "900" },
  snapshotCol: { alignItems: "flex-end" },
  snapshotRow: { flexDirection: "row", alignItems: "center", justifyContent: "flex-end", flexWrap: "wrap", gap: 10 },
  snapshotTxt: { color: T.textDim, fontSize: 13, fontWeight: "700" },
  progressBg: { height: 10, borderRadius: 999, backgroundColor: "rgba(255,255,255,0.08)", overflow: "hidden" },
  progressFill: { height: 10, borderRadius: 999 },
});
