import { StyleSheet } from "react-native";
import { T } from "@/lib/theme";

export const styles = StyleSheet.create({
  wrap: { gap: 12 },
  summaryCard: {
    backgroundColor: T.card,
    borderWidth: 2,
    borderColor: T.accentBorder,
    borderRadius: 14,
    padding: 14,
  },
  summaryTitle: { color: T.textDim, fontSize: 12, fontWeight: "800" },
  summaryValue: { color: T.text, fontSize: 22, fontWeight: "900", marginTop: 4 },
  summarySub: { color: T.textMuted, fontSize: 12, marginTop: 4 },
  card: {
    backgroundColor: T.card,
    borderWidth: 2,
    borderColor: T.accentBorder,
    borderRadius: 14,
    padding: 14,
    gap: 8,
  },
  cardTitle: { color: T.text, fontSize: 14, fontWeight: "900", marginBottom: 2 },
  label: { color: T.textDim, fontSize: 12, fontWeight: "700", marginTop: 2 },
  input: {
    backgroundColor: T.cardAlt,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: T.border,
    color: T.text,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
  },
  saveBtn: {
    backgroundColor: T.accent,
    borderRadius: 10,
    alignItems: "center",
    paddingVertical: 11,
    marginTop: 6,
  },
  saveBtnTxt: { color: T.onAccent, fontSize: 14, fontWeight: "800" },
  customRow: { flexDirection: "row", gap: 10, alignItems: "flex-end" },
  customName: { color: T.text, fontSize: 13, fontWeight: "800", marginBottom: 6 },
  deleteBtn: {
    backgroundColor: `${T.red}22`,
    borderWidth: 1,
    borderColor: `${T.red}66`,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  deleteTxt: { color: T.red, fontSize: 12, fontWeight: "800" },
  typeRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  typePill: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.cardAlt,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  typePillActive: { borderColor: T.accent, backgroundColor: `${T.accent}22` },
  typeTxt: { color: T.textDim, fontSize: 12, fontWeight: "700" },
  typeTxtActive: { color: T.accent, fontWeight: "800" },
  empty: { color: T.textMuted, fontSize: 12, fontWeight: "600" },
  disabled: { opacity: 0.5 },
});
