import { StyleSheet } from "react-native";
import { T } from "@/lib/theme";

export const styles = StyleSheet.create({
  sectionTitle: { color: T.text, fontSize: 14, fontWeight: "900" },
  inputLabel: { color: T.textDim, fontSize: 12, fontWeight: "800" },
  sheetOverlay: { flex: 1, justifyContent: "flex-end" },
  sheetBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(0,0,0,0.55)" },
  paySheetCard: {
    backgroundColor: T.card,
    height: "78%",
    position: "relative",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderTopWidth: 1,
    borderTopColor: T.border,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 142,
    gap: 16,
  },
  sheetHandle: { width: 40, height: 4, borderRadius: 2, alignSelf: "center", backgroundColor: T.border },
  bottomActions: {
    position: "absolute",
    left: 16,
    right: 16,
    bottom: 0,
    gap: 10,
    paddingTop: 10,
    backgroundColor: "transparent",
  },
  sheetActions: { flexDirection: "row", gap: 12 },
  actionBtn: { flex: 1 },
  disabled: { opacity: 0.5 },
  payInputGroup: { gap: 10, marginTop: 10 },
  markPaidBtn: {
    marginTop: 2,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: `${T.green}88`,
    backgroundColor: `${T.green}22`,
    paddingVertical: 12,
    alignItems: "center",
  },
  markPaidBtnTxt: { color: T.green, fontSize: 14, fontWeight: "800" },
});
