import { StyleSheet } from "react-native";

import { T } from "@/lib/theme";

export const EXPENSE_HERO_BLUE = "#080080";

export const expenseDetailStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: EXPENSE_HERO_BLUE },
  center: { flex: 1, justifyContent: "center", alignItems: "center", gap: 12 },
  errorText: { color: T.red, fontSize: 14, textAlign: "center", paddingHorizontal: 32 },
  retryBtn: { backgroundColor: T.accent, borderRadius: 8, paddingHorizontal: 24, paddingVertical: 10 },
  retryTxt: { color: T.onAccent, fontWeight: "700" },
  header: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 30,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingBottom: 12,
    backgroundColor: "transparent",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(255,255,255,0.12)",
    overflow: "hidden",
  },
  headerGlassTint: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(8,0,128,0.18)",
  },
  backBtn: { paddingHorizontal: 6, paddingVertical: 4 },
  scroll: { paddingHorizontal: 14, paddingTop: 0, gap: 14 },
  hero: {
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 18,
    paddingHorizontal: 20,
    paddingBottom: 24,
    marginTop: 0,
    marginHorizontal: -14,
    gap: 6,
    backgroundColor: EXPENSE_HERO_BLUE,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  heroTopRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  heroLabel: { color: "rgba(255,255,255,0.72)", fontSize: 12, fontWeight: "800", letterSpacing: 0.4 },
  brandCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    overflow: "hidden",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 6,
  },
  brandLogo: {
    width: "100%",
    height: "100%",
    borderRadius: 999,
  },
  brandLetter: {
    color: EXPENSE_HERO_BLUE,
    fontSize: 18,
    fontWeight: "900",
  },
  heroBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: "rgba(110,231,160,0.12)",
    borderWidth: 1,
    borderColor: "rgba(110,231,160,0.26)",
  },
  heroBadgeTxt: { color: "#6ee7a0", fontSize: 11, fontWeight: "800" },
  heroAmount: { color: "#ffffff", fontSize: 48, fontWeight: "900", letterSpacing: -1, marginBottom: 4 },
  heroAmountEditWrap: { width: "100%", paddingHorizontal: 8, marginBottom: 4 },
  heroAmountInput: {
    color: "#ffffff",
    fontSize: 48,
    fontWeight: "900",
    letterSpacing: -1,
    paddingVertical: 0,
  },
  heroName: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "900",
    textAlign: "center",
    marginBottom: 6,
    paddingHorizontal: 16,
  },
  heroNameInput: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "900",
    textAlign: "center",
    marginBottom: 6,
    paddingHorizontal: 16,
    paddingVertical: 0,
  },
  heroUpdated: { color: "rgba(255,255,255,0.72)", fontSize: 12, fontWeight: "500", marginBottom: 18 },
  heroDueBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    borderWidth: 1,
    marginBottom: 10,
  },
  heroDueTxt: { color: "#ffffff", fontSize: 12, fontWeight: "800" },
  heroCards: { flexDirection: "row", gap: 10, justifyContent: "center" },
  heroCard: {
    width: 140,
    height: 80,
    backgroundColor: "#03045E",
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  heroCardLbl: { color: "rgba(255,255,255,0.65)", fontSize: 11, fontWeight: "700", marginBottom: 5 },
  heroCardVal: { fontSize: 16, fontWeight: "900" },
  quickRow: { marginTop: 28, width: "100%", flexDirection: "row", gap: 10 },
  quickBtn: { flex: 1, borderRadius: 12, paddingVertical: 14, alignItems: "center" },
  quickBtnPrimary: { backgroundColor: "#ffffff" },
  quickBtnSecondary: { borderWidth: 1, borderColor: "rgba(255,255,255,0.35)", backgroundColor: "rgba(255,255,255,0.1)" },
  quickPrimaryTxt: { color: EXPENSE_HERO_BLUE, fontSize: 15, fontWeight: "900" },
  quickSecondaryTxt: { color: "#ffffff", fontSize: 15, fontWeight: "900" },
  quickDisabled: { opacity: 0.55 },
  statusGraceNote: {
    width: "100%",
    textAlign: "center",
    color: "rgba(255,255,255,0.72)",
    fontSize: 12,
    fontWeight: "500",
    marginBottom: 4,
  },
  lockedHint: {
    marginTop: 10,
    color: "rgba(255,255,255,0.72)",
    fontSize: 12,
    fontWeight: "600",
    textAlign: "center",
  },
  aiCard: {
    backgroundColor: "#03045E",
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: T.border,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  aiTitleRow: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 6 },
  aiTitle: { color: T.text, fontSize: 13, fontWeight: "900", letterSpacing: 0.2 },
  aiText: { color: T.textDim, fontSize: 13, fontWeight: "600", lineHeight: 18 },
  freqCard: {
    backgroundColor: "#03045E",
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: T.border,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  freqHeadRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  freqHeadRight: { flexDirection: "row", alignItems: "center", gap: 10 },
  freqIndicatorTxt: { fontSize: 12, fontWeight: "900", letterSpacing: 0.2 },
  freqTitle: { color: T.text, fontSize: 13, fontWeight: "900", letterSpacing: 0.2 },
  freqSub: { color: T.textDim, fontSize: 12, fontWeight: "700", marginTop: 4, marginBottom: 10 },
  sparkWrap: { width: "100%", alignItems: "center" },
  sparkLabels: { width: "100%", flexDirection: "row", justifyContent: "space-between", marginTop: 6 },
  sparkLbl: { color: T.textMuted, fontSize: 11, fontWeight: "800" },
  sparkStatuses: { width: "100%", flexDirection: "row", justifyContent: "space-between", marginTop: 2 },
  sparkStatus: { fontSize: 10, fontWeight: "900" },
  freqEmptyState: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 4,
    borderRadius: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: T.border,
    backgroundColor: "rgba(255,255,255,0.03)",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  freqEmptyText: { color: T.textDim, fontSize: 12, fontWeight: "700", lineHeight: 18 },
  freqBarsRow: { flexDirection: "row", gap: 10, justifyContent: "space-between" },
  freqBarCol: { alignItems: "center", justifyContent: "flex-end", flex: 1 },
  freqBarTrack: {
    height: 36,
    width: "100%",
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
    overflow: "hidden",
    justifyContent: "flex-end",
  },
  freqBarFill: { width: "100%", borderRadius: 10 },
  freqBarLbl: { color: T.textMuted, fontSize: 11, fontWeight: "800", marginTop: 6 },
  bottomActionsWrap: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 14,
    paddingTop: 12,
    backgroundColor: "transparent",
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "rgba(255,255,255,0.18)",
    overflow: "hidden",
  },
  bottomGlassTint: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(8,0,128,0.16)",
  },
  bottomActionsRow: { flexDirection: "row", gap: 12 },
  bottomActionBtn: {
    flex: 1,
    backgroundColor: "#ffffff",
    borderRadius: 999,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  bottomActionTxt: { fontSize: 14, fontWeight: "900", letterSpacing: 0.2 },
  dateModalOverlay: { ...StyleSheet.absoluteFillObject, justifyContent: "flex-end" },
  dateModalBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(0,0,0,0.55)" },
  dateModalSheet: {
    backgroundColor: T.card,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderTopWidth: 1,
    borderTopColor: T.border,
    paddingBottom: 16,
    overflow: "hidden",
  },
  dateModalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: T.border,
  },
  dateModalCancelTxt: { color: T.textDim, fontSize: 14, fontWeight: "800" },
  dateModalClearTxt: { color: T.red, fontSize: 14, fontWeight: "800" },
  dateModalDoneTxt: { color: T.accent, fontSize: 14, fontWeight: "900" },
});