import { Dimensions, StyleSheet } from "react-native";
import { T } from "@/lib/theme";
import { cardElevated, flatInput, flatInputLabel } from "@/lib/ui";

const { height: SCREEN_H } = Dimensions.get("window");

export const styles = StyleSheet.create({
  sectionTitle: { color: T.text, fontSize: 21, fontWeight: "900", letterSpacing: -0.3 },
  sectionEyebrow: { color: T.textMuted, fontSize: 11, fontWeight: "800", textTransform: "uppercase", letterSpacing: 0.8, marginBottom: 4 },
  inputLabel: { ...flatInputLabel, color: "rgba(244,246,255,0.66)" },
  sheetOverlay: { flex: 1, justifyContent: "flex-end" },
  sheetBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(0,0,0,0.62)" },
  dateModalOverlay: { flex: 1, justifyContent: "flex-end" },
  dateModalBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(0,0,0,0.55)" },
  dateModalSheet: {
    backgroundColor: T.card,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderTopWidth: 1,
    borderTopColor: T.border,
    paddingBottom: 16,
    overflow: "hidden",
  },
  dateModalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: T.border,
  },
  dateModalCancelTxt: { color: T.textDim, fontSize: 14, fontWeight: "700" },
  dateModalDoneTxt: { color: T.accent, fontSize: 14, fontWeight: "800" },
  sheetCard: {
    backgroundColor: T.bg,
    height: SCREEN_H * 0.925,
    position: "relative",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    borderWidth: 1,
    borderBottomWidth: 0,
    borderColor: T.border,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 150,
    overflow: "hidden",
    shadowColor: "#000000",
    shadowOpacity: 0.34,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: -10 },
    elevation: 24,
    gap: 0,
  },
  sheetScroll: { flex: 1, minHeight: 0 },
  sheetScrollContent: { paddingTop: 6, paddingBottom: 24, gap: 16 },
  sheetHandle: { width: 48, height: 5, borderRadius: 999, alignSelf: "center", backgroundColor: T.border, marginBottom: 6 },
  // Section cards are now flat — just spacing containers
  sectionCard: {
    gap: 16,
    paddingTop: 4,
  },
  sectionCardUnderlay: { zIndex: 1 },
  formGroup: { gap: 8 },
  formCol: { flex: 1 },
  formRow: { flexDirection: "row", gap: 12, marginBottom: 2 },
  input: { ...flatInput },
  helperText: { color: T.textMuted, fontSize: 11, lineHeight: 15 },
  dateValue: { color: T.text, fontSize: 14 },
  dateValuePlaceholder: { color: T.textMuted },
  dateDoneBtn: { marginTop: 8 },
  sourceRow: { flexDirection: "row", gap: 8, marginTop: 4 },
  sourceBtn: {
    flex: 1,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.cardAlt,
    borderRadius: 8,
    paddingVertical: 9,
    alignItems: "center",
  },
  sourceBtnActive: { borderColor: T.accent, backgroundColor: `${T.accent}2A` },
  sourceBtnText: { color: T.textDim, fontSize: 12, fontWeight: "700" },
  sourceBtnTextActive: { color: T.accent, fontWeight: "800" },
  dropdownAnchor: { position: "relative", zIndex: 20 },
  dropdownAnchorActive: { zIndex: 80 },
  dropdownValueRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  dropdownChevron: { color: T.textDim, fontSize: 11, fontWeight: "800" },
  dropdownMenu: {
    ...cardElevated,
    position: "absolute",
    top: 64,
    left: 0,
    right: 0,
    borderWidth: 1,
    borderColor: "rgba(244,246,255,0.08)",
    borderRadius: 18,
    overflow: "hidden",
    backgroundColor: T.cardAlt,
    zIndex: 30,
    elevation: 8,
    maxHeight: 240,
  },
  primaryDropdownMenu: { zIndex: 90, elevation: 12 },
  dropdownItem: {
    paddingHorizontal: 16,
    paddingVertical: 13,
    borderBottomWidth: 1,
    borderBottomColor: T.border,
  },
  dropdownItemLast: { borderBottomWidth: 0 },
  dropdownItemActive: { backgroundColor: `${T.accent}14` },
  dropdownItemText: { color: T.text, fontSize: 14, fontWeight: "700" },
  dropdownItemTextActive: { color: T.accent, fontWeight: "800" },
  cardPickerWrap: { gap: 8, marginTop: 4 },
  cardPickBtn: {
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: 8,
    backgroundColor: T.cardAlt,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  cardPickBtnActive: { borderColor: T.accent, backgroundColor: `${T.accent}2A` },
  cardPickTxt: { color: T.text, fontSize: 13, fontWeight: "700" },
  cardPickTxtActive: { color: T.accent, fontWeight: "800" },
  noCardsText: { color: T.textDim, fontSize: 12, fontWeight: "700", marginTop: 4 },
  installmentRow: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginTop: 4 },
  installmentChip: { borderWidth: 1, borderColor: T.border, backgroundColor: T.cardAlt, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 8 },
  installmentChipActive: { borderColor: T.accent, backgroundColor: `${T.accent}2A` },
  installmentChipText: { color: T.textDim, fontSize: 12, fontWeight: "700" },
  installmentChipTextActive: { color: T.accent, fontWeight: "800" },
  toggleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 0,
    paddingVertical: 16,
    gap: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(244,246,255,0.08)",
  },
  toggleInfo: { flex: 1 },
  toggleTitle: { color: T.text, fontSize: 15, fontWeight: "800" },
  toggleSub: { color: T.textMuted, fontSize: 12, fontWeight: "600", marginTop: 4, lineHeight: 16 },
  toggleControl: {
    width: 52,
    height: 30,
    borderRadius: 15,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(244,246,255,0.10)",
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  toggleControlOn: {
    backgroundColor: `${T.accent}24`,
    borderColor: `${T.accent}88`,
  },
  toggleThumb: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "rgba(244,246,255,0.46)",
    alignSelf: "flex-start",
  },
  toggleThumbOn: {
    backgroundColor: T.accent,
    alignSelf: "flex-end",
    shadowColor: T.accent,
    shadowOpacity: 0.35,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  sectionDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: "rgba(244,246,255,0.08)",
    marginTop: 4,
  },
  bottomActions: {
    position: "absolute",
    left: 20,
    right: 20,
    bottom: 0,
    paddingTop: 10,
    backgroundColor: "transparent",
  },
  sheetActions: { flexDirection: "row", gap: 12 },
  actionBtn: { flex: 1 },
  disabled: { opacity: 0.5 },
});
