import { StyleSheet } from "react-native";
import { T } from "@/lib/theme";

export const styles = StyleSheet.create({
  sectionTitle: { color: T.text, fontSize: 14, fontWeight: "900" },
  inputLabel: { color: T.textDim, fontSize: 12, fontWeight: "800" },
  sheetOverlay: { flex: 1, justifyContent: "flex-end" },
  sheetBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(0,0,0,0.55)" },
  dateModalOverlay: { flex: 1, justifyContent: "flex-end" },
  dateModalBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(0,0,0,0.55)" },
  dateModalSheet: {
    backgroundColor: T.card,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderTopWidth: 1,
    borderTopColor: T.border,
    paddingBottom: 16,
    overflow: "hidden",
  },
  dateModalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: T.border,
  },
  dateModalCancelTxt: { color: T.textDim, fontSize: 14, fontWeight: "700" },
  dateModalDoneTxt: { color: T.accent, fontSize: 14, fontWeight: "800" },
  sheetCard: { backgroundColor: T.card, height: "88%", borderTopLeftRadius: 20, borderTopRightRadius: 20, borderTopWidth: 1, borderTopColor: T.border, paddingHorizontal: 16, paddingTop: 12, paddingBottom: 20, gap: 14 },
  sheetScroll: { flex: 1, minHeight: 0 },
  sheetScrollContent: { gap: 10, paddingBottom: 8, flexGrow: 1 },
  sheetHandle: { width: 40, height: 4, borderRadius: 2, alignSelf: "center", backgroundColor: T.border },
  formGroup: { gap: 8 },
  formCol: { flex: 1 },
  formRow: { flexDirection: "row", gap: 12, marginBottom: 2 },
  input: { backgroundColor: T.cardAlt, borderRadius: 8, paddingHorizontal: 12, paddingVertical: 12, color: T.text, fontSize: 14, borderWidth: 1, borderColor: T.border },
  dateValue: { color: T.text, fontSize: 14 },
  dateValuePlaceholder: { color: T.textMuted },
  dateDoneBtn: { marginTop: 8 },
  sourceRow: { flexDirection: "row", gap: 8, marginTop: 4 },
  sourceBtn: {
    flex: 1,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.cardAlt,
    borderRadius: 8,
    paddingVertical: 9,
    alignItems: "center",
  },
  sourceBtnActive: { borderColor: T.accent, backgroundColor: `${T.accent}2A` },
  sourceBtnText: { color: T.textDim, fontSize: 12, fontWeight: "700" },
  sourceBtnTextActive: { color: T.accent, fontWeight: "800" },
  dropdownAnchor: { position: "relative", zIndex: 20 },
  dropdownValueRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  dropdownChevron: { color: T.textDim, fontSize: 11, fontWeight: "800" },
  dropdownMenu: {
    position: "absolute",
    top: 46,
    left: 0,
    right: 0,
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: T.cardAlt,
    zIndex: 30,
    elevation: 8,
  },
  dropdownItem: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: T.border,
  },
  dropdownItemLast: { borderBottomWidth: 0 },
  dropdownItemActive: { backgroundColor: `${T.accent}20` },
  dropdownItemText: { color: T.text, fontSize: 13, fontWeight: "700" },
  dropdownItemTextActive: { color: T.accent, fontWeight: "800" },
  cardPickerWrap: { gap: 8, marginTop: 6 },
  cardPickBtn: {
    borderWidth: 1,
    borderColor: T.border,
    borderRadius: 8,
    backgroundColor: T.cardAlt,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  cardPickBtnActive: { borderColor: T.accent, backgroundColor: `${T.accent}2A` },
  cardPickTxt: { color: T.text, fontSize: 13, fontWeight: "700" },
  cardPickTxtActive: { color: T.accent, fontWeight: "800" },
  noCardsText: { color: T.textDim, fontSize: 12, fontWeight: "700", marginTop: 4 },
  installmentRow: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginTop: 8, marginBottom: 10 },
  installmentChip: { borderWidth: 1, borderColor: T.border, backgroundColor: T.cardAlt, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 6 },
  installmentChipActive: { borderColor: T.accent, backgroundColor: `${T.accent}2A` },
  installmentChipText: { color: T.textDim, fontSize: 12, fontWeight: "700" },
  installmentChipTextActive: { color: T.accent, fontWeight: "800" },
  sheetActions: { flexDirection: "row", gap: 10, marginTop: 14 },
  cancelBtn: { backgroundColor: T.cardAlt, borderRadius: 8, paddingVertical: 11, alignItems: "center", flex: 1 },
  cancelBtnTxt: { color: T.textDim, fontWeight: "700", fontSize: 14 },
  saveBtn: { backgroundColor: T.accent, borderRadius: 8, paddingVertical: 11, alignItems: "center" },
  saveBtnFlex: { flex: 1 },
  saveBtnTxt: { color: T.onAccent, fontWeight: "700", fontSize: 14 },
  disabled: { opacity: 0.5 },
});
