import { Dimensions, StyleSheet } from "react-native";

import { T } from "@/lib/theme";
import { cardElevated, textLabel } from "@/lib/ui";

const screenWidth = Dimensions.get("window").width;

export const GOAL_GAP = 12;
export const GOAL_SIDE = 16;
export const GOAL_CARD = Math.max(122, Math.round((screenWidth - GOAL_SIDE * 2 - GOAL_GAP) / 2));

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: T.bg },
  center: { flex: 1, justifyContent: "center", alignItems: "center", gap: 12 },
  loadingText: { color: T.textDim, marginTop: 12, fontSize: 14 },
  errorText: { color: T.red, marginTop: 12, fontSize: 15, textAlign: "center", paddingHorizontal: 32 },
  retryBtn: { marginTop: 16, backgroundColor: T.accent, borderRadius: 10, paddingHorizontal: 28, paddingVertical: 12 },
  retryText: { color: T.onAccent, fontWeight: "700" },
  scroll: { padding: 16, paddingBottom: 140 },
  section: {
    ...cardElevated,
    padding: 16,
    marginTop: 12,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  sectionTitle: {
    ...textLabel,
    fontWeight: "800",
    marginBottom: 10,
  },
  currentPeriodBadge: {
    alignSelf: "flex-start",
    backgroundColor: T.accentDim,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginBottom: 10,
  },
  currentPeriodBadgeText: {
    color: T.text,
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  alertCard: {
    ...cardElevated,
    marginTop: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: T.red,
  },
  alertTitle: { color: T.red, fontSize: 16, fontWeight: "900" },
  alertText: { color: T.textDim, fontSize: 13, fontWeight: "700", marginTop: 6, lineHeight: 18 },
  setupCard: {
    ...cardElevated,
    marginTop: 12,
    padding: 14,
    gap: 8,
  },
  setupTitle: { color: T.text, fontSize: 16, fontWeight: "900" },
  setupText: { color: T.textDim, fontSize: 13, fontWeight: "600", lineHeight: 18 },
  setupActions: { flexDirection: "row", gap: 10, marginTop: 4 },
  setupBtn: {
    flex: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.cardAlt,
    paddingVertical: 10,
    alignItems: "center",
  },
  setupBtnText: { color: T.accent, fontSize: 12, fontWeight: "900" },
  seeAllText: { color: T.accent, fontSize: 14, fontWeight: "900" },
  emptyUpcomingText: {
    color: T.textDim,
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 20,
  },
  sheetOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.35)",
    justifyContent: "flex-end",
  },
  sheet: {
    backgroundColor: T.cardAlt,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    paddingTop: 8,
    maxHeight: "82%",
  },
  sheetHandle: {
    alignSelf: "center",
    width: 48,
    height: 5,
    borderRadius: 999,
    backgroundColor: T.textMuted,
    marginBottom: 10,
  },
  sheetHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingBottom: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: T.border,
  },
  sheetTitle: { color: T.text, fontSize: 18, fontWeight: "900", flex: 1 },
  sheetCloseBtn: { marginLeft: 12 },
  sheetList: { paddingHorizontal: 16, paddingBottom: 24 },
  sheetEmpty: { color: T.textDim, fontSize: 13, fontStyle: "italic", paddingVertical: 12 },
  sheetRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: T.border,
  },
  sheetRowName: { color: T.text, fontSize: 14, fontWeight: "800" },
  sheetRowSub: { color: T.textDim, fontSize: 12, fontWeight: "700", marginTop: 2 },
  sheetRowAmt: { color: T.text, fontSize: 16, fontWeight: "900" },
  aiTipsCard: {
    ...cardElevated,
    marginTop: 12,
    padding: 16,
    gap: 14,
  },
  aiTipsHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  aiTipsTitleWrap: {
    flex: 1,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  aiTipsIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: T.accentDim,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 1,
  },
  aiTipsTitle: {
    color: T.text,
    fontSize: 16,
    fontWeight: "900",
    letterSpacing: -0.2,
  },
  aiTipsBody: {
    borderRadius: 16,
    backgroundColor: T.cardAlt,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: T.border,
    padding: 14,
    gap: 8,
  },
  aiTipsMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  aiTipHeadline: {
    flex: 1,
    color: T.text,
    fontSize: 15,
    fontWeight: "900",
    letterSpacing: -0.2,
  },
  aiTipPriority: {
    color: T.accent,
    fontSize: 11,
    fontWeight: "900",
    backgroundColor: T.accentDim,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    overflow: "hidden",
  },
  aiTipDetail: {
    color: T.textDim,
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 20,
  },
  aiTipsDots: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  aiTipsDot: {
    width: 7,
    height: 7,
    borderRadius: 999,
    backgroundColor: T.border,
  },
  aiTipsDotActive: {
    width: 18,
    backgroundColor: T.accent,
  },
  lightRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: T.border,
    gap: 12,
  },
  lightLeft: { flexDirection: "row", alignItems: "center", flex: 1, gap: 12 },
  lightAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    overflow: "hidden",
    backgroundColor: T.cardAlt,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: T.border,
    alignItems: "center",
    justifyContent: "center",
  },
  lightAvatarTxt: { color: T.text, fontSize: 14, fontWeight: "800" },
  avatarLogo: {
    width: "100%",
    height: "100%",
    borderRadius: 999,
  },
  lightRowTitle: { color: T.text, fontSize: 16, fontWeight: "800", letterSpacing: -0.2 },
  lightRowSub: { color: T.textDim, fontSize: 13, fontWeight: "600", marginTop: 2 },
  lightRowAmt: { color: T.text, fontSize: 18, fontWeight: "800", letterSpacing: -0.2 },
  blueSection: {
    backgroundColor: T.cardAlt,
    borderColor: T.border,
  },
  blueSectionTitle: {
    color: T.textDim,
  },
  blueRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: T.border,
    gap: 14,
  },
  blueLeft: { flexDirection: "row", alignItems: "center", flex: 1, gap: 14 },
  blueAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    overflow: "hidden",
    backgroundColor: T.accentDim,
    alignItems: "center",
    justifyContent: "center",
  },
  blueAvatarTxt: { color: T.accent, fontSize: 14, fontWeight: "800" },
  blueRowTitle: { color: T.text, fontSize: 16, fontWeight: "800", letterSpacing: -0.2 },
  blueRowSub: { color: T.textDim, fontSize: 13, fontWeight: "600", marginTop: 2 },
  blueRowAmt: { color: T.text, fontSize: 18, fontWeight: "800", letterSpacing: -0.2 },
  recapWrap: { marginTop: 12, marginBottom: 4 },
  recapBadge: {
    alignSelf: "flex-start",
    backgroundColor: T.accentDim,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginBottom: 12,
  },
  recapBadgeText: {
    color: T.text,
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: 0.2,
  },
  recapGrid: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 12,
  },
  recapStatCard: {
    flex: 1,
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 4,
  },
  recapPaidCard: {
    backgroundColor: `${T.green}1A`,
    borderColor: `${T.green}55`,
  },
  recapMissedCard: {
    backgroundColor: T.cardAlt,
    borderColor: T.border,
  },
  recapStatLabel: {
    color: T.textDim,
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  recapStatCount: {
    color: T.text,
    fontSize: 24,
    fontWeight: "900",
    letterSpacing: -0.3,
  },
  recapStatAmount: {
    color: T.text,
    fontSize: 17,
    fontWeight: "800",
  },
  recapMissedTitle: {
    color: T.textDim,
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  recapMissedCount: {
    marginTop: 4,
    color: T.text,
    fontSize: 24,
    fontWeight: "900",
    letterSpacing: -0.3,
  },
  recapMissedAmount: {
    marginTop: 4,
    color: T.text,
    fontSize: 17,
    fontWeight: "800",
  },
  goalsWrap: { marginTop: 12, marginHorizontal: -16 },
  goalsHeaderRow: {
    paddingHorizontal: GOAL_SIDE,
    marginBottom: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  seeAllGoalsText: {
    color: T.accent,
    fontSize: 13,
    fontWeight: "900",
  },
  goalsProjectionTitle: {
    color: T.accent,
    fontSize: 12,
    fontWeight: "900",
  },
  goalCard: {
    width: GOAL_CARD,
    height: GOAL_CARD,
    ...cardElevated,
    padding: 14,
    justifyContent: "space-between",
  },
  goalHeaderRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  goalHeaderLeft: { flexDirection: "row", alignItems: "center", flex: 1, minWidth: 0, gap: 10 },
  goalChip: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: T.accentDim,
    alignItems: "center",
    justifyContent: "center",
  },
  goalTitle: {
    color: T.text,
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "600",
    letterSpacing: -0.2,
    flex: 1,
    flexShrink: 1,
    minWidth: 0,
  },
  goalMainBlock: { flex: 1, justifyContent: "center" },
  goalPrimaryAmt: {
    marginTop: 10,
    color: T.text,
    fontSize: 22,
    fontWeight: "900",
    letterSpacing: -0.4,
  },
  goalAmountLine: {
    marginTop: 2,
    color: T.textDim,
    fontSize: 11,
    fontWeight: "400",
  },
  goalPctRow: { marginTop: 8, flexDirection: "row", alignItems: "center", justifyContent: "flex-start" },
  goalPctPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: T.accentDim,
  },
  goalPctText: { color: T.accent, fontSize: 11, fontWeight: "700" },
  goalBarBg: {
    height: 12,
    borderRadius: 999,
    backgroundColor: T.border,
    overflow: "hidden",
    marginTop: 10,
    marginBottom: 8,
  },
  goalBarFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: T.accent,
  },
  goalIndicatorWrap: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 10,
    gap: 6,
  },
  goalIndicatorDot: {
    height: 4,
    width: 6,
    borderRadius: 999,
    backgroundColor: T.textMuted,
  },
  goalIndicatorDotActive: {
    width: 18,
    backgroundColor: T.accent,
  },
});