import { StyleSheet } from "react-native";

import { T } from "@/lib/theme";

export const expensesStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: T.bg },
  center: { flex: 1, justifyContent: "center", alignItems: "center", gap: 12 },
  scrollContent: { paddingBottom: 140 },
  errorText: { color: "#e25c5c", fontSize: 14, textAlign: "center", paddingHorizontal: 32 },
  retryBtn: { backgroundColor: T.accent, borderRadius: 8, paddingHorizontal: 24, paddingVertical: 10 },
  retryTxt: { color: T.onAccent, fontWeight: "700" },
  actionCard: {
    marginHorizontal: 12,
    marginTop: 10,
    marginBottom: 2,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.card,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  actionCopy: { flex: 1 },
  actionTitle: { color: T.text, fontSize: 14, fontWeight: "900" },
  actionText: { marginTop: 2, color: T.textDim, fontSize: 12, fontWeight: "700" },
  actionBtn: {
    minWidth: 84,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: T.accent,
  },
  actionBtnText: { color: T.onAccent, fontSize: 13, fontWeight: "800" },
  planCardsWrap: {
    marginTop: 16,
    marginBottom: 8,
    paddingHorizontal: 12,
  },
  planTabsBg: {
    backgroundColor: "transparent",
  },
  planTabsScroll: {
    flexGrow: 1,
    paddingHorizontal: 2,
    gap: 10,
  },
  planPill: {
    width: 118,
    minHeight: 106,
    borderRadius: 20,
    backgroundColor: "rgba(20,24,38,0.56)",
    borderWidth: 1,
    borderColor: "rgba(244,246,255,0.16)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 12,
    position: "relative",
    overflow: "hidden",
  },
  planPillSelected: {
    backgroundColor: "rgba(124,92,255,0.24)",
    borderColor: "rgba(124,92,255,0.44)",
  },
  planPillText: {
    color: T.text,
    fontWeight: "800",
    fontSize: 14,
    textAlign: "center",
    marginTop: 8,
  },
  planPillTextSelected: {
    color: T.text,
  },
  planPillMeta: {
    marginTop: 3,
    color: T.textDim,
    fontWeight: "700",
    fontSize: 11,
    textAlign: "center",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  planPillMetaSelected: {
    color: "rgba(255,255,255,0.88)",
  },
  planPillCheck: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(244,246,255,0.28)",
    backgroundColor: "rgba(20,24,38,0.42)",
    alignItems: "center",
    justifyContent: "center",
  },
  planPillCheckSelected: {
    borderColor: "rgba(124,92,255,0.9)",
    backgroundColor: "rgba(124,92,255,0.92)",
  },
  noExpensesCard: {
    marginHorizontal: 14,
    marginTop: 12,
    backgroundColor: "rgba(20,24,38,0.56)",
    borderRadius: 24,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(244,246,255,0.16)",
    shadowColor: "#000000",
    shadowOpacity: 0.3,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 14 },
    elevation: 12,
  },
  noExpensesCardRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  noExpensesCardCopy: { flex: 1 },
  noExpensesAddBtn: {
    height: 40,
    borderRadius: 20,
    backgroundColor: T.accent,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 6,
    flexShrink: 0,
    shadowColor: T.accent,
    shadowOpacity: 0.28,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  noExpensesAddBtnTxt: {
    color: T.onAccent,
    fontSize: 13,
    fontWeight: "800",
  },
  noExpensesTitle: {
    color: T.text,
    fontWeight: "900",
    fontSize: 14,
  },
  noExpensesSub: {
    marginTop: 4,
    color: T.textDim,
    fontWeight: "700",
    fontSize: 12,
  },
  noExpensesHint: {
    marginTop: 6,
    color: T.textMuted,
    fontWeight: "600",
    fontSize: 12,
  },
  planTotalLabelWrap: {
    marginHorizontal: 12,
    marginTop: 12,
    marginBottom: 4,
  },
  planTotalLabelText: {
    color: T.textDim,
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  planTotalLabelSub: {
    marginTop: 3,
    color: T.textMuted,
    fontSize: 12,
    fontWeight: "600",
  },
  monthCardsWrap: {
    paddingHorizontal: 14,
    paddingTop: 10,
    gap: 10,
  },
  sectionHeadingWrap: {
    paddingHorizontal: 14,
    paddingTop: 14,
  },
  sectionHeading: {
    color: T.textDim,
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0.8,
  },
  monthCard: {
    backgroundColor: "rgba(20,24,38,0.56)",
    borderWidth: 1,
    borderColor: "rgba(244,246,255,0.16)",
    borderRadius: 22,
    padding: 16,
    shadowColor: "#000000",
    shadowOpacity: 0.3,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 14 },
    elevation: 12,
  },
  monthCardRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  monthCardTitle: {
    color: T.text,
    fontWeight: "900",
    fontSize: 14,
    flexShrink: 1,
  },
  monthCardAmount: {
    color: T.text,
    fontWeight: "900",
    fontSize: 14,
  },
  monthCardMeta: {
    marginTop: 6,
    color: T.textDim,
    fontWeight: "700",
    fontSize: 12,
  },
  purpleHero: {
    backgroundColor: "transparent",
    paddingHorizontal: 20,
    paddingBottom: 12,
    alignItems: "center",
    overflow: "hidden",
  },
  heroBadge: {
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 12,
    paddingVertical: 7,
    marginBottom: 14,
  },
  heroBadgeText: {
    color: T.accent,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  purpleHeroLabelBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginBottom: 6,
  },
  purpleHeroLabel: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 15,
    fontWeight: "700",
    letterSpacing: 0.4,
  },
  purpleHeroAmount: {
    color: "#ffffff",
    fontSize: 52,
    fontWeight: "900",
    letterSpacing: -1,
    marginTop: 4,
  },
  purpleHeroMeta: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 16,
    fontWeight: "700",
    marginTop: 8,
  },
  purpleHeroDeltaRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
  },
  purpleHeroDeltaPct: {
    fontSize: 13,
    fontWeight: "900",
  },
  purpleHeroDeltaText: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 13,
    fontWeight: "700",
  },
  purpleDeltaUp: {
    color: "#7fffc0",
  },
  purpleDeltaDown: {
    color: "#ffb3b3",
  },
  pickerOverlay: {
    flex: 1,
    justifyContent: "flex-end",
  },
  pickerBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.55)",
  },
  pickerSheet: {
    backgroundColor: T.card,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingBottom: 40,
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  pickerHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: T.border,
    alignSelf: "center",
    marginBottom: 16,
  },
  pickerYearRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  pickerYearBtn: {
    padding: 4,
  },
  pickerYearText: {
    color: T.text,
    fontSize: 20,
    fontWeight: "900",
    letterSpacing: -0.4,
  },
  pickerGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  pickerCell: {
    width: "22%",
    minHeight: 60,
    borderRadius: 10,
    backgroundColor: T.cardAlt,
    paddingHorizontal: 8,
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  pickerCellSelected: {
    backgroundColor: "#080080",
  },
  pickerCellDisabled: {
    opacity: 0.28,
  },
  pickerCellText: {
    color: T.text,
    fontSize: 13,
    fontWeight: "900",
    lineHeight: 18,
    textAlign: "center",
  },
  pickerCellSelectedText: {
    color: "#ffffff",
  },
  pickerCellDisabledText: {
    color: T.textDim,
  },
});