import { StyleSheet } from "react-native";
import { T } from "@/lib/theme";

export const styles = StyleSheet.create({
  wrap: {
    marginHorizontal: 14,
    marginTop: 14,
    backgroundColor: "#171b2d",
    borderRadius: 28,
    paddingHorizontal: 10,
    paddingTop: 14,
    paddingBottom: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    position: "relative",
    overflow: "hidden",
    shadowColor: "#000000",
    shadowOpacity: 0.24,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 14 },
    elevation: 10,
  },
  heroGlow: {
    position: "absolute",
    borderRadius: 999,
  },
  heroGlowPrimary: {
    width: 220,
    height: 220,
    top: -118,
    right: -54,
    backgroundColor: "rgba(124,92,255,0.18)",
  },
  heroGlowSecondary: {
    width: 180,
    height: 180,
    bottom: -100,
    left: -34,
    backgroundColor: "rgba(255,176,32,0.11)",
  },
  header: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    paddingHorizontal: 8,
    marginBottom: 10,
  },
  headerCopy: {
    flex: 1,
    minWidth: 0,
  },
  headerEyebrow: {
    color: T.textMuted,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  headerTitle: {
    color: T.text,
    fontSize: 18,
    fontWeight: "900",
    marginTop: 4,
    letterSpacing: -0.3,
  },
  headerSub: {
    color: T.textDim,
    fontSize: 12,
    fontWeight: "600",
    lineHeight: 18,
    marginTop: 6,
    maxWidth: 220,
  },
  headerPill: {
    minWidth: 84,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 12,
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  headerPillValue: {
    color: T.text,
    fontSize: 18,
    fontWeight: "900",
  },
  headerPillLabel: {
    color: T.textMuted,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  chartArea: {
    position: "relative",
  },
  chartTouchLayer: {
    position: "absolute",
    zIndex: 2,
  },
  tooltipSlot: {
    justifyContent: "flex-start",
    marginBottom: 8,
  },
  yAxisLabels: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 38,
    width: 38,
  },
  yAxisText: {
    position: "absolute",
    color: T.textDim,
    fontSize: 10,
    fontWeight: "700",
  },
  xLabels: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingLeft: 42,
    paddingRight: 12,
    marginTop: -6,
    gap: 6,
  },
  xLabelButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    borderRadius: 16,
    gap: 5,
  },
  xLabelButtonActive: {
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  xLabelDot: {
    width: 10,
    height: 10,
    borderRadius: 999,
  },
  xLabelText: {
    color: T.textDim,
    fontSize: 11,
    fontWeight: "700",
  },
  xLabelTextActive: {
    color: T.text,
  },
  tooltipCard: {
    backgroundColor: "rgba(16,18,28,0.96)",
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 16,
    paddingVertical: 14,
    shadowColor: "#000",
    shadowOpacity: 0.28,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 10,
  },
  tooltipCardInline: {
    position: "relative",
  },
  tooltipTitle: {
    color: T.textMuted,
    fontSize: 10,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  tooltipTotal: {
    color: T.text,
    fontSize: 18,
    fontWeight: "900",
    marginTop: 4,
  },
  tooltipExpenseBlock: {
    marginTop: 2,
    marginBottom: 10,
  },
  tooltipExpenseName: {
    color: T.text,
    fontSize: 13,
    fontWeight: "800",
  },
  tooltipExpenseMetricRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 4,
    gap: 8,
  },
  tooltipMetricLabel: {
    color: T.textMuted,
    fontSize: 11,
    fontWeight: "600",
  },
  tooltipMetricValueMuted: {
    flex: 1,
    textAlign: "right",
    color: T.textDim,
    fontSize: 11,
    fontWeight: "600",
  },
  tooltipMetricValue: {
    color: T.text,
    fontSize: 11,
    fontWeight: "800",
  },
  tooltipMore: {
    color: T.text,
    fontSize: 12,
    fontWeight: "800",
    marginTop: 2,
  },
  tooltipMeta: {
    color: T.textDim,
    fontSize: 10,
    fontWeight: "700",
    marginTop: 8,
  },
});
