import { StyleSheet } from "react-native";

import { withOpacity } from "@/lib/categoryColors";
import { T } from "@/lib/theme";

export const categoryExpensesStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: T.bg },
  center: { alignItems: "center", justifyContent: "center", paddingVertical: 40, gap: 10 },
  errTxt: { color: T.red, fontSize: 13, textAlign: "center" },
  retryBtn: { backgroundColor: T.accent, borderRadius: 8, paddingHorizontal: 20, paddingVertical: 8 },
  retryTxt: { color: T.onAccent, fontWeight: "700", fontSize: 13 },
  emptyTxt: { color: T.textDim, fontSize: 14, fontWeight: "600" },
  pickerOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0,0,0,0.35)",
  },
  pickerBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  pickerSheet: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    backgroundColor: T.card,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 20,
    borderWidth: 1,
    borderColor: T.border,
  },
  pickerHandle: {
    alignSelf: "center",
    width: 42,
    height: 4,
    borderRadius: 99,
    backgroundColor: T.border,
    marginBottom: 12,
  },
  pickerYearRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
    gap: 18,
  },
  pickerYearBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.cardAlt,
    borderWidth: 1,
    borderColor: T.border,
  },
  pickerYearText: {
    color: T.text,
    fontSize: 18,
    fontWeight: "900",
    minWidth: 70,
    textAlign: "center",
  },
  pickerGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 10,
  },
  pickerCell: {
    width: "30%",
    minWidth: 84,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.cardAlt,
    paddingVertical: 10,
    alignItems: "center",
  },
  pickerCellSelected: {
    borderColor: T.accent,
    backgroundColor: T.accentDim,
  },
  pickerCellText: {
    color: T.text,
    fontWeight: "800",
  },
  pickerCellSelectedText: {
    color: T.text,
  },
  hero: {
    backgroundColor: "#080080",
    paddingHorizontal: 20,
    paddingBottom: 22,
    alignItems: "center",
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    marginBottom: 10,
  },
  heroMonthBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 8,
  },
  heroMonthText: {
    color: withOpacity(T.onAccent, 0.8),
    fontSize: 13,
    fontWeight: "900",
  },
  heroPctPill: {
    marginBottom: 10,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: withOpacity(T.green, 0.35),
    backgroundColor: withOpacity(T.green, 0.14),
  },
  heroPctText: { color: T.green, fontSize: 12, fontWeight: "900" },
  heroAmount: {
    color: T.onAccent,
    fontSize: 48,
    fontWeight: "900",
    letterSpacing: -1,
    marginBottom: 4,
  },
  heroUpdated: { color: withOpacity(T.onAccent, 0.72), fontSize: 12, fontWeight: "700", marginBottom: 12 },
  heroCards: { flexDirection: "row", gap: 10, justifyContent: "center" },
  heroCard: {
    width: 140,
    height: 80,
    backgroundColor: "#03045E",
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  heroCardLbl: { color: withOpacity(T.onAccent, 0.65), fontSize: 11, fontWeight: "700", marginBottom: 5 },
  heroCardVal: { fontSize: 16, fontWeight: "900" },
  heroCardPct: { marginTop: 4, color: withOpacity(T.onAccent, 0.75), fontSize: 12, fontWeight: "900" },
  heroAddBtn: {
    marginTop: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: T.accent,
  },
  heroAddTxt: { color: T.onAccent, fontWeight: "900", fontSize: 13 },
});
