import { StyleSheet } from "react-native";

import { withOpacity } from "@/lib/categoryColors";
import { T } from "@/lib/theme";

export const categoryExpensesStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: T.bg },
  center: { alignItems: "center", justifyContent: "center", paddingVertical: 40, gap: 10 },
  errTxt: { color: T.red, fontSize: 13, textAlign: "center" },
  retryBtn: {
    backgroundColor: T.accent,
    borderRadius: 20,
    paddingHorizontal: 20,
    paddingVertical: 10,
    shadowColor: T.accent,
    shadowOpacity: 0.24,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  retryTxt: { color: T.onAccent, fontWeight: "700", fontSize: 13 },
  emptyTxt: { color: T.textDim, fontSize: 14, fontWeight: "600" },
  pickerOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0,0,0,0.35)",
  },
  pickerBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  pickerSheet: {
    backgroundColor: "#141826",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderTopWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    paddingBottom: 40,
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  pickerHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: "rgba(255,255,255,0.14)",
    alignSelf: "center",
    marginBottom: 16,
  },
  pickerYearRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  pickerYearBtn: {
    padding: 4,
  },
  pickerYearText: {
    color: T.text,
    fontSize: 20,
    fontWeight: "900",
    letterSpacing: -0.4,
  },
  pickerGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  pickerCell: {
    width: "22%",
    height: 52,
    borderRadius: 14,
    backgroundColor: "#1b2033",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
    alignItems: "center",
    justifyContent: "center",
  },
  pickerCellSelected: {
    backgroundColor: "rgba(124,92,255,0.22)",
    borderColor: "rgba(124,92,255,0.3)",
  },
  pickerCellText: {
    color: T.text,
    fontSize: 13,
    fontWeight: "900",
  },
  pickerCellSelectedText: {
    color: "#ffffff",
  },
  hero: {
    backgroundColor: "#161a2d",
    paddingHorizontal: 20,
    paddingBottom: 28,
    alignItems: "center",
    borderBottomLeftRadius: 34,
    borderBottomRightRadius: 34,
    marginBottom: 14,
    overflow: "hidden",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(124,92,255,0.16)",
    shadowColor: "#000000",
    shadowOpacity: 0.2,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 12 },
    elevation: 12,
  },
  heroGlow: {
    position: "absolute",
    borderRadius: 999,
  },
  heroGlowPrimary: {
    width: 240,
    height: 240,
    top: -110,
    right: -72,
    backgroundColor: "rgba(124,92,255,0.22)",
  },
  heroGlowSecondary: {
    width: 200,
    height: 200,
    bottom: -112,
    left: -72,
    backgroundColor: "rgba(68,126,255,0.16)",
  },
  heroInnerBorder: {
    ...StyleSheet.absoluteFillObject,
    borderBottomLeftRadius: 34,
    borderBottomRightRadius: 34,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.03)",
  },
  heroBadge: {
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 12,
    paddingVertical: 7,
    marginBottom: 14,
  },
  heroBadgeText: {
    color: T.accent,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  heroMonthBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 10,
  },
  heroMonthText: {
    color: withOpacity(T.onAccent, 0.8),
    fontSize: 14,
    fontWeight: "900",
  },
  heroPctPill: {
    marginBottom: 12,
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: withOpacity(T.green, 0.35),
    backgroundColor: withOpacity(T.green, 0.14),
  },
  heroPctText: { color: T.green, fontSize: 13, fontWeight: "900" },
  heroAmount: {
    color: T.onAccent,
    fontSize: 48,
    fontWeight: "900",
    letterSpacing: -1,
    marginBottom: 6,
  },
  heroUpdated: { color: withOpacity(T.onAccent, 0.72), fontSize: 13, fontWeight: "700", marginBottom: 14 },
  heroCards: { flexDirection: "row", gap: 12, justifyContent: "center" },
  heroCard: {
    width: 140,
    minHeight: 86,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
  },
  heroCardLbl: { color: withOpacity(T.onAccent, 0.65), fontSize: 11, fontWeight: "700", marginBottom: 5, textTransform: "uppercase", letterSpacing: 0.6 },
  heroCardVal: { fontSize: 17, fontWeight: "900" },
  heroCardPct: { marginTop: 5, color: withOpacity(T.onAccent, 0.75), fontSize: 12, fontWeight: "900" },
  heroSummaryRow: {
    width: "100%",
    flexDirection: "row",
    gap: 10,
    marginTop: 14,
  },
  heroSummaryChip: {
    flex: 1,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.07)",
    paddingHorizontal: 14,
    paddingVertical: 11,
  },
  heroSummaryLabel: {
    color: T.textMuted,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  heroSummaryValue: {
    color: T.text,
    fontSize: 14,
    fontWeight: "800",
    marginTop: 5,
  },
  heroAddBtn: {
    marginTop: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 999,
    backgroundColor: T.accent,
    shadowColor: T.accent,
    shadowOpacity: 0.28,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  heroAddTxt: { color: T.onAccent, fontWeight: "900", fontSize: 14 },
});
