import { StyleSheet } from "react-native";

import { T } from "@/lib/theme";
import { cardBase, cardElevated } from "@/lib/ui";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: T.bg },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingBottom: 8,
    gap: 10,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: { color: T.text, fontSize: 18, fontWeight: "800" },
  headerSpacer: { flex: 1 },
  scroll: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 120, gap: 12 },
  heroCard: { ...cardElevated, padding: 18, gap: 8 },
  heroEyebrow: { color: T.accent, fontSize: 12, fontWeight: "900", textTransform: "uppercase", letterSpacing: 0.3 },
  heroTitle: { color: T.text, fontSize: 20, fontWeight: "900", lineHeight: 26 },
  heroText: { color: T.textDim, fontSize: 14, lineHeight: 21, fontWeight: "600" },
  stateCard: { ...cardBase, padding: 16, gap: 6 },
  stateLabel: { color: T.textDim, fontSize: 12, fontWeight: "800", textTransform: "uppercase", letterSpacing: 0.3 },
  stateValue: { fontSize: 20, fontWeight: "900" },
  stateValueOn: { color: T.green },
  stateValueOff: { color: T.textMuted },
  stateHint: { color: T.textDim, fontSize: 13, fontWeight: "600", lineHeight: 19 },
  toggleCard: { ...cardBase, padding: 16, gap: 12 },
  toggleTitle: { color: T.text, fontSize: 15, fontWeight: "800" },
  toggleRow: { flexDirection: "row", gap: 10 },
  toggle: {
    flex: 1,
    minHeight: 48,
    borderRadius: 16,
    backgroundColor: T.cardAlt,
    borderWidth: 1,
    borderColor: T.border,
    alignItems: "center",
    justifyContent: "center",
  },
  toggleActive: {
    backgroundColor: T.accent,
    borderColor: T.accent,
  },
  toggleDisabled: {
    opacity: 0.45,
  },
  toggleText: { color: T.textDim, fontSize: 15, fontWeight: "800" },
  toggleTextActive: { color: T.onAccent },
  toggleTextDisabled: { color: T.textMuted },
  toggleHint: { color: T.textDim, fontSize: 13, fontWeight: "600", lineHeight: 19 },
  footer: {
    flexDirection: "row",
    gap: 14,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 24,
    borderTopWidth: 1,
    borderTopColor: T.border,
    backgroundColor: `${T.bg}F2`,
  },
  cancelBtn: {
    flex: 1,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: T.border,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 16,
    backgroundColor: T.card,
  },
  cancelBtnText: { color: T.textMuted, fontSize: 14, fontWeight: "800" },
  saveBtn: {
    flex: 1,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 16,
    backgroundColor: T.accent,
  },
  saveBtnText: { color: T.onAccent, fontSize: 14, fontWeight: "800" },
  disabled: { opacity: 0.6 },
});