import { StyleSheet } from "react-native";

import { T } from "@/lib/theme";
import { cardElevated } from "@/lib/ui";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: T.bg },
  scroll: { paddingHorizontal: 16, paddingTop: 10, paddingBottom: 56, gap: 14 },
  cardGlow: {
    position: "absolute",
    borderRadius: 999,
  },
  heroCard: {
    ...cardElevated,
    padding: 20,
    gap: 9,
    borderColor: `${T.accent}30`,
    backgroundColor: `${T.card}F7`,
    overflow: "hidden",
  },
  heroGlowPrimary: {
    width: 190,
    height: 190,
    top: -92,
    right: -80,
    backgroundColor: `${T.accent}20`,
  },
  heroGlowSecondary: {
    width: 120,
    height: 120,
    bottom: -52,
    left: -44,
    backgroundColor: `${T.onAccent}08`,
  },
  heroBadge: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: `${T.accent}18`,
    borderWidth: 1,
    borderColor: `${T.accent}4A`,
  },
  heroBadgeText: {
    color: T.accent,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.2,
    textTransform: "uppercase",
  },
  heroTitle: { color: T.text, fontSize: 20, fontWeight: "900", lineHeight: 27, letterSpacing: -0.3 },
  heroText: { color: T.textDim, fontSize: 14, lineHeight: 21, fontWeight: "600" },
  toggleCard: {
    ...cardElevated,
    padding: 18,
    gap: 12,
    borderColor: `${T.accent}2A`,
    backgroundColor: `${T.card}F7`,
    overflow: "hidden",
  },
  toggleGlowPrimary: {
    width: 168,
    height: 168,
    top: -82,
    right: -70,
    backgroundColor: `${T.accent}1C`,
  },
  toggleGlowSecondary: {
    width: 108,
    height: 108,
    bottom: -48,
    left: -36,
    backgroundColor: `${T.onAccent}08`,
  },
  toggleTitle: { color: T.text, fontSize: 16, fontWeight: "900" },
  switchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  switchPressTarget: {
    borderRadius: 999,
  },
  switchTextWrap: {
    flex: 1,
    gap: 4,
  },
  switchTitle: {
    color: T.text,
    fontSize: 15,
    fontWeight: "800",
  },
  switchHint: {
    color: T.textDim,
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 19,
  },
  toggleHint: { color: T.textDim, fontSize: 13, fontWeight: "600", lineHeight: 19, marginTop: 2 },
  sheetOverlay: {
    flex: 1,
    justifyContent: "flex-end",
  },
  sheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0, 0, 0, 0.48)",
  },
  sheetCard: {
    marginHorizontal: 12,
    marginBottom: 12,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: `${T.border}`,
    backgroundColor: `${T.card}F7`,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 14,
    gap: 12,
    shadowColor: "#000",
    shadowOpacity: 0.24,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  sheetHandle: {
    alignSelf: "center",
    width: 44,
    height: 4,
    borderRadius: 999,
    backgroundColor: `${T.textMuted}55`,
    marginBottom: 2,
  },
  sheetTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  sheetWarningIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: `${T.orange}1A`,
    borderWidth: 1,
    borderColor: `${T.orange}55`,
  },
  sheetTitle: {
    color: T.text,
    fontSize: 17,
    fontWeight: "900",
    letterSpacing: -0.2,
  },
  sheetDescription: {
    color: T.textDim,
    fontSize: 14,
    lineHeight: 21,
    fontWeight: "600",
  },
  sheetActions: {
    flexDirection: "row",
    gap: 10,
  },
  sheetCancelBtn: {
    flex: 1,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: `${T.card}EE`,
    minHeight: 46,
    alignItems: "center",
    justifyContent: "center",
  },
  sheetCancelBtnText: {
    color: T.text,
    fontSize: 14,
    fontWeight: "800",
  },
  sheetDangerBtn: {
    flex: 1,
    borderRadius: 14,
    backgroundColor: T.red,
    minHeight: 46,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: T.red,
    shadowOpacity: 0.24,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 5,
  },
  sheetDangerBtnText: {
    color: T.onAccent,
    fontSize: 14,
    fontWeight: "900",
    letterSpacing: 0.2,
  },
  sheetBtnDisabled: {
    opacity: 0.65,
  },
});