import { StyleSheet } from "react-native";

import { T } from "@/lib/theme";
import { cardElevated, flatInput, flatInputLabel } from "@/lib/ui";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: T.bg },
  flex: { flex: 1 },
  center: { flex: 1, alignItems: "center", justifyContent: "center" },
  scrollContent: { paddingHorizontal: 18, paddingBottom: 40, gap: 12 },
  scanShortcutCard: {
    ...cardElevated,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  scanShortcutIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: `${T.accent}18`,
  },
  scanShortcutCopy: {
    flex: 1,
    minWidth: 0,
  },
  scanShortcutTitle: {
    color: T.text,
    fontSize: 15,
    fontWeight: "800",
  },
  scanShortcutSub: {
    color: T.textDim,
    fontSize: 12,
    fontWeight: "600",
    marginTop: 2,
  },
  amountCard: {
    ...cardElevated,
    borderRadius: 20,
    padding: 20,
    borderColor: T.accentBorder,
    marginTop: 4,
  },
  amountLabelRow: { flexDirection: "row", alignItems: "center", gap: 5, marginBottom: 10 },
  amountLabel: { color: T.textDim, fontSize: 13, fontWeight: "500" },
  fieldCard: {
    ...flatInput,
    paddingVertical: 12,
  },
  fieldLabel: { ...flatInputLabel, marginBottom: 8 },
  fieldInput: { color: T.text, fontSize: 18, fontWeight: "500", padding: 0 },
  fieldRow: { flexDirection: "row", alignItems: "center" },
  fieldValue: { flex: 1, color: T.text, fontSize: 18, fontWeight: "500" },
  fieldPlaceholder: { flex: 1, color: T.textMuted, fontSize: 18, fontWeight: "500" },
  fieldChevron: { marginLeft: 6 },
  catDot: { width: 10, height: 10, borderRadius: 5, marginRight: 10 },
  errorWrap: { flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 4 },
  errorText: { color: T.red, fontSize: 13, flex: 1 },
  footerOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 20,
    elevation: 20,
    overflow: "hidden",
  },
  footerBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  footerBackdropTint: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(10,13,24,0.30)",
  },
  footerInner: {
    paddingHorizontal: 18,
    paddingTop: 16,
    alignItems: "center",
  },
  submitBtn: {
    alignSelf: "center",
    borderRadius: 999,
    overflow: "hidden",
    shadowColor: "#000000",
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: -2 },
    elevation: 8,
  },
  submitBtnGlass: {
    minHeight: 56,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 184,
    paddingHorizontal: 24,
    paddingVertical: 15,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.62)",
    backgroundColor: "rgba(255,255,255,0.78)",
    overflow: "hidden",
  },
  submitBtnTint: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  submitBtnGlow: {
    position: "absolute",
    width: 148,
    height: 148,
    borderRadius: 999,
    right: -20,
    top: -56,
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  submitBtnInnerBorder: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.38)",
  },
  submitBtnContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  submitBtnPressed: {
    transform: [{ scale: 0.985 }],
  },
  submitBtnDisabled: { shadowOpacity: 0.08, elevation: 2 },
  submitTxt: { color: "#111827", fontSize: 16, fontWeight: "800" },
  modalOverlay: { flex: 1 },
  modalBackdrop: { flex: 1, backgroundColor: "rgba(0,0,0,0.5)" },
  modalSheet: {
    backgroundColor: T.card,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 12,
    paddingHorizontal: 18,
    paddingBottom: 40,
    maxHeight: "75%",
  },
  sheetHandle: {
    width: 40,
    height: 4,
    backgroundColor: T.border,
    borderRadius: 2,
    alignSelf: "center",
    marginBottom: 16,
  },
  sheetTitle: { color: T.text, fontSize: 16, fontWeight: "700", marginBottom: 12 },
  catList: { paddingBottom: 8 },
  catRow: { flexDirection: "row", alignItems: "center", paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: T.border },
  catRowSelected: { backgroundColor: `${T.accent}0d`, marginHorizontal: -18, paddingHorizontal: 18 },
  catName: { flex: 1, color: T.text, fontSize: 15 },
  catCheck: { marginLeft: 8 },
  pickerYearRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    marginBottom: 16,
  },
  pickerYearBtn: { width: 32, height: 32, alignItems: "center", justifyContent: "center" },
  pickerYearText: { color: T.text, fontSize: 22, fontWeight: "700", minWidth: 60, textAlign: "center" },
  pickerGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    justifyContent: "space-between",
  },
  pickerCell: {
    width: "23%",
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: T.border,
    backgroundColor: T.cardAlt,
    alignItems: "center",
  },
  pickerCellSelected: { backgroundColor: T.accent, borderColor: T.accent },
  pickerCellText: { color: T.textDim, fontSize: 14, fontWeight: "500" },
  pickerCellSelectedText: { color: T.onAccent, fontWeight: "700" },
  emptySheetState: { color: T.textMuted, fontSize: 14, paddingVertical: 8 },
});