import { StyleSheet } from "react-native";

import { T } from "@/lib/theme";
import { cardElevated } from "@/lib/ui";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: T.bg },
  scrollView: { backgroundColor: T.bg },
  center: { flex: 1, justifyContent: "center", alignItems: "center", gap: 10, paddingHorizontal: 24 },
  stateText: { color: T.textDim, fontSize: 14, fontWeight: "700" },
  errorText: { color: T.red, fontSize: 14, textAlign: "center" },
  retryBtn: { marginTop: 10, backgroundColor: T.accent, borderRadius: 10, paddingHorizontal: 20, paddingVertical: 10 },
  retryTxt: { color: T.onAccent, fontWeight: "800" },
  header: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 30,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 8,
    paddingBottom: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: T.border,
    overflow: "hidden",
  },
  headerBlur: {
    ...StyleSheet.absoluteFillObject,
  },
  headerGlassTint: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(11,13,20,0.72)",
  },
  backBtn: { paddingHorizontal: 6, paddingVertical: 4 },
  headerTitle: {
    position: "absolute",
    left: 56,
    right: 56,
    bottom: 14,
    textAlign: "center",
    color: T.text,
    fontSize: 17,
    fontWeight: "900",
  },
  headerSpacer: { width: 36, height: 32 },
  scroll: { padding: 16, paddingBottom: 40, gap: 14 },
  heroCard: {
    ...cardElevated,
    padding: 18,
    gap: 16,
    backgroundColor: T.card,
  },
  heroCopy: { gap: 8 },
  eyebrow: { color: T.accent, fontSize: 12, fontWeight: "900", textTransform: "uppercase", letterSpacing: 1 },
  heroTitle: { color: T.text, fontSize: 24, fontWeight: "900", lineHeight: 28 },
  heroText: { color: T.textDim, fontSize: 14, fontWeight: "600", lineHeight: 20 },
  heroScenarioNote: { color: T.textDim, fontSize: 13, fontWeight: "700", lineHeight: 18 },
  heroScenarioPositive: { color: T.green, fontWeight: "900" },
  heroScenarioNegative: { color: T.red, fontWeight: "900" },
  scenarioWrap: { gap: 10 },
  scenarioLabel: { color: T.textMuted, fontSize: 11, fontWeight: "900", textTransform: "uppercase", letterSpacing: 0.6 },
  sliderWrap: { gap: 10 },
  sliderHeaderRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  sliderValueLabel: { color: T.textDim, fontSize: 13, fontWeight: "800" },
  sliderValue: { color: T.text, fontSize: 20, fontWeight: "900" },
  sliderTrackWrap: {
    height: 34,
    justifyContent: "center",
  },
  sliderTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: T.cardAlt,
  },
  sliderTrackFill: {
    position: "absolute",
    left: 0,
    height: 8,
    borderRadius: 999,
    backgroundColor: T.accent,
  },
  sliderBaselineMarker: {
    position: "absolute",
    marginLeft: -1,
    width: 2,
    height: 18,
    borderRadius: 999,
    backgroundColor: "rgba(244,246,255,0.65)",
  },
  sliderTick: {
    position: "absolute",
    marginLeft: -1,
    width: 2,
    height: 10,
    borderRadius: 999,
    backgroundColor: "rgba(244,246,255,0.26)",
  },
  sliderThumb: {
    position: "absolute",
    marginLeft: -16,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: T.onAccent,
    borderWidth: 4,
    borderColor: T.accent,
    top: 1,
    shadowColor: "#000000",
    shadowOpacity: 0.22,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  sliderLegendRow: { flexDirection: "row", justifyContent: "space-between", gap: 12 },
  sliderLegendText: { color: T.textMuted, fontSize: 11, fontWeight: "700" },
  metricGrid: { flexDirection: "row", gap: 10 },
  metricCard: {
    flex: 1,
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: T.border,
    backgroundColor: T.cardAlt,
    padding: 12,
    gap: 6,
  },
  metricLabel: { color: T.textMuted, fontSize: 11, fontWeight: "800", textTransform: "uppercase", letterSpacing: 0.5 },
  metricValue: { color: T.text, fontSize: 16, fontWeight: "900" },
  chartCard: {
    ...cardElevated,
    padding: 16,
    gap: 14,
    backgroundColor: T.card,
  },
  chartHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  chartTitle: { color: T.text, fontSize: 18, fontWeight: "900" },
  chartSubtitle: { color: T.textDim, fontSize: 12, fontWeight: "700", marginTop: 4 },
  chartPill: {
    borderRadius: 999,
    backgroundColor: T.cardAlt,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: T.border,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  chartPillText: { color: T.accent, fontSize: 11, fontWeight: "900", textTransform: "uppercase", letterSpacing: 0.5 },
  chartShell: { flexDirection: "row", gap: 10, alignItems: "stretch" },
  yAxisCol: { width: 62, justifyContent: "space-between", paddingTop: 10, paddingBottom: 30 },
  yAxisTxt: { color: T.textMuted, fontSize: 10, fontWeight: "700" },
  chartCanvasWrap: {
    flex: 1,
    borderRadius: 22,
    overflow: "hidden",
    backgroundColor: T.cardAlt,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: T.border,
    paddingHorizontal: 8,
    paddingTop: 4,
  },
  legendRow: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginBottom: 10 },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: T.cardAlt,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: T.border,
  },
  legendDot: { width: 8, height: 8, borderRadius: 999 },
  legendTxt: { color: T.textDim, fontSize: 11, fontWeight: "800" },
  axisRow: { marginTop: -4, marginLeft: 72, flexDirection: "row", justifyContent: "space-between" },
  axisTxt: { color: T.textMuted, fontSize: 11, fontWeight: "700" },
  outlookSectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 6,
    marginBottom: 2,
  },
  outlookTitle: { color: T.text, fontSize: 18, fontWeight: "900" },
  outlookCaption: { color: T.textMuted, fontSize: 12, fontWeight: "800" },
  goalCard: {
    ...cardElevated,
    padding: 16,
    gap: 12,
    backgroundColor: T.card,
  },
  goalCardTopRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 12 },
  goalCardTitleWrap: { flexDirection: "row", alignItems: "center", gap: 10, flex: 1 },
  goalSwatch: { width: 10, height: 36, borderRadius: 999 },
  goalCardTitle: { color: T.text, fontSize: 17, fontWeight: "900" },
  goalCardSubtitle: { color: T.textDim, fontSize: 12, fontWeight: "700", marginTop: 2 },
  statusPill: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: T.cardAlt,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: T.border,
  },
  statusPillText: { color: T.text, fontSize: 11, fontWeight: "900" },
  progressMetaRow: { flexDirection: "row", justifyContent: "space-between", gap: 12 },
  progressMetaLabel: { color: T.textDim, fontSize: 12, fontWeight: "700" },
  progressBarTrack: {
    height: 12,
    borderRadius: 999,
    backgroundColor: T.cardAlt,
    overflow: "hidden",
    position: "relative",
  },
  progressBarNow: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    borderRadius: 999,
    opacity: 0.85,
  },
  progressBarProjected: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    borderRadius: 999,
    borderWidth: 2,
    backgroundColor: "transparent",
  },
  statsRow: { flexDirection: "row", gap: 10 },
  statBlock: {
    flex: 1,
    paddingTop: 2,
  },
  statLabel: { color: T.textMuted, fontSize: 11, fontWeight: "800", textTransform: "uppercase", letterSpacing: 0.4 },
  statValue: { color: T.text, fontSize: 13, fontWeight: "800", marginTop: 4 },
  emptyCard: {
    ...cardElevated,
    padding: 18,
    gap: 10,
    alignItems: "flex-start",
    backgroundColor: T.card,
  },
  emptyIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: T.accentDim,
  },
  emptyTitle: { color: T.text, fontSize: 15, fontWeight: "900" },
  emptyDetail: { color: T.textDim, fontSize: 13, fontWeight: "600", lineHeight: 18 },
});