import { StyleSheet } from "react-native";
import { T } from "@/lib/theme";

const SIZE = 210;

export const styles = StyleSheet.create({
  wrap: {
    gap: 14,
    alignItems: "stretch",
  },
  heroCard: {
    position: "relative",
    overflow: "hidden",
    alignItems: "center",
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "rgba(124,92,255,0.16)",
    backgroundColor: "#171b2d",
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 20,
    shadowColor: "#000000",
    shadowOpacity: 0.24,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
    elevation: 10,
  },
  heroGlow: {
    position: "absolute",
    borderRadius: 999,
  },
  heroGlowPrimary: {
    width: 220,
    height: 220,
    top: -110,
    right: -46,
    backgroundColor: "rgba(124,92,255,0.22)",
  },
  heroGlowSecondary: {
    width: 180,
    height: 180,
    bottom: -90,
    left: -22,
    backgroundColor: "rgba(255,181,37,0.16)",
  },
  heroBadge: {
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginBottom: 10,
  },
  heroBadgeText: {
    color: T.accent,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  heroTitle: {
    color: T.text,
    fontSize: 16,
    fontWeight: "900",
    textAlign: "center",
  },
  heroSubtitle: {
    color: T.textDim,
    fontSize: 12,
    fontWeight: "700",
    textAlign: "center",
    lineHeight: 18,
    marginTop: 4,
  },
  chartShell: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 14,
    paddingVertical: 8,
  },
  chartHalo: {
    position: "absolute",
    width: 250,
    height: 250,
    borderRadius: 125,
    backgroundColor: "rgba(255,255,255,0.03)",
  },
  chartWrap: {
    width: SIZE,
    height: SIZE,
    alignItems: "center",
    justifyContent: "center",
  },
  centerLabel: {
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
  },
  centerEyebrow: {
    color: T.textMuted,
    fontSize: 11,
    fontWeight: "700",
    textAlign: "center",
    marginBottom: 6,
  },
  centerTitle: {
    color: T.textDim,
    fontSize: 14,
    fontWeight: "800",
    textAlign: "center",
  },
  centerValue: {
    color: T.text,
    fontSize: 21,
    fontWeight: "900",
    marginTop: 4,
  },
  heroStatsRow: {
    width: "100%",
    flexDirection: "row",
    gap: 10,
    marginTop: 10,
  },
  heroStatCard: {
    flex: 1,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 4,
  },
  heroStatLabel: {
    color: T.textMuted,
    fontSize: 11,
    fontWeight: "700",
  },
  heroStatValue: {
    color: T.text,
    fontSize: 15,
    fontWeight: "900",
  },
  legend: {
    width: "100%",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    justifyContent: "space-between",
  },
  legendCard: {
    width: "48.5%",
    minHeight: 124,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    backgroundColor: "#171b2d",
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 10,
    justifyContent: "space-between",
  },
  legendCardMuted: {
    opacity: 0.7,
  },
  legendTopRow: {
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    gap: 10,
  },
  legendLabelWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    width: "100%",
    minWidth: 0,
  },
  dot: {
    width: 10,
    height: 10,
    borderRadius: 999,
  },
  legendLabel: {
    color: T.text,
    fontSize: 14,
    fontWeight: "800",
  },
  legendValueWrap: {
    alignItems: "flex-start",
    gap: 4,
  },
  legendPct: {
    color: T.textMuted,
    fontSize: 11,
    fontWeight: "700",
  },
  legendValue: {
    color: T.text,
    fontSize: 16,
    fontWeight: "900",
  },
  legendBarBg: {
    height: 7,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.08)",
    overflow: "hidden",
  },
  legendBarFill: {
    height: 7,
    borderRadius: 999,
  },
});
